### ISSUE TITLE
Unable to add Document using GPTTreeIndex.insert

### ISSUE THREAD

**Issue by hxbs-zyy** [jerryjliu/llama_index#1042]
I want to use GPTTreeIndex to build an index for batches of documents, but I found an error when using the insert function.
Below is my case：
```
import os

from llama_index import SimpleDirectoryReader, GPTTreeIndex

os.environ["OPENAI_API_KEY"] = "xxx"
index_name = "./index.json"


def get_index() -> GPTTreeIndex:
    """
    Initialize the index, if the index already exists,
    use the already trained index, otherwise create a new index
    """
    if os.path.exists(index_name):
        index = GPTTreeIndex.load_from_disk(index_name)
    else:
        index = GPTTreeIndex([])
        index.save_to_disk(index_name)
    return index


def insert_into_index(doc_file_path) -> None:
    """Insert document into index"""

    index = get_index()
    documents = SimpleDirectoryReader(input_files=[doc_file_path]).load_data()
    for doc in documents:
        index.insert(doc)
    index.save_to_disk(index_name)


if __name__ == '__main__':
    insert_into_index('./pdfs/茅台1.pdf')
```
Below is the error message：
```
Traceback (most recent call last):
  File "/Users/yueyang/Desktop/ant/finassetpreference/我的GPTDemo/save_to_index.py", line 60, in <module>
    insert_into_index('./pdfs/茅台1.pdf')
  File "/Users/yueyang/Desktop/ant/finassetpreference/我的GPTDemo/save_to_index.py", line 52, in insert_into_index
    index.insert(Document.from_langchain_format(doc))
  File "/Library/Python/3.9/site-packages/llama_index/indices/base.py", line 144, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "/Library/Python/3.9/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/llama_index/indices/base.py", line 139, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "/Library/Python/3.9/site-packages/llama_index/indices/tree/base.py", line 125, in _insert
    inserter.insert(nodes)
  File "/Library/Python/3.9/site-packages/llama_index/indices/tree/inserter.py", line 159, in insert
    self._insert_node(node)
  File "/Library/Python/3.9/site-packages/llama_index/indices/tree/inserter.py", line 114, in _insert_node
    elif len(self.index_graph.get_children(cur_graph_node_list[0])) == 0:
  File "/Library/Python/3.9/site-packages/llama_index/data_structs/data_structs_v2.py", line 94, in get_children
    children_ids = self.node_id_to_children_ids[parent_id]
KeyError: '4e432679-ee81-4c25-875c-8678982048b3'
```
After troubleshooting, it was found that the IndexGraph.insert_under_parent function did not create a corresponding child node empty sequence in node_id_to_children_ids when adding a parent node. Causes an error on subsequent calls to IndexGraph.get_children.

I try to fix using the code below:
```
    def get_children(self, parent_node: Optional[Node]) -> Dict[int, str]:
        """Get children nodes."""
        if parent_node is None:
            return self.root_nodes
        else:
            parent_id = parent_node.get_doc_id()
            # ###########
            if parent_id not in self.node_id_to_children_ids:  # Returns an empty dictionary if not in node_id_to_children_ids
                return {}
            # ###########
            children_ids = self.node_id_to_children_ids[parent_id]
            return {
                self.node_id_to_index[child_id]: child_id for child_id in children_ids
            }
```
Can you please help me to look into this issue? Is it me or is there something wrong with the way I use it? If it is a missing bug, I submit a pr.

**Comment by Disiok** [comment]
Looks like a bug, would be amazing if you can submit a PR with the fix!

**Comment by sheresaidon** [comment]
The KeyError suggests the key is not present in the self.node_id_to_children_ids dictionary. I was getting the same issue one  fix I found is that you could check whether the key exists in the dictionary before attempting to access it. You can use the get() method, which returns a default value if the key is not present.

updating this line:
children_ids = self.node_id_to_children_ids[parent_id]

with:
children_ids = self.node_id_to_children_ids.get(parent_id, [])

that prevented the key error for me
