### ISSUE TITLE
OpenAI LLM being used even when using ServiceContext with a custom LLM

### ISSUE THREAD

**Issue by kirtishrinkhala** [jerryjliu/llama_index#1058]
Version : llama_index 5.7

```
llm = Anthropic(anthropic_api_key=ANTHROPIC_API_KEY, temperature=0)
llm_predictor = LLMPredictor(llm=llm)

model_name = "sentence-transformers/sentence-t5-large"
hf = HuggingFaceEmbeddings(model_name=model_name)
embed_model = LangchainEmbedding(hf)

parser = SimpleNodeParser()
nodes = parser.get_nodes_from_documents(documents)

max_input_size = 4096
num_output = 256
max_chunk_overlap = 20

prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper

index = GPTSimpleVectorIndex(nodes, service_context=service_context)

```

Error:

```
Traceback (most recent call last):
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, engine=engine).data
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/openai/api_requestor.py", line 130, in __init__
    self.api_key = key or util.default_api_key()
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://onboard.openai.com for details, or email support@openai.com if you have any questions.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/agent/c_agent.py", line 140, in get_txt_plans_index_global
    index = GPTSimpleVectorIndex(nodes, service_context=service_context)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/vector_store/vector_indices.py", line 94, in __init__
    super().__init__(
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 57, in __init__
    super().__init__(
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/base.py", line 69, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 213, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 202, in _build_index_from_nodes
    self._add_nodes_to_index(index_struct, nodes)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 181, in _add_nodes_to_index
    embedding_results = self._get_node_embedding_results(
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 99, in _get_node_embedding_results
    ) = self._service_context.embed_model.get_queued_text_embeddings()
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/embeddings/base.py", line 151, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/llama_index/embeddings/openai.py", line 261, in _get_text_embeddings
    embeddings = get_embeddings(texts, engine=engine)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f7070b38b50 state=finished raised AuthenticationError>]
```

**Comment by logan-markewich** [comment]
There are two models, the LLM and the embedding model

The embedding model will default to text-ada-002. You need to provide this as well if you want everything to run locally.

You can run any embedding model from huggingface by following this guide: https://gpt-index.readthedocs.io/en/latest/how_to/customization/embeddings.html#custom-embeddings

**Comment by kirtishrinkhala** [comment]
Thanks! Got it working!
