### ISSUE TITLE
[Bug] GPTFaissIndex.load_from_disk crashes when passing faiss_index_save_path and service_context

### ISSUE THREAD

**Issue by titu1994** [jerryjliu/llama_index#1134]
Trying to restore a GPTFaissIndex with a custom service_context in load_from_disk will throw an error (shown below) due to incorrect dict being passed into its constructor.

-----

# Pseudo code to build an index 

```python
llm = CustomLLM()
llm_predictor = LLMPredictor(llm=llm)
prompt_helper = llm.get_prompt_helper()

# Embedding model setup
embedding_model, embed_dim = get_hf_embedding_model()
embedding_model = LangchainEmbedding(embedding_model)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper,
                                               embed_model=embedding_model)

faiss_index = faiss.IndexFlatL2(embed_dim)

# Load the your data
documents = SimpleDirectoryReader(input_files=[data_path], recursive=True).load_data()
index = GPTFaissIndex.from_documents(documents, faiss_index=faiss_index, service_context=service_context)

save_dir, filename = os.path.split(index_save_path)
filename, filext = os.path.splitext(filename)

if not os.path.exists(save_dir):
    os.makedirs(save_dir, exist_ok=True)

faiss_index_save_path = os.path.join(save_dir, f'{filename}-faiss.index')

index.save_to_disk(index_save_path, faiss_index_save_path=faiss_index_save_path, encoding='utf-8')

```

-----

# Pseudo code to load an index 

```python

# LLM setup
llm = CustomLLM()
llm_predictor = LLMPredictor(llm=llm)
prompt_helper = llm.get_prompt_helper()

# Embedding model setup
embedding_model, embed_dim = get_hf_embedding_model()
embedding_model = LangchainEmbedding(embedding_model)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper,
                                               embed_model=embedding_model)

# Load the index
index_dir, filename = os.path.split(cfg.index_path)
filename, filext = os.path.splitext(filename)
faiss_index_load_path = os.path.join(index_dir, f'{filename}-faiss.index')

index = GPTFaissIndex.load_from_disk(
    cfg.index_path,
    faiss_index_save_path=faiss_index_load_path,
    service_context=service_context,
)

```

# Error that is raised

```python

Traceback (most recent call last):
  ...
    index = GPTFaissIndex.load_from_disk(
  File ".../llama_index/indices/vector_store/vector_indices.py", line 152, in load_from_disk
    return super().load_from_disk(save_path, faiss_index=faiss_index, **kwargs)
  File ".../llama_index/indices/base.py", line 364, in load_from_disk
    return cls.load_from_string(file_contents, **kwargs)
  File ".../llama_index/indices/base.py", line 340, in load_from_string
    return cls.load_from_dict(result_dict, **kwargs)
  File ".../llama_index/indices/vector_store/base.py", line 260, in load_from_dict
    vector_store = load_vector_store_from_dict(
  File ".../llama_index/vector_stores/registry.py", line 61, in load_vector_store_from_dict
    return cls.from_dict(config_dict)
  File ".../llama_index/vector_stores/faiss.py", line 52, in from_dict
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'service_context'

```

This error shows up in `faiss.py` in the class method `from_dict()`

```python
 @classmethod
    def from_dict(cls, config_dict: Dict[str, Any]) -> "FaissVectorStore":
        if "faiss_index" in config_dict:
            return cls(**config_dict)
        else:
            ...
```

# Fix

One line modification of the if condition to explicitly extract arguments (or at least pop out unnecessary arguments)

```python
 @classmethod
    def from_dict(cls, config_dict: Dict[str, Any]) -> "FaissVectorStore":
        if "faiss_index" in config_dict:
            return cls(faiss_index=config_dict['faiss_index'], save_path=config_dict['save_path'])
        else:
            ...
```

# Minor Bug

Another thing is that the build index code above will save both json and index file to the correct location, but also save a duplicate of the index at PWD called `faiss.json`. The code also has hard coded assumptions of where this "default" index should be - and it will be overridden when you try to construct multiple indices.

# Library version

llama_index 0.5.12

**Comment by titu1994** [comment]
Hi @Disiok , any update on this?

**Comment by sumihiro** [comment]
I have same issue.

**Comment by logan-markewich** [comment]
Since we no longer have `GPTFaissIndex`, I don't think this is an issue anymore?

Feel free to check out the latest Faiss example here

https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/FaissIndexDemo.html
