### ISSUE TITLE
ValueError: A single term is larger than the allowed chunk size.

### ISSUE THREAD

**Issue by cxgreat2014** [jerryjliu/llama_index#1196]
```log
Error: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/managers.py", line 211, in handle_request
    result = func(c, *args, **kwds)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/managers.py", line 378, in create
    obj = callable(*args, **kwds)
  File "/Users/macuser/PycharmProjects/GPTKB/llama_index_starter_pack/flask_react/./index_server.py", line 54, in insert_into_index
    index.insert(document)
  File "/Users/macuser/PycharmProjects/GPTKB/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 143, in insert
    nodes = self.service_context.node_parser.get_nodes_from_documents([document])
  File "/Users/macuser/PycharmProjects/GPTKB/venv/lib/python3.9/site-packages/llama_index/node_parser/simple.py", line 30, in get_nodes_from_documents
    nodes = get_nodes_from_document(
  File "/Users/macuser/PycharmProjects/GPTKB/venv/lib/python3.9/site-packages/llama_index/node_parser/node_utils.py", line 49, in get_nodes_from_document
    text_splits = get_text_splits_from_document(
  File "/Users/macuser/PycharmProjects/GPTKB/venv/lib/python3.9/site-packages/llama_index/node_parser/node_utils.py", line 30, in get_text_splits_from_document
    text_splits = text_splitter.split_text_with_overlaps(
  File "/Users/macuser/PycharmProjects/GPTKB/venv/lib/python3.9/site-packages/llama_index/langchain_helpers/text_splitter.py", line 157, in split_text_with_overlaps
    raise ValueError(
ValueError: A single term is larger than the allowed chunk size.
Term size: 1042
Chunk size: 512Effective chunk size: 512
---------------------------------------------------------------------------
```

test_document.md :

[test_document.md](https://github.com/jerryjliu/llama_index/files/11238817/test_document.md)

**Comment by cxgreat2014** [comment]
use https://github.com/logan-markewich/llama_index_starter_pack/tree/main/flask_react upload document will see this error in browser network panel uploadfile request 's response preview tab
