### ISSUE TITLE
StableLM not returning response when querying with GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by Jegama** [jerryjliu/llama_index#1334]
I created an index with StableLM as the LLM like this

```python
stablelm = HuggingFacePipeline.from_model_id(model_id=repo_id, task="text-generation",  model_kwargs={"max_length":1024})
embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
llm_predictor = LLMPredictor(llm=stablelm)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model)
index = GPTSimpleVectorIndex(nodes, service_context=service_context)

response = index.query("Cool question")

print('\nStr - ', str(response))
print('\nDot response - ', response.response)
print('\nSource Node - ', response.get_formatted_sources())
```

But the first 2 prints return empty. I know it's working because `response.get_formatted_sources()` returns the correct node. Any ideas why is this happening? Is it langchain, or llama_index?

**Comment by logan-markewich** [comment]
@Jegama we actually added some official support for stable lm, given how reputable they are.

Check out this notebook and let me know if it helps https://github.com/jerryjliu/llama_index/blob/main/examples/llms/SimpleIndexDemo-StableLM.ipynb

**Comment by Jegama** [comment]
Hi @logan-markewich, the authentication is not working 😞 . I get this error.

```
Traceback (most recent call last):
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\embeddings\openai.py", line 106, in get_embedding
    return openai.Embedding.create(input=[text], engine=engine)["data"][0]["embedding"]
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\openai\api_requestor.py", line 130, in __init__
    self.api_key = key or util.default_api_key()
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details, or email support@openai.com if you have any questions.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Dev\testing_llama\index_representative.py", line 13, in <module>
    response = index.query('Where did he go to school?', mode='embedding')
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\base.py", line 260, in query
    return query_runner.query(query_str)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\query\query_runner.py", line 349, in query
    return query_combiner.run(query_bundle, level)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\query\query_combiner\base.py", line 68, in run
    return self._query_runner.query_transformed(
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\query\query_runner.py", line 209, in query_transformed
    return query_obj.query(query_bundle)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\query\base.py", line 206, in query
    nodes = self.retrieve(query_bundle)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\query\base.py", line 166, in retrieve
    nodes = self._retrieve(query_bundle, similarity_tracker=similarity_tracker)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\indices\vector_store\base_query.py", line 62, in _retrieve
    self._service_context.embed_model.get_agg_embedding_from_queries(
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\embeddings\base.py", line 83, in get_agg_embedding_from_queries
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\embeddings\base.py", line 83, in <listcomp>
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\embeddings\base.py", line 72, in get_query_embedding
    query_embedding = self._get_query_embedding(query)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\llama_index\embeddings\openai.py", line 223, in _get_query_embedding
    return get_embedding(query, engine=engine)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\__\anaconda3\envs\testing_llama\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1d57b78eec0 state=finished raised AuthenticationError>]
```

I have the api key on my `.env`

**Comment by logan-markewich** [comment]
@Jegama try setting the key directly I'm the code maybe?

```
import os
os.environ["OPENAI_API_KEY"] = "key"
```

**Comment by Jegama** [comment]
Same error boss, I tested with `llama-index-0.5.25` and today I updated it to `llama-index-0.5.27`

**Comment by mpvcs00** [comment]
pip install 'pdftotext==2.2.2' 'llama-index==0.5.27' 'nltk==3.8.1' 'requests==2.28.2' 'langchain==0.0.142'

https://github.com/jerryjliu/llama_index/issues/1723

import io

import pdftotext
import requests
from langchain.schema import Document
from llama_index.langchain_helpers.text_splitter import SentenceSplitter

r = requests.get(
    'https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/d30155b8-b438-11ed-85e8-02420a0001f7/Chetan%20Bhagat%20-three%20mistakes%20of%20my%20life.pdf'
)
data = r.content
pages = list(pdftotext.PDF(io.BytesIO(data)))
text_splitter = SentenceSplitter(chunk_size=200, chunk_overlap=0)
documents = text_splitter.split_documents([Document(page_content=page) for page in pages])
for doc in documents:
    print(doc.page_content)
    print('---')

**Comment by Disiok** [comment]
Could you try with the latest version and re-open if the issue still persists?
