### ISSUE TITLE
GPTVectorStoreIndex: Reference doc id is None. 

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [jerryjliu/llama_index#1348]
Hello, 
I am trying to build a `GPTSimpleVectorIndex` index using a `LangChain` embedding model but I get an error due to the `ref_doc_id` beeing `None`.

<details>
<summary>Error</summary>

```
Traceback (most recent call last):
  File "/Users/andrea/git/KG_construction_with_LLAMA/kb_builder.py", line 57, in <module>
    kb_index = GPTSimpleVectorIndex(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/vector_store/vector_indices.py", line 73, in __init__
    super().__init__(
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 54, in __init__
    super().__init__(
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/base.py", line 74, in __init__
    index_struct = self.build_index_from_nodes(nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 217, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 206, in _build_index_from_nodes
    self._add_nodes_to_index(index_struct, nodes)
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 178, in _add_nodes_to_index
    embedding_results = self._get_node_embedding_results(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrea/.miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 104, in _get_node_embedding_results
    raise ValueError("Reference doc id is None.")
ValueError: Reference doc id is None.
```
</details>

Going in order: 
- I create a list of nodes (with text given by the edges of a `Networkx` graph `g`, but this should not be relevant)
```
from llama_index.data_structs.node_v2 import Node

nodes = []
for n in g.nodes():
    edges = list(g.in_edges(n, data=True)) + list(g.out_edges(n, data=True))
    edges = [
        '({}, {}, {})'.format(e[0], e[2]['title'], e[1])
        for e in edges
    ]
    text = '\n'.join(edges)
    node = Node(
        text=text,
        doc_id=n,
    )
    nodes.append(node)
```
- I set up a `service_context` using `Huggingface` and `LangChain` 
```
from transformers import pipeline as Pipeline
from transformers import AutoTokenizer
from langchain.llms import HuggingFacePipeline
from langchain.embeddings import HuggingFaceEmbeddings
from llama_index.indices.service_context import ServiceContext
from llama_index import LLMPredictor
from llama_index.embeddings.langchain import LangchainEmbedding

tokenizer = AutoTokenizer.from_pretrained(model_id)
pipe = Pipeline(
   'text-generation',
    model=model_id,
    tokenizer=tokenizer,
    max_new_tokens=64,
    device_map='auto', # used for distributed
    model_kwargs={"torch_dtype":torch.bfloat16}
)
llm = HuggingFacePipeline(pipeline=pipe)
llm_predictor = LLMPredictor(llm = llm)
emb = HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2')
emb = LangchainEmbedding(emb)
service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=emb,
    chunk_size_limit=512
)
```
- and then just try to build the index
```
from llama_index.indices.vector_store.vector_indices import GPTSimpleVectorIndex

kb_index = GPTSimpleVectorIndex(
    nodes=nodes,
    service_context=service_context
)
```

but unfortunately, the `ref_doc_id` of each node is `None`, since I did not set any relationship between the nodes I guess, and I get the value error reported above. 
Would passing the relationships upon node creation solve this? If yes, how are you supposed to do it? Why, although each node has its own `doc_id`, is it so important to have `ref_doc_id` for index creation anyway?

**Comment by BrunoLiegiBastonLiegi** [comment]
A little update: I added the relationships between the nodes by doing:
```
from llama_index.data_structs.node_v2 import DocumentRelationship

for i,n in enumerate(nodes):
    if i < len(nodes) - 1:
        n.relationships[DocumentRelationship.NEXT] = nodes[i+1].get_doc_id()
    if i > 0:
        n.relationships[DocumentRelationship.PREVIOUS] = nodes[i-1].get_doc_id()
```
as suggested in the [usage pattern section of the docs](https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#parse-the-documents-into-nodes), but still it is complaining about missing `ref_doc_id` upon index construction.
Can anyone help with this?

**Comment by Disiok** [comment]
Hey @BrunoLiegiBastonLiegi , thanks for the issue.

Enforcing the ref_doc_id is not None is definitely a very weird behavior. We are gonna fix this.

In the meanwhile, if you can unblock yourself by setting `DocumentRelationship .SOURCE`

**Comment by BrunoLiegiBastonLiegi** [comment]
Thanks!
Indeed setting the `SOURCE` relationship:
```
for i,n in enumerate(nodes):
    n.relationships[DocumentRelationship.SOURCE] = n.get_doc_id()
```
solved this.
