### ISSUE TITLE
 query_engine.query() : KeyError: 'best_of'

### ISSUE THREAD

**Issue by reinershir** [jerryjliu/llama_index#2176]
```python
import logging
import sys
import os
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader
from IPython.display import Markdown, display
os.environ["OPENAI_API_KEY"] = 'sk-xxxx'

documents = SimpleDirectoryReader('C:\data').load_data()
index = GPTVectorStoreIndex.from_documents(documents, chunk_size_limit=1024)
# set Logging to DEBUG for more detailed outputs
query_engine = index.as_query_engine(
    streaming=True,
    similarity_top_k=1
)
response_stream = query_engine.query(
    "my prompt is ?", 
)
response_stream.print_response_stream()
```

llama_index version:0.60
python version:3.10

error message:
```
INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
NumExpr defaulting to 8 threads.
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
> [build_index_from_nodes] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 5664 tokens
> [build_index_from_nodes] Total embedding token usage: 5664 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total LLM token usage: 0 tokens
> [retrieve] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total embedding token usage: 15 tokens
> [retrieve] Total embedding token usage: 15 tokens
Traceback (most recent call last):
  File "d:\Work\project\gptIndexWork\testStream.py", line 18, in <module>
    response_stream = query_engine.query(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\query\base.py", line 20, in query
    return self._query(str_or_query_bundle)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 145, in _query
    response = self._response_synthesizer.synthesize(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\query\response_synthesis.py", line 174, in synthesize
    response_str = self._response_builder.get_response(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\response\response_builder.py", line 349, in get_response
    response = super().get_response(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\response\response_builder.py", line 172, in get_response
    response = self._give_response_single(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\response\response_builder.py", line 224, in _give_response_single
    response, formatted_prompt = self._service_context.llm_predictor.stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\llm_predictor\base.py", line 256, in stream
    raw_response_gen = self._llm.stream(formatted_prompt)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\openai.py", line 417, in stream
    params = self.prep_streaming_params(stop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\openai.py", line 425, in prep_streaming_params
    if params["best_of"] != 1:
KeyError: 'best_of'
```

**Comment by Disiok** [comment]
Can you print the langchain version you are using? My guess is that it's outdated.

**Comment by reinershir** [comment]
> Can you print the langchain version you are using? My guess is that it's outdated.

my langchain verison is : 0.0.157 ,I tried to downgrade it to version 0.0.154, but still received this error.

**Comment by CarLeeToes** [comment]
@reinershir I'm a super beginner but I was having a similar issue and got it to work by removing  streaming=True,  similarity_top_k=1 and returning response instead of response_stream.print_response_stream().

See my code below.

```
from llama_index import SimpleDirectoryReader, GPTVectorStoreIndex, LLMPredictor, ServiceContext
from llama_index import StorageContext, load_index_from_storage
from langchain import OpenAI
import gradio as gr
import sys
import os

os.environ["OPENAI_API_KEY"] = 'Your Key'
num_outputs = 512
llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="text-davinci-003", max_tokens=num_outputs))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

def construct_index(directory_path):

    docs = SimpleDirectoryReader(directory_path).load_data()

    index = GPTVectorStoreIndex.from_documents(docs, service_context=service_context)

    index.storage_context.persist()

    return index

def chatbot(input_text):

    storage_context = StorageContext.from_defaults(persist_dir="./storage")

    index = load_index_from_storage(storage_context, service_context=service_context)

    query_engine = index.as_query_engine()

    response = query_engine.query(input_text)

    return response

iface = gr.Interface(fn=chatbot,
                     inputs=gr.inputs.Textbox(lines=7, label="Enter your text"),
                     outputs="text",
                     title="Custom-trained AI Chatbot")

index = construct_index("/mnt/c/docs")
iface.launch(share=True)
```

**Comment by reinershir** [comment]
> @reinershir I'm a super beginner but I was having a similar issue and got it to work by removing streaming=True, similarity_top_k=1 and returning response instead of response_stream.print_response_stream().
> 
> See my code below.
> 
> ```
> from llama_index import SimpleDirectoryReader, GPTVectorStoreIndex, LLMPredictor, ServiceContext
> from llama_index import StorageContext, load_index_from_storage
> from langchain import OpenAI
> import gradio as gr
> import sys
> import os
> 
> os.environ["OPENAI_API_KEY"] = 'Your Key'
> num_outputs = 512
> llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="text-davinci-003", max_tokens=num_outputs))
> service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
> 
> def construct_index(directory_path):
> 
>     docs = SimpleDirectoryReader(directory_path).load_data()
> 
>     index = GPTVectorStoreIndex.from_documents(docs, service_context=service_context)
> 
>     index.storage_context.persist()
> 
>     return index
> 
> def chatbot(input_text):
> 
>     storage_context = StorageContext.from_defaults(persist_dir="./storage")
> 
>     index = load_index_from_storage(storage_context, service_context=service_context)
> 
>     query_engine = index.as_query_engine()
> 
>     response = query_engine.query(input_text)
> 
>     return response
> 
> iface = gr.Interface(fn=chatbot,
>                      inputs=gr.inputs.Textbox(lines=7, label="Enter your text"),
>                      outputs="text",
>                      title="Custom-trained AI Chatbot")
> 
> index = construct_index("/mnt/c/docs")
> iface.launch(share=True)
> ```
> 
> Python 3.10.6 llama-index 0.6.1 langchain 0.0.160 gradio 3.28.3
thank you for your reply,However, I need to use streaming=True. Finally, I removed these two lines of code and it worked properly:

langchain.llms.openai.py
in line 425
```python
#       if params["best_of"] != 1:
 #           raise ValueError("OpenAI only supports best_of == 1 for streaming")
```

**Comment by logan-markewich** [comment]
Please also checkout our native LLM openai integration

```
from llama_index import ServiceContext, set_global_service_context
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0)
ctx = ServiceContext.from_defaults(llm=llm)
set_global_service_context(ctx)
```
