### ISSUE TITLE
Getting type = vector_store_dict[TYPE_KEY] KeyError: 'type' error only on streamlit cloud

### ISSUE THREAD

**Issue by jesikalovelt696** [jerryjliu/llama_index#2226]
hello, I'm getting this error with my [app ](https://infogram.com/slot-dana-cara-daftar-slot-online-pakai-akun-dana-tanpa-menggunakan-rekening-bank-1h7j4dvrk7ynv4n)only when I run it on streamlit cloud and couldn't resolve it, what might be causing it?

Collecting usage statistics. To [deactivate](https://gitlab.idren.id/video/partido-de-hoy-olimpia-sportivo-trinidense-en-vivo-27-abril-2023-es-419-py-6673-7-5/issues/1694), set browser.gatherUsageStats to False.

2023-04-17 23:08:01.114 Uncaught app exception

Traceback (most recent call last):

File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script

exec(code, module.dict)
File "/app/chat6529/6529GPT.py", line 99, in

st.session_state.response_text, st.session_state.similarity_score = process_question(query)
File "/app/chat6529/6529GPT.py", line 54, in process_question

[index ](https://git.krews.org/bellachang/onlystars/-/issues/231)= GPTSimpleVectorIndex.load_from_disk(input_index)
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 364, in load_from_disk

return cls.[load_from_string](https://git.fairkom.net/apkfriv98/emma/-/issues/151)(file_contents, **kwargs)
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 340, in load_from_string

[return ](https://ejournal.perpusnas.go.id/files/journals/4/articles/4561/submission/original/4561-9157-1-SM.html)cls.load_from_dict(result_dict, **kwargs)
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 260, in load_from_dict

vector_store = load_vector_store_from_dict(
File "/home/[appuser](https://git.morello-project.org/harryramsey/linux/-/issues/1497)/venv/lib/python3.9/site-packages/llama_index/vector_stores/registry.py", line 52, in load_vector_store_from_dict

type = vector_store_dict[TYPE_KEY]
KeyError: 'type'

**Comment by Disiok** [comment]
Hey, we had a series of API changes recently. I think your app might have updated the version of the library. You could try pinning the version of the library or updating your code.
