### ISSUE TITLE
Error with get_embedding in Azure environment on v0.6.2

### ISSUE THREAD

**Issue by ryugonomura** [jerryjliu/llama_index#3044]
```shell
Traceback (most recent call last):
  File "/home/product/.cache/pypoetry/virtualenvs/chatbot-eVeRnpX_-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/product/.cache/pypoetry/virtualenvs/chatbot-eVeRnpX_-py3.11/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/product/.cache/pypoetry/virtualenvs/chatbot-eVeRnpX_-py3.11/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/product/.cache/pypoetry/virtualenvs/chatbot-eVeRnpX_-py3.11/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/product/.cache/pypoetry/virtualenvs/chatbot-eVeRnpX_-py3.11/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>
``` 
The cause is in llama-index/embeddings/openai.py.
I think it should be engine instead of model at "openai.Embedding.create(input=list_of_text, model=engine).data" in the function "get_embeddings, get_embeddings, get_embeddings, get_embeddings" .
It was engine until v0.6.0, but changed to model in v0.6.1 and v0.6.2.
Please confirm.

**Comment by ryugonomura** [comment]
If it is possible for me to modify the source code, I can fix it.

![image](https://user-images.githubusercontent.com/7021453/236978402-11de6065-3e38-437e-aeee-4d6316f9ebf1.png)
![image](https://user-images.githubusercontent.com/7021453/236978431-8ff17794-dd19-4df2-91ad-8e418a543639.png)
