### ISSUE TITLE
Unable to download all-MiniLM-L6-v2 while using chroma index

### ISSUE THREAD

**Issue by nithinkanil1** [jerryjliu/llama_index#3050]
Two days back deployment is working properly. When I deployed today I am getting the below mentioned error.

```
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-05-09 02:22:57.014 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 678, in get_or_create_cached_value
    return_value = _read_from_cache(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 435, in _read_from_cache
    raise e
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 420, in _read_from_cache
    return _read_from_mem_cache(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 337, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/opt/Files.py", line 153, in <module>
    index = construct_index("data/")
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 715, in wrapped_func
    return get_or_create_cached_value()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 694, in get_or_create_cached_value
    return_value = non_optional_func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Files.py", line 83, in construct_index
    chroma_collection = chroma_client.create_collection("documents")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/local.py", line 70, in create_collection
    return Collection(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 55, in __init__
    self._embedding_function = ef.SentenceTransformerEmbeddingFunction()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/utils/embedding_functions.py", line 14, in __init__
    self._model = SentenceTransformer(model_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/usr/local/lib/python3.11/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1604, in model_info
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6459ae80-6cf6b72e5d7289313c7448b5)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```
I am using Llama index 0.5.27. Kindly help

**Comment by logan-markewich** [comment]
Seems like something changed on huggingface. Chroma needs to update the model they are loading. I would file a bug with chromadb

**Comment by logan-markewich** [comment]
Actually, I saw on Twitter huggingface is having issues

**Comment by logan-markewich** [comment]
This is resolved now by huggingface
