### ISSUE TITLE
TypeError: Object of type float32 is not JSON serializable when saving index to disk

### ISSUE THREAD

**Issue by klehmann** [jerryjliu/llama_index#323]
I run the following code to build an index from a PDF in the data directory and use the hugging face embeddings (need a model with German support later):

```python
from gpt_index import GPTSimpleVectorIndex, SimpleDirectoryReader, LangchainEmbedding
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

hfemb = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
embed_model = LangchainEmbedding(hfemb)

documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex(documents, embed_model=embed_model)
index.save_to_disk('index.json')
```

This fails with the following error:

```
Traceback (most recent call last):
  File "/Users/klehmann/gpt-index/prepareindex.py", line 9, in <module>
    index.save_to_disk('index.json')
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/site-packages/gpt_index/indices/base.py", line 371, in save_to_disk
    json.dump(out_dict, f)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/klehmann/opt/anaconda3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable
```

Am I doing something wrong here?

And how would I load and use the index, would this work?

```python
index = GPTSimpleVectorIndex.load_from_disk('index.json')
response = index.query(q, mode="embedding", verbose=True, embed_model=embed_model)
```

**Comment by simonManydata** [comment]
We need to convert all the elements of the JSON into python-specific types. 
It's possible that there is a numpy `item` or a numpy float array still exists.


Looking at the codebase,


I see this code here called by any `save_to_disk` method:
```python
def serialize_to_dict(self) -> Dict[str, Any]:
        """Serialize to dict."""
        docs_dict = {}
        for doc_id, doc in self.docs.items():
            doc_dict = doc.to_dict()
            doc_dict[TYPE_KEY] = doc.get_type()
            docs_dict[doc_id] = doc_dict
        return {"docs": docs_dict}
```

Maybe `doc_id` is a numpy item, and we have a problem like this one:
https://stackoverflow.com/questions/53082708/typeerror-object-of-type-float32-is-not-json-serializable
