### ISSUE TITLE
Unable to read and use service_context  when loading an index with the load_index_from_storage function

### ISSUE THREAD

**Issue by paolosalvatori** [jerryjliu/llama_index#3429]
I created the following sample that works as follows:

1. The first time you run it, it loads a list of documents, creates and index, then stores it locally. Then it runs the query using AzureOpenAI as LLM engine
2. The second time the code loads the index from the local store and runs the query

```python
# For more information, see: 
# https://gpt-index.readthedocs.io/en/latest/getting_started/starter_example.html
# https://gist.github.com/csiebler/e287b791333011183792c08bad1dc140

# Load modules
import os
import openai
from dotenv import load_dotenv
from llama_index import (
    GPTVectorStoreIndex, 
    SimpleDirectoryReader, 
    PromptHelper, 
    LangchainEmbedding, 
    ServiceContext, 
    StorageContext, 
    load_index_from_storage)
from llama_index.storage.index_store.types import DEFAULT_PERSIST_DIR
from langchain.chat_models import AzureChatOpenAI
from langchain.embeddings import OpenAIEmbeddings
from llama_index.llm_predictor.chatgpt import ChatGPTLLMPredictor

# Load environment variables (set OPENAI_API_KEY and OPENAI_API_BASE in .env)
load_dotenv(override=True)

# Initialize LLM and Embeddings model
llm = AzureChatOpenAI(
  temperature=0.9, 
  deployment_name=os.getenv("AZURE_OPENAI_DEPLOYMENT"), 
  openai_api_key=os.getenv("AZURE_OPENAI_KEY"),
  openai_api_base=os.getenv("AZURE_OPENAI_BASE"),
  openai_api_version=os.getenv("AZURE_OPENAI_VERSION"))

llm_predictor = ChatGPTLLMPredictor(llm=llm, retry_on_throttling=False)

open_ai_embeddings = OpenAIEmbeddings(
  deployment = os.getenv("AZURE_OPENAI_ADA_DEPLOYMENT"), 
  openai_api_key = os.getenv("AZURE_OPENAI_KEY"),
  openai_api_base = os.getenv("AZURE_OPENAI_BASE"),
  openai_api_version = os.getenv("AZURE_OPENAI_VERSION"),
  openai_api_type = "azure",
  chunk_size = 1)

embeddings = LangchainEmbedding(open_ai_embeddings)

# Define prompt helper
max_input_size = 3000
num_output = 256
chunk_size_limit = 1000
max_chunk_overlap = 20
prompt_helper = PromptHelper(
  max_input_size = max_input_size, 
  num_output = num_output, 
  max_chunk_overlap = max_chunk_overlap, 
  chunk_size_limit = chunk_size_limit)

service_context = ServiceContext.from_defaults(
  llm_predictor = llm_predictor, 
  embed_model = embeddings, 
  prompt_helper = prompt_helper)

# Check if storage directory exists
persist_dir = DEFAULT_PERSIST_DIR
input_files = ['/mnt/d/Paolos/books/Building_Microservices.pdf']

if not os.path.isdir(persist_dir):
  # Load documents
  print("Loading documents:")
  for input_file in input_files:
    print(f" -  {input_file}")

  # Create the simple directory reader
  print("Creating directory reader...")
  documents = SimpleDirectoryReader(
    input_files=input_files, 
    required_exts=['.pdf']).load_data()

  # Create index
  print("Creating index...")
  index = GPTVectorStoreIndex.from_documents(
    documents = documents, 
    service_context = service_context, 
    prompt_helper = prompt_helper)

  # Save index
  print("Saving index...")
  index.storage_context.persist(persist_dir = persist_dir)
else:
  # Rebuild storage context
  storage_context = StorageContext.from_defaults(persist_dir = persist_dir)

  # Load index
  print(f"Loading index from {persist_dir}...")
  index = load_index_from_storage(storage_context)

# Query index
print("Creating query engine from index...")
query_engine = index.as_query_engine(service_context = service_context, verbose = True, engine = llm)

# Run query
query = "What is a microservice? Summarize and provide main characteristics in a bullet point list."
print("Running query...")
answer = query_engine.query(query)

# Print results
print(f"Query: {query}")
print(f"Answer: {answer}")
print(f"Sources: {answer.get_formatted_sources()}")
```
The application behaves as follows:

1. The first time the app works as expected, the index is created locally, and the query returns an answer as expected.
2. The second time the `answer = query_engine.query(query)` call throws the following exception:

```
Traceback (most recent call last):
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 105, in get_embedding
    return openai.Embedding.create(input=[text], model=engine, **kwargs)["data"][0][
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/paolos/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/paolos/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/paolos/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/paolos/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/paolos/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/paolos/python/llama_index/quickstart/storage.py", line 126, in <module>
    answer = query_engine.query(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/indices/query/base.py", line 20, in query
    return self._query(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 139, in _query
    nodes = self._retriever.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/indices/base_retriever.py", line 21, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 70, in _retrieve
    self._service_context.embed_model.get_agg_embedding_from_queries(
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 91, in get_agg_embedding_from_queries
    query_embeddings = [self.get_query_embedding(query) for query in queries]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 91, in <listcomp>
    query_embeddings = [self.get_query_embedding(query) for query in queries]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 77, in get_query_embedding
    query_embedding = self._get_query_embedding(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 230, in _get_query_embedding
    return get_embedding(
           ^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paolos/python/llama_index/quickstart/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f56be227410 state=finished raised InvalidRequestError>]
```

After some investigation and debugging, I found that the `VectorIndexRetriever` gets the `service_context` from the index. When creating the index using the `load_index_from_storage`, there is no possibility of passing the `service_context` as a parameter. The `service_context` property of the `BaseGPTIndex` has no setter, so I changed the following code:

```python
  ...
  # Load index
  print(f"Loading index from {persist_dir}...")
  index = load_index_from_storage(storage_context)
  ...
```

into: 

```python
  ...
  # Load index
  print(f"Loading index from {persist_dir}...")
  index = load_index_from_storage(storage_context)
  index._service_context = service_context
  ...
```

Now the retriever can retrieve the `service_context` from the index, and the  `answer = query_engine.query(query)` call returns an answer as expected. Maybe the `load_index_from_storage` function should be extended with the `service_context` parameter, or maybe there is another way to pass the service_context to an index loaded from storage. Thoughts?

**Comment by zioproto** [comment]
> When creating the index using the load_index_from_storage, there is no possibility of passing the service_context as a parameter.

From the docs it seems possible to do:
```
index = load_index_from_storage(service_context=service_context)
```
reference:

https://github.com/jerryjliu/llama_index/blob/7eab5dfe4b7aa1e55d6b5eef82de90a2983bd38a/docs/guides/tutorials/terms_definitions_tutorial.md?plain=1#L281

I also see `service_context` here:
https://github.com/jerryjliu/llama_index/blob/7eab5dfe4b7aa1e55d6b5eef82de90a2983bd38a/llama_index/indices/base.py#L39

Can you confirm what version of llama_index you have installed ?

**Comment by paolosalvatori** [comment]
I had the 0.6.7 version installed:

```sh
pip show llama_index
Name: llama-index
Version: 0.6.7
Summary: Interface between LLMs and your data
Home-page: https://github.com/jerryjliu/llama_index
Author: 
Author-email: 
License: MIT
Location: /home/paolos/.local/lib/python3.9/site-packages
Requires: dataclasses-json, langchain, numpy, openai, pandas, requests, tenacity, tiktoken```

I upgraded to the latest version 0.6.8:

```sh
pip install llama_index --upgrade
Name: llama-index
Version: 0.6.8
Summary: Interface between LLMs and your data
Home-page: https://github.com/jerryjliu/llama_index
Author: 
Author-email: 
License: MIT
Location: /home/paolos/.local/lib/python3.9/site-packages
Requires: dataclasses-json, langchain, numpy, openai, pandas, requests, tenacity, tiktoken
```

It looks like the latest version supports passing the `service_context`  as a kw parameter to the `load_index_from_storage `. 

I replaced 

```python
 # Load index
  print(f"Loading index from {persist_dir}...")
  index = load_index_from_storage(storage_context)
  index._service_context = service_context
```

with:

```python
# Load index
  print(f"Loading index from {persist_dir}...")
  index = load_index_from_storage(
    storage_context = storage_context, 
    service_context = service_context)
```

and now it works. Closing the issue, thanks

**Comment by harshitsinghai77** [comment]
I was running into a weird error saying resource not found:
This fixed the issue and now its working.

`openai.api_version = "2023-05-15"`

**Comment by harshitsinghai77** [comment]
Thanks. 

This is working for me as well.

```python
# Load index
print(f"Loading index from {persist_dir}...")
index = load_index_from_storage(
  storage_context = storage_context, 
  service_context = service_context
)
```
