### ISSUE TITLE
ValueError: The following `model_kwargs` are not used by the model: ['token_type_ids'] 

### ISSUE THREAD

**Issue by ZERO-A-ONE** [jerryjliu/llama_index#3501]
When I try to use the vicuna-13b-1.1 model, the following problem occurs
```
import torch
query_wrapper_prompt = SimpleInputPrompt(
    "Below is an instruction that describes a task. "
    "Write a response that appropriately completes the request.\n\n"
    "### Instruction:\n{query_str}\n\n### Response:"
)
hf_predictor = HuggingFaceLLMPredictor(
    max_input_size=2048, 
    max_new_tokens=512,
    temperature=0.25,
    do_sample=False,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="eachadea/vicuna-13b-1.1",
    model_name="eachadea/vicuna-13b-1.1",
    device_map="auto",
    tokenizer_kwargs={"max_length": 2048},
    # uncomment this if using CUDA to reduce memory usage
    model_kwargs={"torch_dtype": torch.float16}
)
prompt_helper = PromptHelper(max_input_size=2048, num_output=512, max_chunk_overlap=50)
embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2"))
service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model, prompt_helper=prompt_helper)
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist(persist_dir="./storage")
query_engine = index.as_query_engine(streaming=True, similarity_top_k=4, service_context=service_context)
```
```
Exception in thread Thread-14 (generate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1267, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1140, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['token_type_ids'] (note: typos in the generate arguments will also show up in this list)
```

**Comment by MINGYUK** [comment]
You can temporarily make it work this way:

open site-packages/transformers/generation/utils.py
this will be located in the folder wherever your python interpreter is

delete line 1139, 1140, 1141

Remember to keep those lines somewhere, for when you are done with this project and have to restore the package as it was.

**Comment by fblissjr** [comment]
> You can temporarily make it work this way:
> 
> open site-packages/transformers/generation/utils.py this will be located in the folder wherever your python interpreter is
> 
> delete line 1139, 1140, 1141
> 
> Remember to keep those lines somewhere, for when you are done with this project and have to restore the package as it was.

This worked for me. Thank you, was tearing my hair out.

**Comment by fblissjr** [comment]
This worked for me. Thank you!
