### ISSUE TITLE
GPU Llama Index under native-windows not works

### ISSUE THREAD

**Issue by AngelTs** [jerryjliu/llama_index#3755]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 4: invalid continuation byte
OSError: It looks like the config file at './models/ggml-gpt4all-j-v1.3-groovy.bin' is not a valid JSON file.
--------------------------------------------------------------------------------------------------------------------------------------
The script:
--------------------------------------------------------------------------------------------------------------------------------------
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from langchain.llms import GPT4All
from llama_index.node_parser.simple import SimpleNodeParser
from llama_index.langchain_helpers.text_splitter import TokenTextSplitter
from llama_index import (
GPTVectorStoreIndex,
LangchainEmbedding,
LLMPredictor,
ServiceContext,
StorageContext,
download_loader,
PromptHelper
)
PyMuPDFReader = download_loader("PyMuPDFReader")

from llama_index.prompts.prompts import SimpleInputPrompt

query_wrapper_prompt = SimpleInputPrompt(
"Below is an instruction that describes a task. "
"Write a response that appropriately completes the request.\n\n"
"### Instruction:\n{query_str}\n\n### Response:"
)

import torch
from llama_index.llm_predictor import HuggingFaceLLMPredictor

hf_predictor = HuggingFaceLLMPredictor(
max_input_size=2048,
max_new_tokens=256,
temperature=0.25,
do_sample=False,
query_wrapper_prompt=query_wrapper_prompt,
tokenizer_name="./models/ggml-gpt4all-j-v1.3-groovy.bin",
model_name="./models/ggml-gpt4all-j-v1.3-groovy.bin",
device_map="auto",
tokenizer_kwargs={"max_length": 2048},
model_kwargs={"torch_dtype": torch.bfloat16}
)

embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2"))

service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist(persist_dir="./source_documents")

query_engine = index.as_query_engine(streaming=True, similarity_top_k=3, service_context=service_context)
response_stream = query_engine.query("What are the main climate risks to our Oceans?")
response_stream.print_response_stream()

------------------------------------------------------------------------------------------------------------------------------------------------
Detailed errors:

 File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 658, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 745, in _dict_from_json_file
    text = reader.read()
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\privateGPT-main\embeddings2-GPU.py", line 35, in <module>
    hf_predictor = HuggingFaceLLMPredictor(
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\llm_predictor\huggingface.py", line 64, in __init__
    self.model = model or AutoModelForCausalLM.from_pretrained(
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Angel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 661, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at './models/ggml-gpt4all-j-v1.3-groovy.bin' is not a valid JSON file.

**Comment by logan-markewich** [comment]
gpt4all is not a huggingface model, and can't be used in this way 

Try loading the tokenizer and model outside of the predictor, and passing them in directly

`HuggingFaceLLMPredictor(model=model, tokenizer=tokenizer, ...)`
