### ISSUE TITLE
GPTVectorStoreIndex throwing authentication error even when not using OpenAI

### ISSUE THREAD

**Issue by santoshs** [jerryjliu/llama_index#4173]
Example code:

```python
class LocalGPT4ALL(LLM):
    """Custom LocalOPT LLM model."""

    model_name = "nomic-ai/GPT4All-13b-snoozy"
    pipeline = pipeline("text-generation", model=model_name,
                        device="cuda:0",
                        model_kwargs={"torch_dtype": torch.bfloat16})

    def _call(self, prompt: str, stop=None) -> str:
        """Generate response for the given prompt."""
        response = self.pipeline(prompt, max_new_tokens=256)
        return response[0]["generated_text"]

    @property
    def _identifying_params(self):
        """Return identifying parameters for the LLM."""
        return {"name_of_model": self.model_name}

    @property
    def _llm_type(self):
        """Return the type of LLM."""
        return "custom"


def create_index(config_data):
    os.environ['OPENAI_API_KEY'] = 'random'
    """Create and load the GPTVectorStoreIndex."""
    llm = LLMPredictor(llm=LocalGPT4ALL())
    service_context = ServiceContext.from_defaults(
        llm_predictor=llm,
        prompt_helper=initialize_prompt_helper
    )

    print("Creating index")
    documents = SimpleDirectoryReader(
        os.path.expanduser(config_data['data_dir']),
        recursive=True).load_data()
    index = GPTVectorStoreIndex.from_documents(
        documents
    )
    index.storage_context.persist(
        persist_dir=os.path.expanduser(config_data['training_data_dir']))

    return index

index = create_index(config_data)
```

Running this throws:

```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:18<00:00,  3.05s/it]
Creating index
Token indices sequence length is longer than the specified maximum sequence length for this model (1526 > 1024). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/embeddings/openai.py", line 150, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 25, in main
    create_index(config_data)
  File "/home/santosh/sample/chatbot/index.py", line 54, in create_index
    index = GPTVectorStoreIndex.from_documents(
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/base.py", line 95, in from_documents
    return cls(
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 44, in __init__
    super().__init__(
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/base.py", line 66, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 203, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 192, in _build_index_from_nodes
    self._add_nodes_to_index(index_struct, nodes)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 168, in _add_nodes_to_index
    embedding_results = self._get_node_embedding_results(nodes)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 87, in _get_node_embedding_results
    ) = self._service_context.embed_model.get_queued_text_embeddings()
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/embeddings/base.py", line 168, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/llama_index/embeddings/openai.py", line 267, in _get_text_embeddings
    return get_embeddings(
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/santosh/sample/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f7957f7a250 state=finished raised AuthenticationError>]
```

I expected that using another LLM shouldn't use OpenAI API calls.

**Comment by logan-markewich** [comment]
You did not actually use the service context:

```
index = GPTVectorStoreIndex.from_documents(
        documents,
        service_context=service_context
    )
```

You'll also want to specify an embed model though, otherwise embeddings will still be generated by OpenAI. The LLM is only for generating text

https://gpt-index.readthedocs.io/en/latest/how_to/customization/embeddings.html#custom-embeddings

Also last note, when you load the index later, make sure you pass in the service context again

`index = load_index_from_storage(StorageContext.from_defaults(persist_dir="./dir"), service_context=service_context)`

**Comment by santoshs** [comment]
@logan-markewich , thanks for the inputs. Though I did experiment with service_context I missed the embeddings part. Closing the issue.
