### ISSUE TITLE
TypeError: Instance and class checks can only be used with @runtime_checkable protocols

### ISSUE THREAD

**Issue by diogofouto** [jerryjliu/llama_index#4341]
Traceback (most recent call last):
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/main.py", line 3, in <module>
    from llama_index import (
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/keyword_table/base.py", line 18, in <module>
    from llama_index.indices.base import BaseGPTIndex
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/base.py", line 8, in <module>
    from llama_index.indices.base_retriever import BaseRetriever
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/base_retriever.py", line 5, in <module>
    from llama_index.indices.query.schema import QueryBundle, QueryType
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/query/__init__.py", line 3, in <module>
    from llama_index.indices.query.response_synthesis import ResponseSynthesizer
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/query/response_synthesis.py", line 5, in <module>
    from llama_index.indices.postprocessor.types import BaseNodePostprocessor
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/postprocessor/__init__.py", line 4, in <module>
    from llama_index.indices.postprocessor.node import (
  File "/Users/diogofouto/Documents/MEIC-A/Tese/llama_playground/llama_index/indices/postprocessor/node.py", line 236, in <module>
    class AutoPrevNextNodePostprocessor(BasePydanticNodePostprocessor):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 725, in find_validators
  File "pydantic/dataclasses.py", line 478, in make_dataclass_validator
    value = f'{default_name}()'
  File "pydantic/dataclasses.py", line 231, in pydantic.dataclasses.dataclass
    repr_running = set()
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
    _MODULE_IDENTIFIER_RE = re.compile(r'^(?:\s*(\w+)\s*\.)?\s*(\w+)')
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
    self.init = init
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 639, in pydantic.fields.ModelField._type_analysis
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ai/lib/python3.11/typing.py", line 1979, in __instancecheck__
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols

**Comment by logan-markewich** [comment]
Try updating llama index, this should be fixed

`pip install --upgrade llama-index`

**Comment by diogofouto** [comment]
It worked. Thank you.
