### ISSUE TITLE
How deeplake to load a stored file into the index

### ISSUE THREAD

**Issue by mintisan** [jerryjliu/llama_index#4348]
Here is the code for saving and loading. 

```
if not os.path.exists("./storage_deeplake"):
    print("generate storage context")
    vector_store = DeepLakeVectorStore(dataset_path="storage_deeplake", overwrite=True)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    index = GPTVectorStoreIndex.from_documents(documents, storage_context=storage_context)
    index.storage_context.persist(persist_dir="./storage_deeplake")
else:
    # load index from disk
    print("load index from disk")
    vector_store = DeepLakeVectorStore(dataset_path="storage_deeplake")
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    index = load_index_from_storage(storage_context=storage_context)

```

Saving works fine, but loading prompts the following error:

```
Loading all indices.
Traceback (most recent call last):
  File "/Users/mintisan/anaconda3/lib/python3.10/site-packages/humbug/report.py", line 540, in _hook
    self.error_report(error=exception_instance, tags=tags, publish=publish)
  File "/Users/mintisan/anaconda3/lib/python3.10/site-packages/humbug/report.py", line 274, in error_report
    traceback.format_exception(
TypeError: format_exception() got an unexpected keyword argument 'etype'

Original exception was:
Traceback (most recent call last):
  File "/Users/mintisan/Workspaces/streamlit_chatbot/llamaindex_example23_deeplake.py", line 62, in <module>
    index = load_index_from_storage(storage_context=storage_context)
  File "/Users/mintisan/anaconda3/lib/python3.10/site-packages/llama_index/indices/loading.py", line 36, in load_index_from_storage
    raise ValueError(
ValueError: No index in storage context, check if you specified the right persist_dir.

Process finished with exit code 1
```

I didn't see the generation of `vector_store.json` file, and I don't know how to do it.

![image](https://github.com/jerryjliu/llama_index/assets/9136049/970c1d07-88f8-4771-9c06-28fe50e11f4e)

I did not see this operation in the relevant documents. Could anyone please advise on how to proceed?

**Comment by logan-markewich** [comment]
Deeplake is stored locally in it's own file format (not our vector_store.json format)

To load from disk, setup the `vector_store` from the storage context 

```
dataset_path = "./dataset_path"

# construct vector store
vector_store = DeepLakeVectorStore(dataset_path=dataset_path, overwrite=False)

# setup storage context
storage_context = StorageContext.from_defaults(vector_store=vector_store, persist_dir="./storage_deeplake")
index = load_index_from_storage(storage_context)
```

**Comment by mintisan** [comment]
@logan-markewich It works, thanks...XD
