### ISSUE TITLE
Does chat engine support streaming response?

### ISSUE THREAD

**Issue by wenyongqd** [jerryjliu/llama_index#5824]
Error on request:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 327, in execute
    for data in application_iter:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/wsgi.py", line 289, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/helpers.py", line 149, in generator
    yield from gen
  File "/Users/weny/VSCode/ChatFiles/chatfiles/server.py", line 71, in generate
    for data in answer.response_gen:
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'response_gen'

I got this error when using chat engine with streaming, does it support for streaming response now?

**Comment by Disiok** [comment]
Not yet, will come soon!

**Comment by t-koyoyo** [comment]
When will this be implemented?

**Comment by logan-markewich** [comment]
Its implemented!

check out chat_engine.stream_chat or agent.stream_chat, which both give responses with a response_gen attribute
