### ISSUE TITLE
Getting Assertion error, while running query.

### ISSUE THREAD

**Issue by manaskrishnajaiswal** [jerryjliu/llama_index#5834]
storage_context = StorageContext.from_defaults(
        persist_dir=STORAGE_FILE_FOLDER_PATH)
    print(storage_context)
    # load index
    index = load_index_from_storage(storage_context)
    query_engine = index.as_query_engine()
    response = query_engine.query("What did the author do growing up?")

Traceback (most recent call last):
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\ProjectDemos\LlamaIndexUsagePattern\app.py", line 69, in <module>
    response = query_engine.query("What did the author do growing up?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 145, in _query
    response = self._response_synthesizer.synthesize(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\indices\query\response_synthesis.py", line 178, in synthesize
    response_str = self._response_builder.get_response(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\indices\response\compact_and_refine.py", line 50, in get_response
    response = super().get_response(
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\indices\response\refine.py", line 52, in get_response
    response = self._give_response_single(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\indices\response\refine.py", line 86, in _give_response_single
    ) = self._service_context.llm_predictor.predict(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\llm_predictor\base.py", line 227, in predict
    llm_prediction = self._predict(prompt, **prompt_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\llm_predictor\base.py", line 195, in _predict
    llm_prediction = retry_on_exceptions_with_backoff(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\utils.py", line 177, in retry_on_exceptions_with_backoff
    return lambda_fn()
           ^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\llm_predictor\base.py", line 196, in <lambda>
    lambda: llm_chain.predict(**full_prompt_args),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\chains\llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\chains\llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\chains\llm.py", line 79, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\base.py", line 134, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\base.py", line 191, in generate
    raise e
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\base.py", line 185, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\openai.py", line 300, in _generate
    sub_prompts = self.get_sub_prompts(params, prompts, stop)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\openai.py", line 386, in get_sub_prompts
    params["max_tokens"] = self.max_tokens_for_prompt(prompts[0])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\openai.py", line 553, in max_tokens_for_prompt
    num_tokens = self.get_num_tokens(prompt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\base_language.py", line 77, in get_num_tokens
    return len(self.get_token_ids(text))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\langchain\llms\openai.py", line 481, in get_token_ids
    enc = tiktoken.encoding_for_model(self.model_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ManasImpDOCs\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\tiktoken\core.py", line 47, in __init__
    assert len(mergeable_ranks) + len(special_tokens) == explicit_n_vocab
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by logan-markewich** [comment]
I've never seen this before actually 🤔 Seems like an issue either with tiktoken or langchain though

Maybe try with a fresh venv?
