### ISSUE TITLE
[Bug]: StreamingResponse class constructor not accepting keyword arguments

### ISSUE THREAD

**Issue by mike-j-brooks** [jerryjliu/llama_index#6195]
### Bug Description

For context, I'm using python 3.8 in a fastapi endpoint that streams to a react frontend. 

Instantiating the StreamingResponse class object works fine if you only pass in a response_gen object as a positional argument, as shown in your documentation examples. 

Python throws a TypeError if you pass the argument as keyword argument as follows: 

```
streaming_response = StreamingResponse(
        response_gen=query_engine.query(user_input).response_gen,
        extra_info={"source_url": source_url}
        )
```

Error message: 
```
streaming_response = StreamingResponse(
TypeError: __init__() got an unexpected keyword argument 'response_gen'
```
This also occurs for extra_info, if you pass response_gen as positional, and extra_info as keyword argument as follows:
```
streaming_response = StreamingResponse(
        query_engine.query(user_input).response_gen,
        extra_info={"source_url": source_url}
        )
```
Error message: 
```
TypeError: __init__() got an unexpected keyword argument 'extra_info'
```

I can't find a syntax related cause for this. The @dataclass decorator provides an automatically generated __init__() method, but it seems to not like keyword arguments. According to python docs, keyword args should be fine for dataclass constructors. 

I've also tried just passing everything as a positional argument, but there's a separate issue where source_nodes won't take a list of nodes, as the documentation would suggest. So I need to pass extra_info as a keyword argument. 

### Version

0.6.20

### Steps to Reproduce

This setup assumes an index has already been built and stored in a directory.
This is part of a fastapi endpoint, but this script-style setup should explain what I'm doing sufficiently. 

### setup LLM
llm_predictor = LLMPredictor(llm=ChatOpenAI(model_name="gpt-3.5-turbo", streaming=True))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

### rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir="/some/data/directory")

### load index
index = load_index_from_storage(storage_context, service_context=service_context)

### query the index
query_engine = index.as_query_engine(
    streaming=True,
    similarity_top_k=1
)

### use user input to retrieve nodes 
retriever = index.as_retriever()
nodes = retriever.retrieve(user_input)

### I'm using a custom method (not shown here) to get the source_url 
streaming_response = StreamingResponse(
        response_gen=query_engine.query(user_input).response_gen,
        extra_info={"source_url": source_url}
        )

### pass the response stream to frontend GUI
return streaming_response

### Relevant Logs/Tracbacks

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "pve1/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "pve1/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "pve1/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "pve1/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "pve1/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "pve1/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "pve1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "pve1/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "pve1/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "pve1/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "pve1/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/my/chatbot/app/backend/main.py", line 298, in sse_endpoint
    streaming_response = StreamingResponse(
TypeError: __init__() got an unexpected keyword argument 'response_gen'
```

**Comment by mike-j-brooks** [comment]
Okay, so you can safely disregard this entire issue. 
I was importing fastAPI's StreamingResponse and trying to use LlamaIndex's StreamingResponse. 
Didn't realize there was a naming conflict there.
