### ISSUE TITLE
[Question]: _validate_is_flat_dict check extra_info fail when using QdrantVectorStore

### ISSUE THREAD

**Issue by Myoungs** [jerryjliu/llama_index#6435]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When I build index with QdrantVectorStore, I add filename in extra_info field. The value of extra_info is dict type, which causes the _validate_is_flat_dict to check the value of the key, which will fail, because extra_info is not a string, integer, float or None. **So I wonder if it is possible to add this dict type ?**

build index codes:  

    file_meta = lambda filename: {"filename": filename}

    loader = SimpleDirectoryReader(
        dir_path, 
        recursive=True, 
        exclude_hidden=False, 
        file_metadata=file_meta,
    )

    documents =loader.load_data()

    index = GPTVectorStoreIndex.from_documents(
        documents,
        service_context=service_context,
        storage_context=storage_context,
    )

query index codes:

    query_engine = index.as_query_engine(
        service_context=service_context,
        similarity_top_k=2,
    )
    response = query_engine.query(query_str)

**Comment by Myoungs** [comment]
llama_index version: 0.6.23

Relevant Logs:


    Traceback (most recent call last):
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/Users/Myoungs/llama/web_server.py", line 92, in query
        return llama.query_index(query=query_str, llm=llm)
      File "/Users/Myoungs/llama/index.py", line 192, in query_index
        response = query_engine.query(query_str)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/indices/query/base.py", line 23, in query
        response = self._query(str_or_query_bundle)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/query_engine/retriever_query_engine.py", line 142, in _query
        nodes = self._retriever.retrieve(query_bundle)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/indices/base_retriever.py", line 21, in retrieve
        return self._retrieve(str_or_query_bundle)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
        f_return_val = f(_self, *args, **kwargs)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 84, in _retrieve
        query_result = self._vector_store.query(query, **self._kwargs)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/vector_stores/qdrant.py", line 198, in query
        node = Node(
      File "<string>", line 10, in __init__
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/data_structs/node.py", line 63, in __post_init__
        super().__post_init__()
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/schema.py", line 61, in __post_init__
        _validate_is_flat_dict(self.extra_info)
      File "/Users/Myoungs/opt/anaconda3/lib/python3.9/site-packages/llama_index/schema.py", line 24, in _validate_is_flat_dict
        raise ValueError("Value must be one of (str, int, float, None)")
    ValueError: Value must be one of (str, int, float, None)

**Comment by Myoungs** [comment]
same as https://github.com/jerryjliu/llama_index/issues/6494
