### ISSUE TITLE
[Bug]:  No module named 'langchain.chat_models' after import llama-index

### ISSUE THREAD

**Issue by camilarmoraes** [jerryjliu/llama_index#6478]
### Bug Description

Even not using langchain package diretly; only import  `from llama_index import download_loader` or any other method from llama-index; the console show this error: 
``No module named 'langchain.chat_models'; 'langchain' is not a package``

And this is my imports
`import os `
`import pandas as pd`
`from pathlib import Path`
`from llama_index import download_loader`
`from llama_index import GPTVectorStoreIndex, Document, SimpleWebPageReader`

### Version

0.6.26

### Steps to Reproduce

Only install the libs.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/camila/Documentos/Workspace//PDFSEARCH/code/algoritmo_llama.py", line 12, in <module>
    from llama_index import download_loader
  File "/home/camila/anaconda3/envs/pdf_search/lib/python3.11/site-packages/llama_index/__init__.py", line 15, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/home/camila/anaconda3/envs/pdf_search/lib/python3.11/site-packages/llama_index/embeddings/__init__.py", line 4, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/home/camila/anaconda3/envs/pdf_search/lib/python3.11/site-packages/llama_index/embeddings/langchain.py", line 6, in <module>
    from langchain.embeddings.base import Embeddings as LCEmbeddings
  File "/home/camila/Documentos/Workspace//PDFSEARCH/code/langchain.py", line 9, in <module>
    from langchain.chat_models import ChatOpenAI
ModuleNotFoundError: No module named 'langchain.chat_models'; 'langchain' is not a package
```

**Comment by logan-markewich** [comment]
@camilarmoraes how did you install llama-index? `pip install llama-index` should also install langchain 👀 Or do you have a file or folder in your directory called `langchain` that might be causing conflicts?
