### ISSUE TITLE
[Bug]: load_index_from_storage Error! openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter

### ISSUE THREAD

**Issue by imgonewild** [jerryjliu/llama_index#6489]
### Bug Description

 According to 
https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-save-the-index-for-future-use

I follow the [Optional] Save the index for future use
I created the index and store files to local folder successfully.
But when I want to load the data from local, it shows error

### Version

0.6.21.post1

### Steps to Reproduce

Code:
```
import openai, os
from llama_index import StorageContext, load_index_from_storage
from dotenv import load_dotenv
load_dotenv()

openai_api_version = "2023-03-15-preview"

openai.api_type = "azure"
openai.api_version = openai_api_version
openai.api_base = os.getenv('OPENAI_API_BASE')
openai.api_key = os.getenv("OPENAI_API_KEY")

# load index from local
storage_context = StorageContext.from_defaults(persist_dir='data_vector')
index = load_index_from_storage(storage_context) 
query_engine = index.as_query_engine()

print("Question: What should be done in case of eye contact with the product?")
response = query_engine.query(
    "What should be done in case of eye contact with the product?"
)
print(response)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\embeddings\openai.py", line 106, in get_embedding
    return openai.Embedding.create(input=[text], model=engine, **kwargs)["data"][0][
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Github Repo\LlamaIndex\text-davinci-003_load_index.py", line 19, in <module>
    response = query_engine.query(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\query_engine\retriever_query_engine.py", line 142, in _query        
    nodes = self._retriever.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\indices\base_retriever.py", line 21, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict    
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\indices\vector_store\retrievers\retriever.py", line 70, in _retrieve
    self._service_context.embed_model.get_agg_embedding_from_queries(
  File "C:\Github Repo\llama_index\llama_index\embeddings\base.py", line 91, in get_agg_embedding_from_queries     
    query_embeddings = [self.get_query_embedding(query) for query in queries]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\embeddings\base.py", line 91, in <listcomp>
    query_embeddings = [self.get_query_embedding(query) for query in queries]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\embeddings\base.py", line 77, in get_query_embedding
    query_embedding = self._get_query_embedding(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github Repo\llama_index\llama_index\embeddings\openai.py", line 235, in _get_query_embedding
    return get_embedding(
           ^^^^^^^^^^^^^^
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alan\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14d1b54d9d0 state=finished raised InvalidRequestError>]
```

**Comment by rahulaga** [comment]
You need to provide the service_context, then it works. You can see details: https://rahulaga.medium.com/using-azure-openai-for-a-custom-chatbot-2479fd9115f8

**Comment by Disiok** [comment]
Yep, you must use Azure OpenAI and provide the service context. More information here: https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html
