### ISSUE TITLE
[Bug]: The statement "openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data" is invalid.

### ISSUE THREAD

**Issue by zhugexinxin** [jerryjliu/llama_index#6546]
### Bug Description

```
llm=ChatOpenAI(
    openai_api_base='https://xxxx,
    openai_api_key='sk-xxx',
    temperature=0,
    model_name="gpt-3.5-turbo"
)
llm_predictor = LLMPredictor(llm=llm)

payload_1 = {
    'openai_api_base': 'https://xxx',
    'openai_api_key': 'sk-xxx',
    'model': 'text-embedding-ada-002',
}

payload_2 = {
    'api_base': 'https://xxx',
    'api_key': 'sk-xxx',
    'model': 'text-embedding-ada-002',
}


embed_model_1 = OpenAIEmbedding(**payload_1)
embed_model_2 = OpenAIEmbedding(**payload_2)

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model_1,
)

index = VectorStoreIndex.from_documents(
    nodes, service_context=service_context
)
```
embed_model_1 and embed_model_2 both tried and failed

llama_index/embeddings/openai.py

```
def get_embeddings(
    list_of_text: List[str], engine: Optional[str] = None, **kwargs: Any
) -> List[List[float]]:
    """Get embeddings.

    NOTE: Copied from OpenAI's embedding utils:
    https://github.com/openai/openai-python/blob/main/openai/embeddings_utils.py

    Copied here to avoid importing unnecessary dependencies
    like matplotlib, plotly, scipy, sklearn.

    """
    assert len(list_of_text) <= 2048, "The batch size should not be larger than 2048."

    # replace newlines, which can negatively affect performance.
    list_of_text = [text.replace("\n", " ") for text in list_of_text]

    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
    return [d["embedding"] for d in data]
```

data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs) is invalid.

```
openai.api_key = "sk-xxxx"
openai.api_base = "https://xxx"

response = openai.Embedding.create(
    input="The best vector database",
    model='text-embedding-ada-002',
)
```

This is correct, passing additional parameters via `kwargs` doesn't seem to achieve the desired effect.

### Version

llama-index==0.6.29

### Steps to Reproduce

```
llm=ChatOpenAI(
    openai_api_base='https://xxxx,
    openai_api_key='sk-xxx',
    temperature=0,
    model_name="gpt-3.5-turbo"
)
llm_predictor = LLMPredictor(llm=llm)

payload_1 = {
    'openai_api_base': 'https://xxx',
    'openai_api_key': 'sk-xxx',
    'model': 'text-embedding-ada-002',
}

payload_2 = {
    'api_base': 'https://xxx',
    'api_key': 'sk-xxx',
    'model': 'text-embedding-ada-002',
}


embed_model_1 = OpenAIEmbedding(**payload_1)
embed_model_2 = OpenAIEmbedding(**payload_2)

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model_1,
)

index = VectorStoreIndex.from_documents(
    nodes, service_context=service_context
)
```
embed_model_1 and embed_model_2 both tried and failed

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 150, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 130, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details, or email support@openai.com if you have any questions.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/base.py", line 97, in from_documents
    return cls(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/base.py", line 68, in __init__
    index_struct = self.build_index_from_nodes(nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 221, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 210, in _build_index_from_nodes
    self._add_nodes_to_index(index_struct, nodes)
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 186, in _add_nodes_to_index
    embedding_results = self._get_node_embedding_results(nodes)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 105, in _get_node_embedding_results
    ) = self._service_context.embed_model.get_queued_text_embeddings()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 172, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 267, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0xffffa6f79050 state=finished raised AuthenticationError>]
>>> embed_model
<llama_index.embeddings.openai.OpenAIEmbedding object at 0xffff937bee10>
```
```

**Comment by sanjaykare** [comment]
https://stackoverflow.com/questions/76425556/tenacity-retryerror-retryerrorfuture-at-0x7f89bc35eb90-state-finished-raised

**Comment by zhugexinxin** [comment]
embed_model and llm_predictor may also have different parameters

**Comment by Disiok** [comment]
Take a look at the docs for details:
* https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/root.html
* https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/root.html
