### ISSUE TITLE
[Bug]: Throws InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter again with Azure when using the RouterQueryEngine. 

### ISSUE THREAD

**Issue by buddhics** [jerryjliu/llama_index#6568]
### Bug Description

There was an issue with Azure explained here: https://github.com/jerryjliu/llama_index/issues/2129, But this has been fixed.

I get the same error when using RouterQueryEngine.

```
import os
import openai
from langchain.llms import AzureOpenAI
from langchain.embeddings import OpenAIEmbeddings
from llama_index import LangchainEmbedding
from llama_index import (
    GPTVectorStoreIndex,
    GPTEmptyIndex,
    LLMPredictor,
    PromptHelper,
    ServiceContext
)
import logging
import sys
from llama_index import download_loader
from llama_index.tools.query_engine import QueryEngineTool
from llama_index.query_engine.router_query_engine import RouterQueryEngine
from llama_index.selectors.llm_selectors import LLMSingleSelector

openai.api_type = "azure"
os.environ['OPENAI_API_VERSION'] = '2023-05-15'
openai.api_version = os.getenv('OPENAI_API_VERSION')
openai.api_base = '<basu_url>'
os.environ['OPENAI_API_KEY'] = '<key>'
openai.api_key = os.getenv("OPENAI_API_KEY")

llm = AzureOpenAI(deployment_name='<deployment_name>',model_name='text-davinci-003', model_kwargs={
    "api_key": openai.api_key,
    "api_base": openai.api_base,
    "api_type": openai.api_type,
    "api_version": openai.api_version,
})

logging.basicConfig(stream=sys.stdout, level=logging.INFO) # logging.DEBUG for more verbose output
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

llm_predictor = LLMPredictor(llm=llm)

embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        model="text-embedding-ada-002",
        deployment="<deployment_name>",
        openai_api_key= openai.api_key,
        openai_api_base=openai.api_base,
        openai_api_type=openai.api_type,
        openai_api_version=openai.api_version
    ),
    embed_batch_size=1,
)

BeautifulSoupWebReader = download_loader("BeautifulSoupWebReader")

loader = BeautifulSoupWebReader()
documents = loader.load_data(urls=['<url_1>','<url_2>'])

max_input_size = 500
num_output = 48
max_chunk_overlap = 0.2

prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embedding_llm,
    prompt_helper=prompt_helper
)

vector_index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

empty_index = GPTEmptyIndex(service_context=service_context)

vector_query_engine = vector_index.as_query_engine()
empty_query_engine = empty_index.as_query_engine(response_mode='generation')

vector_tool = QueryEngineTool.from_defaults(
    query_engine=vector_query_engine,
    description='custom domain',
)

empty_tool = QueryEngineTool.from_defaults(
    query_engine=empty_query_engine,
    description='generic',
)

query_engine = RouterQueryEngine(
    selector=LLMSingleSelector.from_defaults(),
    query_engine_tools=[
        vector_tool,
        empty_tool,
    ]
)

query_engine.query('Who is the CEO of company ABC?')
```

### Version

0.6.31

### Steps to Reproduce

1. Run the above code.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\workspace\exp\main.py", line 126, in <module>
    query_engine.query('Who is the CEO of company ABC?')
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\query_engine\router_query_engine.py", line 117, in _query
    result = self._selector.select(self._metadatas, query_bundle)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\selectors\types.py", line 76, in select
    return self._select(choices=metadatas, query=query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\selectors\llm_selectors.py", line 179, in _select
    prediction, _ = self._llm_predictor.predict(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\llm_predictor\base.py", line 241, in predict
    llm_prediction = self._predict(prompt, **prompt_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\llm_predictor\base.py", line 209, in _predict
    llm_prediction = retry_on_exceptions_with_backoff(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\utils.py", line 178, in retry_on_exceptions_with_backoff
    return lambda_fn()
           ^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\llama_index\llm_predictor\base.py", line 210, in <lambda>
    lambda: llm_chain.predict(**full_prompt_args),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\chains\llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\llms\base.py", line 140, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\llms\base.py", line 206, in generate
    raise e
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\llms\base.py", line 198, in generate
    self._generate(
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\llms\openai.py", line 326, in _generate
    response = completion_with_retry(self, prompt=_prompts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\llms\openai.py", line 106, in completion_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\langchain\llms\openai.py", line 104, in _completion_with_retry
    return llm.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XYZ\miniconda3\envs\temp\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>
```

**Comment by Disiok** [comment]
Hey @buddhics . The issue happens because the `RouterQueryEngine` is creating a default service context under the hood (which is using vanilla OpenAI)

To avoid this:
1. pass the `service_context` in like `RouterQueryEngine(..., service_context)`
2. set global service context, so every call to LLM uses the right AzureOpenAI LLM instance.
```
from llama_index import set_global_service_context
set_global_service_context(service_context)
```

**Comment by buddhics** [comment]
@Disiok this worked for me. Thanks 👍
