### ISSUE TITLE
[Question]: AttributeError: 'SQLDatabase' object has no attribute 'get_single_table_info'

### ISSUE THREAD

**Issue by byamasu-patrick** [jerryjliu/llama_index#6578]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Here is my code and the error I am getting 
```
sql_database = SQLDatabase.from_uri(db_uri)
table_node_mapping = SQLTableNodeMapping(sql_database)
all_table_names = [
    "table1",
    "table2",
    "table3"]
table_schema_objs = []
for table_name in all_table_names:
    table_schema_objs.append(SQLTableSchema(table_name=table_name))

obj_index = ObjectIndex.from_objects(
    table_schema_objs,
    table_node_mapping,
    VectorStoreIndex,
)
```
`
python main.py
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\openai\main.py", line 64, in <module>
    obj_index = ObjectIndex.from_objects(
  File "C:\Users\hp\Desktop\openai\jmf-env\lib\site-packages\llama_index\objects\base.py", line 50, in from_objects
    nodes = object_mapping.to_nodes(objects)
  File "C:\Users\hp\Desktop\openai\jmf-env\lib\site-packages\llama_index\objects\base_node_mapping.py", line 55, in to_nodes
    return [self.to_node(obj) for obj in objs]
  File "C:\Users\hp\Desktop\openai\jmf-env\lib\site-packages\llama_index\objects\base_node_mapping.py", line 55, in <listcomp>
    return [self.to_node(obj) for obj in objs]
  File "C:\Users\hp\Desktop\openai\jmf-env\lib\site-packages\llama_index\objects\table_node_mapping.py", line 46, in to_node
    f"{self._sql_database.get_single_table_info(obj.table_name)}\n"
AttributeError: 'SQLDatabase' object has no attribute 'get_single_table_info'`

Can someone help me how to resolve this error? I have tried to check my code everything seems to work perfectly fine

**Comment by byamasu-patrick** [comment]
I solved the issue after running a diagnosis of my imports, I came to realize that there was another SQLDatabase class from langchain that was overriding the first one from llamaindex. Thanks so very much @logan-markewich  for the assistance.
