### ISSUE TITLE
[Bug]: SelectionOutputParser incorrectly parsing Router Query Engine

### ISSUE THREAD

**Issue by sheresaidon** [jerryjliu/llama_index#6607]
### Bug Description

The `SelectionOutputParser` class in the llama-index library was unable to correctly parse JSON objects when used with a router query engine and a `LLMSingleSelector` with only one tool. The `_marshal_llm_to_json` method was designed to extract a JSON array from a string, but it failed when the output was a JSON object. This resulted in a `json.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` error.

### Version

The issue was observed in llama-index version v0.6.34.post1.

### Steps to Reproduce

1. Set up a router query engine with a `LLMSingleSelector` with only one tool.
2. Use the GPT-4 model for the tool.
3. Create an instance of the `SelectionOutputParser` class.
4. Call the `parse` method on this instance, passing a string that represents a JSON object (not an array). For example: `{"choice": 1, "reason": "The provided choice does not directly address the question, but it is the only choice available. The question asks for a specific task of data structuring, which is not covered in the given choice."}`
4b. also if you attempt to ask a question that does have a tool that matches it still errors

output pre marshal {"choice": 1, "reason": "The provided choice does not directly address the question, but it is the only choice available. The question asks for a specific task of data structuring, which is not covered in the given choice."}
output post marshal 
Error parsing JSON response: Expecting value: line 1 column 1 (char 0)

### Relevant Logs/Tracbacks

```shell
{
  "type": "array",
  "items": [
    {
      "type": "object",
      "properties": {
        "choice": {
          "type": "integer",
          "value": 1
        },	
        "reason": {
          "type": "string",
          "value": "The choice is relevant as it refers to the structuring of XXX data, which is the task at hand. The task involves XXX into a specific JSON format."
        }
      },
      "required": [
        "choice",
        "reason"
      ],
      "additionalProperties": false
    }
  ]
}
[2023-06-27 13:50:39 -0400] [79292] [ERROR] Error handling request /send_message
Traceback (most recent call last):
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/shere/Documents/GitHub/dev-ai-chat-template/app/app.py", line 348, in send_message
    response = get_bot_response(user_question, user_id, project_name, chat_history_file_path, project_attributes, direct_ai_chat)
  File "/Users/shere/Documents/GitHub/dev-ai-chat-template/app/llm_handler.py", line 284, in get_bot_response
    response = handle_index_type(
  File "/Users/shere/Documents/GitHub/dev-ai-chat-template/app/llm_handler.py", line 304, in handle_index_type
    response_obj = query_router_index(
  File "/Users/shere/Documents/GitHub/dev-ai-chat-template/app/llm_handler.py", line 1672, in query_router_index
    response = query_engine.query(user_question)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/llama_index/query_engine/router_query_engine.py", line 116, in _query
    result = self._selector.select(self._metadatas, query_bundle)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/llama_index/selectors/types.py", line 76, in select
    return self._select(choices=metadatas, query=query_bundle)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/llama_index/selectors/llm_selectors.py", line 103, in _select
    parse = self._prompt.output_parser.parse(prediction)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/llama_index/output_parsers/selection.py", line 71, in parse
    answers = [Answer.from_dict(json_dict) for json_dict in json_list]
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/llama_index/output_parsers/selection.py", line 71, in <listcomp>
    answers = [Answer.from_dict(json_dict) for json_dict in json_list]
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/Users/shere/virtualenvs/dev-ai-chat-template/lib/python3.10/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'choice'
```

**Comment by logan-markewich** [comment]
I think your solution makes sense, definitely feel free to raise a PR with this @sheresaidon !

Also just to note, we also have pydantic selectors that work with the new function calling API from OpenAI. These should be less prone to breaking, and I recommend trying them out :) https://gpt-index.readthedocs.io/en/latest/examples/query_engine/RouterQueryEngine.html#pydanticsingleselector
