### ISSUE TITLE
[Question]:  AuthenticationError: No API key provided

### ISSUE THREAD

**Issue by SeloSlav** [jerryjliu/llama_index#6624]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**Description:**
I encountered an issue while running the llama_index_server.py script. It seems that the OpenAI API key is not being properly utilized, resulting in an "AuthenticationError: No API key provided" exception.

**Expected Behavior:**
The script should initialize the LLMPredictor with the provided OpenAI API key and continue running without any authentication errors.

**Actual Behavior:**
The script raises an AuthenticationError with the message "No API key provided."

**Code:**

```
#  /server/llama_index_server.py

from flask import Flask, request, Response
from flask_cors import CORS
from dotenv import load_dotenv
import os
import pandas as pd
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader
from llama_index import Document
from langchain.chat_models import ChatOpenAI
from llama_index import LLMPredictor
from llama_index import ServiceContext

app = Flask(__name__)
CORS(app)

load_dotenv()

# Get the API key from the environment variable
api_key = os.getenv('OPENAI_API_KEY')

# Print the API key for verification
# print(f"API key: {api_key}")

# Loading documents from an Excel file
df = pd.read_excel('data/SupplierSample.xlsx')

# Convert DataFrame rows into documents
# Concatenate all column values into a single string for each row
documents = [Document(text=' '.join(map(str, row.values))) for _, row in df.iterrows()]

# Construct a simple vector index
index = GPTVectorStoreIndex(documents)

# LLM that supports streaming
llm_predictor = LLMPredictor(llm=ChatOpenAI(api_key=api_key, temperature=0, model_name="gpt-3.5-turbo", streaming=True))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

# Configure query engine to use streaming
query_engine = index.as_query_engine(streaming=True, similarity_top_k=1)

@app.route('/api/query', methods=['POST'])
def query():
    # Get the payload from the request
    payload = request.json
    
    # Get the question from the messages in the payload
    question = [m['content'] for m in payload['messages'] if m['role'] == 'user'][-1]
    
    # Now, query returns a StreamingResponse object
    streaming_response = query_engine.query(question)

    def response_stream():
        for text in streaming_response.response_gen:
            yield text + "\n"

    return Response(response_stream(), mimetype="text/event-stream")

if __name__ == '__main__':
    # Start the server, to run this script use "python llama_index_server.py" in terminal
    app.run(port=5000)
```

**Error Message:**

```
Traceback (most recent call last):
  File "llama_index_server.py", line 33, in <module>
    index = GPTVectorStoreIndex(documents)
  ...
  File "llama_index\embeddings\openai.py", line 150, in get_embeddings
    ...
openai.error.AuthenticationError: No API key provided.
```

**Additional Information:**

    The OPENAI_API_KEY environment variable is properly set and printed to the console before the error occurs.
    The OpenAI API key is retrieved using os.getenv('OPENAI_API_KEY') and assigned to the api_key variable.
    The LLMPredictor is initialized with the ChatOpenAI model, but the API key is not passed to the model.

**Possible Solution:**
To resolve this issue, the retrieved API key (api_key) should be passed as an argument to the ChatOpenAI model during initialization. This can be done as follows:

```
llm_predictor = LLMPredictor(llm=ChatOpenAI(api_key=api_key, temperature=0, model_name="gpt-3.5-turbo", streaming=True))
```

Please let me know if you need any further information or assistance with this issue.

**Comment by logan-markewich** [comment]
The correct kwarg is `openai_api_key=api_key`

But you are only passing it to the LLM, and not the embed model. Furthermore, you are not actually using the service context anywhere either 👀 

Here's a modified example that I think should work

```python
#  /server/llama_index_server.py

from flask import Flask, request, Response
from flask_cors import CORS
from dotenv import load_dotenv
import os
import pandas as pd
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader
from llama_index import Document
from langchain.chat_models import ChatOpenAI
from llama_index import LLMPredictor
from llama_index import ServiceContext

app = Flask(__name__)
CORS(app)

load_dotenv()

# Get the API key from the environment variable
import openai
api_key = os.getenv('OPENAI_API_KEY')
openai.api_key = api_key

# Print the API key for verification
# print(f"API key: {api_key}")

# Loading documents from an Excel file
df = pd.read_excel('data/SupplierSample.xlsx')

# Convert DataFrame rows into documents
# Concatenate all column values into a single string for each row
documents = [Document(text=' '.join(map(str, row.values))) for _, row in df.iterrows()]

# LLM that supports streaming
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

# Construct a simple vector index
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

# Configure query engine to use streaming
query_engine = index.as_query_engine(streaming=True, similarity_top_k=1)

@app.route('/api/query', methods=['POST'])
def query():
    # Get the payload from the request
    payload = request.json
    
    # Get the question from the messages in the payload
    question = [m['content'] for m in payload['messages'] if m['role'] == 'user'][-1]
    
    # Now, query returns a StreamingResponse object
    streaming_response = query_engine.query(question)

    def response_stream():
        for text in streaming_response.response_gen:
            yield text + "\n"

    return Response(response_stream(), mimetype="text/event-stream")

if __name__ == '__main__':
    # Start the server, to run this script use "python llama_index_server.py" in terminal
    app.run(port=5000)
```

**Comment by SeloSlav** [comment]
This is what I have now:

```
#  /server/llama_index_server.py

import openai
from flask import Flask, request, Response
from flask_cors import CORS
from dotenv import load_dotenv
import os
import pandas as pd
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader
from llama_index import Document
from langchain import ChatOpenAI
from llama_index import LLMPredictor
from llama_index import ServiceContext

app = Flask(__name__)
CORS(app)

load_dotenv()

# Get the API key from the environment variable
api_key = os.getenv('OPENAI_API_KEY')

# Set the OpenAI API key directly
openai.api_key = api_key

# Print the API key for verification
# print(f"API key: {api_key}")

# Loading documents from an Excel file
df = pd.read_excel('data/SupplierSample.xlsx')

# Convert DataFrame rows into documents
# Concatenate all column values into a single string for each row
documents = [Document(text=' '.join(map(str, row.values))) for _, row in df.iterrows()]

# LLM that supports streaming
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

# Construct a simple vector index
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

# Configure query engine to use streaming
query_engine = index.as_query_engine(streaming=True, similarity_top_k=1)

@app.route('/api/query', methods=['POST'])
def query():
    # Get the payload from the request
    payload = request.json
    
    # Get the question from the messages in the payload
    question = [m['content'] for m in payload['messages'] if m['role'] == 'user'][-1]
    
    # Now, query returns a StreamingResponse object
    streaming_response = query_engine.query(question)

    def response_stream():
        for text in streaming_response.response_gen:
            yield text + "\n"

    return Response(response_stream(), mimetype="text/event-stream")

if __name__ == '__main__':
    # Start the server, to run this script use "python llama_index_server.py" in terminal
    # Invoke-WebRequest -Uri http://localhost:5000/api/query -Method POST -ContentType "application/json" -Body '{"messages":[{"role": "user", "content": "What is OpenAI?"}]}'

    app.run(port=5000)
```

But it appears streaming isn't supported or it's broken?

```
[2023-06-29 18:45:05,764] ERROR in app: Exception on /api/query [POST]
Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, 
**kwargs)))
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\marti\Documents\Web Projects\latam-link\server\llama_index_server.py", line 56, in query
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\query_engine\retriever_query_engine.py", line 149, in _query
    response = self._response_synthesizer.synthesize(    
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\indices\query\response_synthesis.py", line 178, in synthesize        
    response_str = self._response_builder.get_response(  
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\indices\response\compact_and_refine.py", line 48, in get_response    
    response = super().get_response(
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict     
    f_return_val = f(_self, *args, **kwargs)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\indices\response\refine.py", line 52, in get_response
    response = self._give_response_single(
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\indices\response\refine.py", line 94, in _give_response_single       
    response, formatted_prompt = self._service_context.llm_predictor.stream(
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\llama_index\llm_predictor\base.py", line 284, in stream
    raise ValueError("LLM must support streaming and set 
streaming=True.")
ValueError: LLM must support streaming and set streaming=True.
127.0.0.1 - - [29/Jun/2023 18:45:05] "POST /api/query HTTP/1.1" 500 -
```

**Comment by logan-markewich** [comment]
Going to close this for now. Feel free to reopen or reach out on discord!
