### ISSUE TITLE
[Bug]: sqlite3.Warning: You can only execute one statement at a time in NLSQLTableQueryEngine

### ISSUE THREAD

**Issue by talvola** [jerryjliu/llama_index#6781]
### Bug Description

Using the example from https://gpt-index.readthedocs.io/en/latest/guides/tutorials/sql_guide.html - with an in-memory SQLite database, one ends up with:

`>>> response = query_engine.query(query_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/llama_index/indices/struct_store/sql_query.py", line 267, in _query
    raw_response_str, metadata = self._sql_database.run_sql(sql_query_str)
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/llama_index/langchain_helpers/sql_wrapper.py", line 82, in run_sql
    cursor = connection.execute(text(command))
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2342, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/talvola/llama_testing/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.Warning: You can only execute one statement at a time.`

I'm not sure if the prompt needs changing, but turning on logging - the SQL query generated is:

`INFO:llama_index.indices.struct_store.sql_query:> Table desc str: Table 'city_stats' has columns: city_name (VARCHAR(16)), population (INTEGER), country (VARCHAR(16)) and foreign keys: .
DEBUG:llama_index.indices.struct_store.sql_query:> Predicted SQL query: SELECT city_name, population
FROM city_stats
ORDER BY population DESC
LIMIT 1;
SQLResult:
city_name | population
Tokyo     | 37000000
Answer: Tokyo has the highest population.`

with OpenAI (in my case) already filling in part of the answer.

I fixed this by stripping out the rest of the SQL statement:

`$ git diff llama_index/indices/struct_store/sql_query.py
diff --git a/llama_index/indices/struct_store/sql_query.py b/llama_index/indices/struct_store/sql_query.py
index 5dd5b6cf..27254eed 100644
--- a/llama_index/indices/struct_store/sql_query.py
+++ b/llama_index/indices/struct_store/sql_query.py
@@ -237,7 +237,7 @@ class BaseSQLTableQueryEngine(BaseQueryEngine):

     def _parse_response_to_sql(self, response: str) -> str:
         """Parse response to SQL."""
-        result_response = response.strip()
+        result_response = response.strip().split(";")[0] + ";"

but could be better to change the prompt?  

separately - the sample code on the Guide didn't work for me without doing an explicit commit like connection.commit() after the execute for the insert statements.

### Version

0.7.2

### Steps to Reproduce

simply run the steps from https://gpt-index.readthedocs.io/en/latest/guides/tutorials/sql_guide.html as in the description

**Comment by logan-markewich** [comment]
This should be fixed in the latest versions of llama-index! Can you give it a try again?

Relevant PR: https://github.com/jerryjliu/llama_index/pull/6782

**Comment by talvola** [comment]
yes - using the latest codebase with that fix addresses the issue
