### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by sameerbabu** [jerryjliu/llama_index#6910]
### Bug Description

We did the following steps 

1. We have a text file, created embeddings using "api.openai.com"
2. We have created an index in pinecone 
3. We have used pinecone upsert to create vectors in pinecone

**We have done all the above steps offline, outside llama**

Now, 
We have created a py file to query a question using llama with below content

```
pinecone.init(api_key=api_key, environment=environment)  
pinecone_index = pinecone.Index("testindex")
print(pinecone_index.describe_index_stats())

vector_store = PineconeVectorStore(pinecone_index=pinecone_index)
index = VectorStoreIndex.from_vector_store(vector_store=vector_store)

#query_engine = index.as_query_engine()
#Init query engine like this if you want to use filters
query_engine = index.as_query_engine(
    similarity_top_k=3,
    vector_store_query_mode="default"
)
res = query_engine.query("movie inception?")

```
We got the below error on running above mentioned llama-app.py code

```
Traceback (most recent call last):
  File "/vscode-workspace/chatgpt/llama-app.py", line 36, in <module>
    res = query_engine.query("who directed movie inception?")
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/query_engine/retriever_query_engine.py", line 147, in _query
    nodes = self.retrieve(query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/query_engine/retriever_query_engine.py", line 107, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/indices/base_retriever.py", line 21, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 85, in _retrieve
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/vector_stores/pinecone.py", line 298, in query
    metadata, node_info, relationships = legacy_metadata_dict_to_node(
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/vector_stores/utils.py", line 72, in legacy_metadata_dict_to_node
    metadata = metadata.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

```

On enabling debugging logs, we got the following

```
DEBUG:llama_index.vector_stores.pinecone:Failed to parse Node metadata, fallback to legacy logic.
Failed to parse Node metadata, fallback to legacy logic.
```

### Version

0.7.8

### Steps to Reproduce

Pinecone index has been updated offline using openai embeddings API and pinecone upsert API

Trying to do a basic search via llama. 
We have followed the steps mentioned in the below documentation URL.

https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/vector_store_guide.html#connect-to-external-vector-stores-with-existing-embeddings

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/vscode-workspace/chatgpt/llama-app.py", line 36, in <module>
    res = query_engine.query("who directed movie inception?")
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/query_engine/retriever_query_engine.py", line 147, in _query
    nodes = self.retrieve(query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/query_engine/retriever_query_engine.py", line 107, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/indices/base_retriever.py", line 21, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 85, in _retrieve
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/vector_stores/pinecone.py", line 298, in query
    metadata, node_info, relationships = legacy_metadata_dict_to_node(
  File "/vscode-workspace/chatgpt/venv/lib/python3.9/site-packages/llama_index/vector_stores/utils.py", line 72, in legacy_metadata_dict_to_node
    metadata = metadata.copy()
AttributeError: 'NoneType' object has no attribute 'copy'



On enabling debugging logs, we got the following

DEBUG:llama_index.vector_stores.pinecone:Failed to parse Node metadata, fallback to legacy logic.
Failed to parse Node metadata, fallback to legacy logic.
```

**Comment by logan-markewich** [comment]
Yea this is a small bug in our legacy code path, fixing now!

https://github.com/jerryjliu/llama_index/pull/6912
