### ISSUE TITLE
[Question]: RemoteReader not working while reading PDF data from URL

### ISSUE THREAD

**Issue by qaixerabbas** [jerryjliu/llama_index#6953]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to read PDF data using RemoteReader from llama_hub but stuck into some JSONDecoreError. I am not sure what is causing the error here is my code below  (copied directly from [this link](https://llamahub.ai/l/remote)):

```
from llama_index import download_loader
RemoteReader = download_loader("RemoteReader")
url = "URL to a pdf"
loader = RemoteReader()
documents = loader.load_data(url=url)
```
Not sure it is a bug or some other issue but I am not able to run this code.

The code is throwing following error:
```
Traceback (most recent call last):
  File "D:\1. SDSol Projects\Between Sessions\AI Progress Notes Generator\worksheet analysis\experiments\another_test.py", line 3, in <module>
    RemoteReader = download_loader("RemoteReader")
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\llama_index\readers\download.py", line 133, in download_loader
    library = json.loads(library_raw_content)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
```

**Comment by tyre** [comment]
Could you go into the `llama_index` package and print out the `library_raw_content`?

I've tried the code you linked with the URL `https://writing.colostate.edu/guides/documents/resume/functionalsample.pdf` and it works.

Alternatively, you can get this directly from the llamahub pip package (`pip install llama-hub`):

```python
from llama_hub.remote.base import RemoteReader

url = "https://writing.colostate.edu/guides/documents/resume/functionalsample.pdf"
loader = RemoteReader()
documents = loader.load_data(url=url)
print(documents)
```
