### ISSUE TITLE
[Question]: When customize the LLM, using VectorStoreIndex, it reports error 

### ISSUE THREAD

**Issue by Danny-C-Auditore** [jerryjliu/llama_index#6977]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Traceback (most recent call last):
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 165, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yaoyunzhang897/llama-index/test.py", line 82, in <module>
    index = VectorStoreIndex.from_documents(documents, service_context=service_context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/base.py", line 102, in from_documents
    return cls(
           ^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 46, in __init__
    super().__init__(
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 241, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 229, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 201, in _add_nodes_to_index
    embedding_results = self._get_node_embedding_results(nodes, show_progress)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 111, in _get_node_embedding_results
    ) = self._service_context.embed_model.get_queued_text_embeddings(show_progress)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home//.local/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 180, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 285, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaoyunzhang897/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fd5edf13d10 state=finished raised AuthenticationError>]

it reports "openai.error.AuthenticationError: No API key provided."
But the question is that I didn't try to use the Openai model,  why would I need the API key?

**Comment by aetherwu** [comment]
index = VectorStoreIndex.from_documents(documents, service_context=service_context)

Would call OpenAI embedding by default.
How did you config your customized llm connection?

**Comment by Danny-C-Auditore** [comment]
![image](https://github.com/jerryjliu/llama_index/assets/66711049/8c8898b9-c95e-423b-a478-76620ff92fe3)
![image](https://github.com/jerryjliu/llama_index/assets/66711049/b2647060-1142-4333-b45a-87717f77d60c)
I did the same as the example code in the doc. I don't know what went wrong.

**Comment by Danny-C-Auditore** [comment]
the latter is  "Using a HuggingFace LLM"

**Comment by aetherwu** [comment]
Hi, I assume that it still use OpenAI embadding to decode/encode your documents and query text.
The HuggingFace LLM you use here, looks like it provide final question and materials for it to get answer from LLM.
You might want to wait and see auther's feedback from repo.

**Comment by Danny-C-Auditore** [comment]
yes, the hf model just runs once for only one question and then the program stops. I'm trying to use the chat_engine for consistent conversation. And thanks for your help, I appreciate that.

**Comment by logan-markewich** [comment]
@Danny-C-Auditore yea there's two models in llama-index -- the LLM and the embedding model

You'll need to set **both** in order to to avoid openai.

You can learn more about setting up custom embeddings here:
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#embedding-model-integrations

**Comment by Danny-C-Auditore** [comment]
![image](https://github.com/jerryjliu/llama_index/assets/66711049/f5bae1fb-adf9-4538-a9c4-cacf96c4557b)
Another error emerges when running "**service_context = ServiceContext.from_defaults(
        llm=llm, context_window=int(window), num_output=int(output),embed_model=("local:"+ model_name)
    )**"

The probelm is, the service_context seems not to have an attibute **tokenizer**, so I can't add the **[pad] token**, how can I solve this? 

Since the model was running on a server and I can upload the tokenizer_config.json(the connection to the server will crash.....), using "(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})" is the only way for me. 

Thanks a lot !!!

**Comment by logan-markewich** [comment]
Hmm, sounds like to me you just need to implement your own custom embedding model class.

Normally it's expected that the tokenization is handled by the model class

There's an example here of a completely custom embedding class that sub classes the base class
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#custom-embedding-model
