### ISSUE TITLE
AssertionError: The batch size should not be larger than 2048

### ISSUE THREAD

**Issue by kenn** [jerryjliu/llama_index#698]
I'm getting `AssertionError` in `get_embeddings` — `list_of_text` seems to be larger than 2048.

```py
Traceback (most recent call last):
  File "/proj/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 142, in get_embeddings
    assert len(list_of_text) <= 2048, "The batch size should not be larger than 2048."
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: The batch size should not be larger than 2048.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
  File "/proj/main.py", line 91, in build_index
    index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/vector_indices.py", line 84, in __init__
    super().__init__(
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 63, in __init__
    super().__init__(
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 279, in build_index_from_documents
    return self._build_index_from_documents(documents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 206, in _build_index_from_documents
    self._add_document_to_index(index_struct, d)
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 182, in _add_document_to_index
    embedding_results = self._get_node_embedding_results(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 102, in _get_node_embedding_results
    result_ids, result_embeddings = self._embed_model.get_queued_text_embeddings()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 151, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 260, in _get_text_embeddings
    embeddings = get_embeddings(texts, engine=engine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x133445050 state=finished raised AssertionError>]
```

**Comment by Disiok** [comment]
Could you give a bit more details to help use reproduce this issue?

From my understanding of the code, we use `DEFAULT_EMBED_BATCH_SIZE=10`, which should not hit in the assertion above.

**Comment by logan-markewich** [comment]
This should not be possible anymore. Please re-open if it becomes an issue again!
