### ISSUE TITLE
[Bug]:  SubQuestionQueryEngine error

### ISSUE THREAD

**Issue by DhavalWI** [jerryjliu/llama_index#6993]
### Bug Description

While using SubQuestionQueryEngine for multiple index query im getting some un explainable error please take a look.

### Version

0.7.11 post1

### Steps to Reproduce

used GPTVectorStoreIndex to generate indexes for 2 documents. Then used SubQuestionQueryEngine for query.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/output_parsers/utils.py", line 19, in parse_json_markdown
    json_obj = json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 5 column 1 (char 112)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/output_parsers/utils.py", line 26, in parse_json_markdown
    json_obj = yaml.safe_load(json_string)
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '`' that cannot start any token
  in "<unicode string>", line 5, column 1:
    
    ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dhaval/llama_index/backup/multii.py", line 95, in <module>
    response = s_engine.query("What is the date of agreement for abbisko?")
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/query_engine/sub_question_query_engine.py", line 123, in _query
    sub_questions = self._question_gen.generate(self._metadatas, query_bundle)
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/question_gen/llm_generators.py", line 63, in generate
    parse = self._prompt.output_parser.parse(prediction)
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/question_gen/output_parser.py", line 11, in parse
    json_dict = parse_json_markdown(output)
  File "/home/dhaval/llama_index/lam/lib/python3.10/site-packages/llama_index/output_parsers/utils.py", line 28, in parse_json_markdown
    raise OutputParserException(
llama_index.output_parsers.base.OutputParserException: Got invalid JSON object. Error: Extra data: line 5 column 1 (char 112) while scanning for the next token
found character '`' that cannot start any token
  in "<unicode string>", line 5, column 1:
    ```
    ^
```

**Comment by Disiok** [comment]
I think it's due to the LLM outputting a response with bad format (e.g. missing a backtick).

The function calling models are much more reliable. You can do so by setting the LLM to use `gpt-3.5-turbo` or `gpt-3.5-turbo"`

**Comment by DhavalWI** [comment]
> I think it's due to the LLM outputting a response with bad format (e.g. missing a backtick).
> 
> The function calling models are much more reliable. You can do so by setting the LLM to use OpenAI `gpt-3.5-turbo` or `gpt-3.5-turbo"`

i'm using the open source llm by databricks. dollyv2-12b
