### ISSUE TITLE
[Question]: Trying to understand llama_index better

### ISSUE THREAD

**Issue by kylemassimilian** [jerryjliu/llama_index#7108]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to create a Q&A app over a large set of documents. I'm currently using the s3 loader to retrieve my docs and load them in (is this pulling all the documents on to my local machine?). Currently, I cannot do this with close to 1GB of files without having my working code run extremely slow (5-10 minutes before timeout). My desired amount of file data is 10GB. Then, I am using Chroma to store these documents in a collection and build my index to then query. 

1. Is there a different method I can use to speed up this loading of documents? Perhaps with the Chroma reader? If I used the Chroma reader, would I do all of the embedding ahead of time, and would I only have to do this once?
2. I think I'm embedding every time I run this but please let me know if I'm wrong. Is there a way to prevent this from happening/only do it once? I would like to embed my files one time, then add my vectordb using a Lambda function each time files are added to the bucket.
3. Is the advantage of running Chroma in the cloud that I can store my embeddings in a way such that anyone can use them later for querying? If so, I do not understand how to implement this in code.

This code works, but only for a very small amount of data. I'm trying to create something others could use 

```
`import os, chromadb, openai
from dotenv import load_dotenv
from llama_index import VectorStoreIndex, ServiceContext
from llama_index.vector_stores import ChromaVectorStore
from llama_index.storage.storage_context import StorageContext
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index.embeddings import LangchainEmbedding
from llama_index import download_loader
load_dotenv()
openai.organization = os.getenv('OPENAI_ORGANIZATION')
openai.api_key = os.getenv('OPENAI_API_KEY')

# Create AWS S3 Reader using download_loader class
S3Reader = download_loader("S3Reader")

# Validate credentials
bucket = os.getenv('BUCKET_NAME')
#key = os.getenv('KEY_NAME')
access_id = os.getenv('ACCESS_ID')
secret_key = os.getenv('SECRET_KEY')

# Load data from S3 w/ credentials
loader = S3Reader(bucket=bucket, prefix='', aws_access_id=access_id, aws_access_secret=secret_key)
    # Load data into document format
try:
        print("Loading data...")
        documents = loader.load_data()
        print("Data loaded")
except Exception as e:
        print("Error loading data:", e)

def index_chroma():
    
   # Create remote Chroma connection
   remote_db = chromadb.HttpClient(host="", port=8000)

   collection_name = "Pavise-small-768-3"
   collections = [col.name for col in remote_db.list_collections()]
   print(collections)
   
   embed_model = LangchainEmbedding(
            HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
         )
   chroma_collection = remote_db.get_or_create_collection(collection_name)
   
   vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
   storage_context = StorageContext.from_defaults(vector_store=vector_store)
   service_context = ServiceContext.from_defaults(embed_model=embed_model)
   
   index = VectorStoreIndex.from_documents(
               documents, storage_context=storage_context, service_context=service_context, embed_model=embed_model)
   return index
  
def query_chroma(index):
    chat_engine = index.as_chat_engine()

    response = chat_engine.chat("Tell me about Pavise")
    return response

test = index_chroma()
response = query_chroma(test)
print(response)`
```

I tried to create a check to see if the collection was new:

```
`import os, chromadb, openai, sys
from dotenv import load_dotenv
from llama_index import VectorStoreIndex, ServiceContext, load_index_from_storage
from llama_index.vector_stores import ChromaVectorStore
from llama_index.storage.storage_context import StorageContext
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index.embeddings import LangchainEmbedding
from llama_index import download_loader
load_dotenv()
openai.organization = os.getenv('OPENAI_ORGANIZATION')
openai.api_key = os.getenv('OPENAI_API_KEY')

# Create AWS S3 Reader using download_loader class
S3Reader = download_loader("S3Reader")

# Validate credentials
bucket = os.getenv('BUCKET_NAME')
#key = os.getenv('KEY_NAME')
access_id = os.getenv('ACCESS_ID')
secret_key = os.getenv('SECRET_KEY')

# Load data from S3 w/ credentials
loader = S3Reader(bucket=bucket, prefix='', aws_access_id=access_id, aws_access_secret=secret_key)
    # Load data into document format
try:
        print("Loading data...")
        documents = loader.load_data()
        print("Data loaded")
except Exception as e:
        print("Error loading data:", e)

def index_chroma():
    
   # Create remote Chroma connection
   remote_db = chromadb.HttpClient(host="", port=8000)

   collection_name = "Pavise-small-768-2"
   collections = [col.name for col in remote_db.list_collections()]
   print(collections)
   
   embed_model = LangchainEmbedding(
            HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
         )

   # Check if collection exists and either retrieve or create it accordingly
   if collection_name in collections:
         print(f"Collection '{collection_name}' already exists, getting existing collection...")
         chroma_collection = remote_db.get_collection(collection_name)
         vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
         index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
         #storage_context=StorageContext.from_defaults(vector_store=chroma_collection['embeddings'])
         #index = load_index_from_storage(storage_context)
         return index
         
   else:
         print("Creating new collection...")
         chroma_collection = remote_db.create_collection(collection_name)
         
         # Create Chroma Vector Store
         vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
         # Create the storage context and service context for the new collections
         storage_context = StorageContext.from_defaults(vector_store=vector_store)
         service_context = ServiceContext.from_defaults(embed_model=embed_model)

         # Create index from documents for the new collection
         index = VectorStoreIndex.from_documents(
               documents, storage_context=storage_context, service_context=service_context, embed_model=embed_model)
         return index
   
   

def query_chroma(index, query):
    chat_engine = index.as_chat_engine()

    response = chat_engine.chat("Tell me about Pavise")
    return response


test = index_chroma()
response = query_chroma(test)
print(response)
```

but I received this error:

```
root@38200e892614:/chroma# python chromatest4.py
Loading data...
Data loaded
['Pavise-small', 'Pavise-small-768-3', 'IX-test', 'IX-Alpha-new-2', 'Pavise-small-768', 'IX-Alpha-new', 'Pavise-small-768-2', 'IX-Alpha-investments']
Collection 'Pavise-small-768-2' already exists, getting existing collection...
Traceback (most recent call last):
  File "/chroma/chromatest4.py", line 81, in <module>
    response = query_chroma(test)
  File "/chroma/chromatest4.py", line 76, in query_chroma
    response = chat_engine.chat("Tell me about Pavise")
  File "/usr/local/lib/python3.10/site-packages/llama_index/agent/react/base.py", line 156, in chat
    reasoning_steps, is_done = self._process_actions(output=chat_response)
  File "/usr/local/lib/python3.10/site-packages/llama_index/agent/react/base.py", line 117, in _process_actions
    tool_output = tool(**reasoning_step.action_input)
  File "/usr/local/lib/python3.10/site-packages/llama_index/tools/query_engine.py", line 54, in __call__
    response = self._query_engine.query(query_str)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 157, in _query  
    nodes = self.retrieve(query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 115, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/base_retriever.py", line 22, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 75, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 151, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/llama_index/vector_stores/chroma.py", line 130, in query
    results = self._collection.query(
  File "/chroma/chromadb/api/models/Collection.py", line 223, in query
    return self._client._query(
  File "/chroma/chromadb/api/fastapi.py", line 340, in _query
    raise_chroma_error(resp)
  File "/chroma/chromadb/api/fastapi.py", line 405, in raise_chroma_error
    raise chroma_error
chromadb.errors.InvalidDimensionException: Embedding dimension 1536 does not match collection dimensionality 768
```

**Comment by logan-markewich** [comment]
@kylemassimilian check out the example here for saving/loading a chromadb instance https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/ChromaIndexDemo.html#chroma

**Comment by kylemassimilian** [comment]
@logan-markewich Thank you. That page is where I got most of the code for what you see in the thread. I guess what I'm trying to understand is how to store and retrieve a vector db on and from the cloud. Is this done via collections? It is confusing to me that I have to create a ChromaVectorStore and embed this collection even when it already exists. Seems to defeat the purpose of running a Chroma instance via AWS: [https://docs.trychroma.com/deployment](url)

**Comment by logan-markewich** [comment]
@kylemassimilian so once you create the index in chroma, you should be able to just setup the collection object to connect back to the existing index, and use `index = VectorStoreIndex.from_vector_store(vector_store)`, and the embeddings won't be re-created

**Comment by logan-markewich** [comment]
The example in the notebook is a little more complicated than it needs to be, really this will work

```
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
index = VectorStoreIndex.from_vector_store(
    vector_store=vector_store,
    service_context=service_context,
)
```
