### ISSUE TITLE
[Question]: Embedding dimension 1536 does not match collection dimensionality 768

### ISSUE THREAD

**Issue by kylemassimilian** [jerryjliu/llama_index#7110]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to fix the case in which a Chroma collection already exists. Does anyone know how I can prevent a reembedding attempt and just build an index?

```
`Loading data...
Data loaded
['Pavise-small', 'Pavise-small-768-3', 'IX-test', 'IX-Alpha-new-2', 'Pavise-small-768', 'IX-Alpha-new', 'Pavise-small-768-2', 'IX-Alpha-investments']
Collection 'Pavise-small-768-2' already exists, getting existing collection...
Traceback (most recent call last):
  File "/chroma/chromatest4.py", line 80, in <module>
    response = query_chroma(test)
  File "/chroma/chromatest4.py", line 75, in query_chroma
    response = chat_engine.chat("Tell me about Pavise")
  File "/usr/local/lib/python3.10/site-packages/llama_index/agent/react/base.py", line 156, in chat
    reasoning_steps, is_done = self._process_actions(output=chat_response)
  File "/usr/local/lib/python3.10/site-packages/llama_index/agent/react/base.py", line 117, in _process_actions
    tool_output = tool(**reasoning_step.action_input)
  File "/usr/local/lib/python3.10/site-packages/llama_index/tools/query_engine.py", line 54, in __call__
    response = self._query_engine.query(query_str)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 157, in _query
    nodes = self.retrieve(query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 115, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/base_retriever.py", line 22, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 75, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 151, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/llama_index/vector_stores/chroma.py", line 130, in query
    results = self._collection.query(
  File "/chroma/chromadb/api/models/Collection.py", line 223, in query
    return self._client._query(
  File "/chroma/chromadb/api/fastapi.py", line 340, in _query
    raise_chroma_error(resp)
  File "/chroma/chromadb/api/fastapi.py", line 405, in raise_chroma_error
    raise chroma_error
chromadb.errors.InvalidDimensionException: Embedding dimension 1536 does not match collection dimensionality 768`
```

```
import os, chromadb, openai, sys
from dotenv import load_dotenv
from llama_index import VectorStoreIndex, ServiceContext, load_index_from_storage
from llama_index.vector_stores import ChromaVectorStore
from llama_index.storage.storage_context import StorageContext
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index.embeddings import LangchainEmbedding
from llama_index import download_loader
load_dotenv()
openai.organization = os.getenv('OPENAI_ORGANIZATION')
openai.api_key = os.getenv('OPENAI_API_KEY')

# Create AWS S3 Reader using download_loader class
S3Reader = download_loader("S3Reader")

# Validate credentials
bucket = os.getenv('BUCKET_NAME')
#key = os.getenv('KEY_NAME')
access_id = os.getenv('ACCESS_ID')
secret_key = os.getenv('SECRET_KEY')

# Load data from S3 w/ credentials
loader = S3Reader(bucket=bucket, prefix='', aws_access_id=access_id, aws_access_secret=secret_key)
    # Load data into document format
try:
        print("Loading data...")
        documents = loader.load_data()
        print("Data loaded")
except Exception as e:
        print("Error loading data:", e)

def index_chroma():
    
   # Create remote Chroma connection
   remote_db = chromadb.HttpClient(host="", port=8000)

   collection_name = "Pavise-small-768-2"
   collections = [col.name for col in remote_db.list_collections()]
   print(collections)
   
   embed_model = LangchainEmbedding(
            HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
         )

   # Check if collection exists and either retrieve or create it accordingly
   if collection_name in collections:
         print(f"Collection '{collection_name}' already exists, getting existing collection...")
         chroma_collection = remote_db.get_collection(collection_name)
         vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
         index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
         #storage_context=StorageContext.from_defaults(vector_store=chroma_collection['embeddings'])
         #index = load_index_from_storage(storage_context)
         return index
         
   else:
         print("Creating new collection...")
         chroma_collection = remote_db.create_collection(collection_name)
         
         # Create Chroma Vector Store
         vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
         # Create the storage context and service context for the new collections
         storage_context = StorageContext.from_defaults(vector_store=vector_store)
         service_context = ServiceContext.from_defaults(embed_model=embed_model)

         # Create index from documents for the new collection
         index = VectorStoreIndex.from_documents(
               documents, storage_context=storage_context, service_context=service_context, embed_model=embed_model)
         return index
   
   

def query_chroma(index):
    chat_engine = index.as_chat_engine()

    response = chat_engine.chat("Tell me about Pavise")
    return response


test = index_chroma()
response = query_chroma(test)
print(response)

```

**Comment by kylemassimilian** [comment]
similar to issue #777, I specified the embedding model when building the index in the event that the collection is new. This does not help me in the case that the collection already exists. I want to be able to reference a the embeddings in my already existing collection to build on index from that, not re-embed each time.

**Comment by logan-markewich** [comment]
@kylemassimilian The vector store needs to follow a pretty specific format in order for llama-index to use it. This is because llama-index stores json-ified versions of our nodes in the vectordb.

Currently, it looks like our chroma implementation does not support existing collections created outside of llama-index. This could be added in a PR though (we did something similar for pinecone), you just need a way to tell llama-index where to find a few key fields (text, id, etc.)
