### ISSUE TITLE
[Question]: llama_index supports NebulaGraph, what can I change to make it support neo4j?

### ISSUE THREAD

**Issue by xinkeyb** [jerryjliu/llama_index#7137]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

llama_index supports NebulaGraph, what can I change to make it support neo4j?
（zh：llama_index支持NebulaGraph，我该怎么改才能让它支持neo4j呢）

**Comment by logan-markewich** [comment]
We just added neo4j support! Like actually merged it a few minutes ago haha

Should show up in the next release, or you can install from source. Example here:
https://github.com/jerryjliu/llama_index/blob/main/docs/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo.ipynb

**Comment by xinkeyb** [comment]
amazing，thank u very much！

**Comment by xinkeyb** [comment]
> We just added neo4j support! Like actually merged it a few minutes ago haha
> 
> Should show up in the next release, or you can install from source. Example here: https://github.com/jerryjliu/llama_index/blob/main/docs/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo.ipynb

### I referred to the link you provided，and use local LLM and remote Neo4j, but the following error occurred：
Traceback (most recent call last):
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/llama_index/response_synthesizers/tree_summarize.py", line 149, in get_response
    return self.get_response(
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/llama_index/response_synthesizers/tree_summarize.py", line 149, in get_response
    return self.get_response(
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/llama_index/response_synthesizers/tree_summarize.py", line 149, in get_response
    return self.get_response(
  [Previous line repeated 977 more times]
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/llama_index/response_synthesizers/tree_summarize.py", line 100, in get_response
    text_qa_template = self._text_qa_template.partial_format(query_str=query_str)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/llama_index/prompts/base.py", line 112, in partial_format
    raise e
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/llama_index/prompts/base.py", line 107, in partial_format
    copy_obj = deepcopy(self)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/copy.py", line 138, in deepcopy
    y = memo.get(d, _nil)
RecursionError: maximum recursion depth exceeded in comparison
Exception ignored in: <function Driver.__del__ at 0x7fe150bd0940>
Traceback (most recent call last):
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/neo4j/_sync/driver.py", line 485, in __del__
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.8/site-packages/neo4j/_meta.py", line 226, in unclosed_resource_warn
TypeError: 'NoneType' object is not callable



### This is my code：
username = "neo4j"
password = "Shb9Sy5q_j_5hw_ZybKyfr6SPQsqqdB7Z-Xza4-pgQ"
url = "neo4j+s://46de362d.databases.neo4j.io:7687"
database = "neo4j"

documents = SimpleDirectoryReader(
    "./data"
).load_data()

graph_store = Neo4jGraphStore(
    username=username,
    password=password,
    url=url,
    database=database,
)

storage_context = StorageContext.from_defaults(graph_store=graph_store)

index = KnowledgeGraphIndex.from_documents(
    documents,
    storage_context=storage_context,
    max_triplets_per_chunk=2,
    service_context=service_context,
)
query_engine = index.as_query_engine(include_text=False, response_mode="tree_summarize")
response = query_engine.query("Tell me more about Tom Hanks")
display(Markdown(f"<b>{response}</b>"))

#### I did not use Neo4j provided in the example, because I can't connect to it. But instead used Neo4j's Aura online database .

**Comment by xinkeyb** [comment]
### This is the whole code：
```
# For OpenAI

import os


import logging
import sys
from llama_index.llms import CustomLLM, CompletionResponse, LLMMetadata
from llama_index.llms.base import llm_chat_callback, llm_completion_callback
from llama_index import ServiceContext

import torch
from transformers import pipeline
from typing import Optional, List, Mapping, Any

from llama_index import (
    ServiceContext,
    SimpleDirectoryReader,
    LangchainEmbedding,
    ListIndex
)

from llama_index.llms.base import CompletionResponseGen
from llama_index.callbacks import CallbackManager



# set context window size
context_window = 2048
# set number of output tokens
num_output = 256

# store the pipeline/model outisde of the LLM class to avoid memory issues
model_name = "/data/zhaoxinke/PromptCBLUE-main/src/bloom-7b1"
pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype": torch.bfloat16})


class OurLLM(CustomLLM):

    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=context_window,
            num_output=num_output,
            model_name=model_name
        )

    @llm_completion_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        prompt_length = len(prompt)
        response = pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

        # only return newly generated tokens
        text = response[prompt_length:]
        return CompletionResponse(text=text)

    @llm_completion_callback()
    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        raise NotImplementedError()

callback_manager = CallbackManager([])
# define our LLM
llm = OurLLM(callback_manager)

service_context = ServiceContext.from_defaults(
    llm=llm,
    context_window=context_window,
    num_output=num_output,
    embed_model="local"
)




from llama_index import (
    KnowledgeGraphIndex,
    LLMPredictor,
    ServiceContext,
    SimpleDirectoryReader,
)
from llama_index.storage.storage_context import StorageContext
from llama_index.graph_stores import Neo4jGraphStore

from llama_index.llms import OpenAI
from IPython.display import Markdown, display


username = "neo4j"
password = "Shb9Sy5q_j_5hw_ZybKyfr6SPQsqqdB7Z-Xza4-pgQ"
url = "neo4j+s://46de362d.databases.neo4j.io:7687"
database = "neo4j"



documents = SimpleDirectoryReader(
    "./data"
).load_data()

graph_store = Neo4jGraphStore(
    username=username,
    password=password,
    url=url,
    database=database,
)

storage_context = StorageContext.from_defaults(graph_store=graph_store)

# NOTE: can take a while!
index = KnowledgeGraphIndex.from_documents(
    documents,
    storage_context=storage_context,
    max_triplets_per_chunk=2,
    service_context=service_context,
)

query_engine = index.as_query_engine(include_text=False, response_mode="tree_summarize")

response = query_engine.query("Tell me more about Tom Hanks")

display(Markdown(f"<b>{response}</b>"))

```
