### ISSUE TITLE
[Bug]: ChatMemoryBuffer unpicklable since 0.7.18

### ISSUE THREAD

**Issue by SlapDrone** [jerryjliu/llama_index#7169]
### Bug Description

Hey folks,

Since 0.7.18 the `ChatMemoryBuffer` class is unpicklable. Looks like there was some refactoring/tweaks in this release. Pretty sure it's the tokenizer object. See e.g. https://github.com/huggingface/datasets/issues/5536.

(FAO @logan-markewich)

### Version

0.7.18

### Steps to Reproduce

```python
from copy import deepcopy

from llama_index.memory import ChatMemoryBuffer

buffer = ChatMemoryBuffer(token_limit=5)
deepcopy(buffer)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 172, in deepcopy
      y = _reconstruct(x, memo, *rv)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 271, in _reconstruct
      state = deepcopy(state, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 146, in deepcopy
      y = copier(x, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 231, in _deepcopy_dict
      y[deepcopy(key, memo)] = deepcopy(value, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 146, in deepcopy
      y = copier(x, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 231, in _deepcopy_dict
      y[deepcopy(key, memo)] = deepcopy(value, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 172, in deepcopy
      y = _reconstruct(x, memo, *rv)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 265, in _reconstruct
      y = func(*args)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 264, in <genexpr>
      args = (deepcopy(arg, memo) for arg in args)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 146, in deepcopy
      y = copier(x, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 238, in _deepcopy_method
      return type(x)(x.__func__, deepcopy(x.__self__, memo))
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 172, in deepcopy
      y = _reconstruct(x, memo, *rv)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 271, in _reconstruct
      state = deepcopy(state, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 146, in deepcopy
      y = copier(x, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 231, in _deepcopy_dict
      y[deepcopy(key, memo)] = deepcopy(value, memo)
    File "/home/slapdrone/.pyenv/versions/3.10.8/lib/python3.10/copy.py", line 161, in deepcopy
      rv = reductor(4)
  TypeError: cannot pickle 'builtins.CoreBPE' object
```

**Comment by logan-markewich** [comment]
Tbh, I think we would prefer users the json-ify the object, rather than pickle it? The changes that caused this allowed the json/dict operations to work properly in pydantic 😅

The end goal would be doing something like agent.persist() or something, similar to indexes?

Although I'm surprised pickling worked before. All I did was change the tokenizer to a default factory 🤔

**Comment by SlapDrone** [comment]
So I just used a straight deepcopy as a minimal working example to open this issue, wasn't planning to use it to serialise the ChatMemory (although I agree there that `json` would make a lot more sense for that!).

Problem is that a fair few libraries implicitly pickle things, and it's not always clear when it's happening until something breaks. In this case, I've been using [gin](https://github.com/google/gin-config) to configure my llama index agents/pipelines for a while, and this broke it :disappointed:. 

Btw, I just tried just getting rid of the default factory and the issue persisted for some reason (constructing it with `from_defaults`).

**Comment by logan-markewich** [comment]
That's fair! I can take a look in a bit and get pickling work again 👍

**Comment by logan-markewich** [comment]
Update: Tried reverting to pre 0.7.18 code, but it's actually still not able to pickle 🤔 Trying some other approaches

**Comment by logan-markewich** [comment]
As long as the tokenizer is an attribute of the memory, this seems to always happen :sadge:

**Comment by SlapDrone** [comment]
> Update: Tried reverting to pre 0.7.18 code, but it's actually still not able to pickle thinking Are you sure it worked earlier?

Very weird. It definitely works for me on my pinned 0.7.17. Looking into this now.
