### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wcw1996119** [jerryjliu/llama_index#7208]
### Bug Description

when i try to import anything from llama_index, it causes the same error:
Traceback (most recent call last):
  File "C:\Users\aiwus\wus-webdemo\app.py", line 4, in <module>
    from llama_index import GPTVectorStoreIndex
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\llama_index\__init__.py", line 11, in <module>
    from llama_index.data_structs.struct_type import IndexStructType
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\llama_index\data_structs\__init__.py", line 3, in <module>
    from llama_index.data_structs.data_structs_v2 import (
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\llama_index\data_structs\data_structs_v2.py", line 12, in <module>
    from dataclasses_json import DataClassJsonMixin
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\dataclasses_json\__init__.py", line 2, in <module>
    from dataclasses_json.api import (DataClassJsonMixin,
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\dataclasses_json\api.py", line 7, in <module>
    from dataclasses_json.core import (Json, _ExtendedEncoder, _asdict,
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\dataclasses_json\core.py", line 17, in <module>
    from typing_inspect import is_union_type  # type: ignore
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\typing_inspect.py", line 17, in <module>
    from typing_extensions import _TypedDictMeta as _TypedDictMeta_TE
  File "C:\Users\aiwus\wus-webdemo\venv\lib\site-packages\typing_extensions.py", line 1127, in <module>
    def TypeAlias(self, parameters):
TypeError: __init__() missing 1 required positional argument: 'doc'

### Version

0.5.16

### Steps to Reproduce

import

**Comment by logan-markewich** [comment]
Are you using a venv? Maybe create a fresh venv just to be sure

```
python -m venv venv
source venv/bin/activate
pip install llama-index==0.5.16
```
