### ISSUE TITLE
help for how to use llama_index on chroma.[Question]: 

### ISSUE THREAD

**Issue by pythonmanGo** [jerryjliu/llama_index#7225]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using llama_index on chroma  ,but there is still  a  question.

    According to the example：[Chroma - LlamaIndex 🦙 0.7.22 (gpt-index.readthedocs.io)](https://gpt-index.readthedocs.io/en/stable/examples/vector_stores/ChromaIndexDemo.html#basic-example-using-the-docker-container)

    Normally, we delete or modify a document based on our query, not based on the ID of a document, because the document id is an internal field that we cannot know in advance.     But is now based on the code:
'''
    query_engine = index.as_query_engine()
    response = query_engine.query("What did the author do growing up?")
'''

    Now according to the sample code, we can only get the text result of the query, but cannot get the corresponding id of the text, so we cannot delete or update the query result.     How to query the corresponding id of the result text based on prompt, so as to delete or modify the operation later?

`db = chromadb.PersistentClient(path="./chroma_db")
        chroma_collection = db.get_or_create_collection("datartchromaDB")
        vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)

        index = VectorStoreIndex.from_vector_store(
            vector_store=vector_store,
            storage_context=storage_context,
            service_context=service_context,
        )
       query_engine = index.as_query_engine()

        response = query_engine.query(prompt)

        doc_to_update = chroma_collection.get(limit=1)
###how to  get the id  of the result ( response = query_engine.query(prompt)) ,which i had prompt from  gpt3.5
        print(doc_to_update)
            # delete the last document
        print("count before", chroma_collection.count())
        chroma_collection.delete(ids=[doc_to_update["ids"][0]])
        print("count after", chroma_collection.count())`

**Comment by pythonmanGo** [comment]
`llm=ChatOpenAI(temperature=0,  model_name="gpt-3.5-turbo-0301", max_tokens=1024)



llm_predictor = LLMPredictor(llm=llm)


service_context = ServiceContext.from_defaults(



  #prompt_helper=prompt_helper,


  llm_predictor=llm_predictor  ,


  node_parser=node_parser,


        chunk_size=1024)


set_global_service_context(service_context)


db = chromadb. PersistentClient(path="./chroma_db")


        chroma_collection = db.get_or_create_collection("datartchromaDB")


        vector_store = ChromaVectorStore(chroma_collection=chroma_collection)


        storage_context = StorageContext.from_defaults(vector_store=vector_store)


        index = VectorStoreIndex.from_vector_store(


            vector_store=vector_store,


            storage_context=storage_context,


            service_context=service_context,


        )



        # Query Data from the persisted index


        query_engine = index.as_query_engine()


        response = query_engine.query(prompt)


        Acflag="Delete"


        doc_to_update_id=response.source_nodes[0].node.ref_doc_id


        if         Acflag=="Delete":


            print("begin delse")


            #doc_to_update = chroma_collection.get(limit=1)


            print(doc_to_update)


            # delete the last document


            print("count before", chroma_collection.count())


            chroma_collection.delete(ids=[doc_to_update_id])


            print("count after", chroma_collection.count())


        elif  Acflag=="Update":


                doc_to_update = chroma_collection.get(ids=[doc_to_update_id])



                #new_content = 'new record'



                doc_to_update["documents"][0] = new_content



                chroma_collection.update(


                    ids=[doc_to_update_id],


                    documents=doc_to_update["documents"]


                )


`




thanks a lot    when i  update  i got a error :


Traceback (most recent call last):


  File "C:\java\javaproject\langchainServerXLDB\langchainServerNEWXLDB.py", line 496, in MixSerchGPT


    chroma_collection.update(


  File "C:\java\anaconda3\envs\langchainChatbot\lib\site-packages\chromadb\api\models\Collection.py", line 276, in update


    self._client._update(self.id, ids, embeddings, metadatas, documents)


  File "C:\java\anaconda3\envs\langchainChatbot\lib\site-packages\chromadb\api\segment.py", line 267, in _update


    self._validate_embedding_record(coll, r)


  File "C:\java\anaconda3\envs\langchainChatbot\lib\site-packages\chromadb\api\segment.py", line 522, in _validate_embedding_record


    self._validate_dimension(collection, len(record["embedding"]), update=True)


  File "C:\java\anaconda3\envs\langchainChatbot\lib\site-packages\chromadb\api\segment.py", line 537, in _validate_dimension


    raise InvalidDimensionException(


chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "C:\java\javaproject\langchainServerXLDB\langchainServerNEWXLDB.py", line 928, in <module>





seems  when i  update the record  the  embedding   method use default method ,but when  i  add  the record to the  chromadb the method is gpt-3.5-turbo-0301 how can i resolve  it. maybe  we  need  a method to  update chromadb  by   llama_index. 

By the way  how  add a record to  chromadb quikly  ,my data  is like :

data = {
    'ids': ['250bb797-bb3d-4824-8d69-e62125645951'],
    'embeddings': None,
    'metadatas': [
        {
            'doc_id': '702ecd1e-9305-4a71-a5fa-7d43f366c72d',
            'document_id': '702ecd1e-9305-4a71-a5fa-7d43f366c72d',
            'node_info': '{"start": 3428, "end": 4047, "_node_type": "1"}',
            'ref_doc_id': '702ecd1e-9305-4a71-a5fa-7d43f366c72d',
            'relationships': '{"1": "702ecd1e-9305-4a71-a5fa-7d43f366c72d", "2": "be8ceeda-b69b-48c6-b12a-cc5859dcd488", "3": "9e96142a-0c6d-4138-80f3-544972b38053"}'
        }
    ],
    'documents': [
        'recorder1........',
        'recorder2........',
        'recorder3........'
    ]
}

**Comment by pythonmanGo** [comment]
> 
thanks a lot when i update i got a error :


seems when i update the record the embedding method use default method ,but when i add the record to the chromadb the method is gpt-3.5-turbo-0301 how can i resolve it. maybe we need a method to update chromadb by llama_index.

By the way how add a record to chromadb quikly ,my data is like :

**Comment by pythonmanGo** [comment]
@dosu-bot  if i need  embedding whith chatgpt3.5  ,please modyfied  the  code  for me
