### ISSUE TITLE
[Bug]: Since 0.8.2 using a different LLM of OpenAI requests the ApiKey

### ISSUE THREAD

**Issue by semoal** [jerryjliu/llama_index#7276]
### Bug Description

```bash
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/llama_index/embeddings/openai.py", line 166, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
  File "/Users/sergiomoreno/miniconda3/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

The above exception was the direct cause of the following exception:
```

### Version

0.8.2

### Steps to Reproduce

```python
 llm = Replicate(
        model=SELECTED_MODEL,
        temperature=0.1,
        # override max tokens since it's interpreted
        # as context window instead of max tokens
        context_window=CONTEXT_WINDOW,
        # override completion representation for llama 2
        completion_to_prompt=custom_completion_to_prompt,
        # if using llama 2 for data agents, also override the message representation
        messages_to_prompt=messages_to_prompt,
    )
    embed_model = LangchainEmbedding(
        HuggingFaceBgeEmbeddings(
            model_name="BAAI/bge-large-en",
            encode_kwargs={"normalize_embeddings": True},
            cache_folder=".tmp",
        ),
        embed_batch_size=15,
    )
    vector_client = weaviate.Client(VECTOR_DB_URL)
    service_context = ServiceContext.from_defaults(
        context_window=CONTEXT_WINDOW,
        llm=llm,
        chunk_size=512,
        embed_model=embed_model,
    )
    set_global_service_context(service_context)
```

**Comment by semoal** [comment]
With 0.8.1 works fine 👍

**Comment by logan-markewich** [comment]
Can you try updating to 0.8.2.post1?

**Comment by semoal** [comment]
> Can you try updating to 0.8.2.post1?

Tried and same problem

**Comment by logan-markewich** [comment]
Weird that it's not falling back to our local defaults?

In any case, managed to replicate the issue. The global service context was not resolving the embed model properly. Should be working once I merge the PR

**Comment by logan-markewich** [comment]
@fcakyon looks like 0.8.4

I'm not sure what version you are currently on, but I'm sure the changes aren't that bad? 

If they are, you can optionally monkey-patch your installed version with the fix in the PR
