### ISSUE TITLE
[Bug]: SentenceSplitter hangs in an infinite loop

### ISSUE THREAD

**Issue by sanand0** [jerryjliu/llama_index#7287]
### Bug Description

When running the default `VectorStoreIndex.from_documents(docs)` on a specific document (shown below), `StentenceSplitter.split_text()` goes into an infinite loop.

### Version

0.8.3

### Steps to Reproduce

Run

```shell
export OPENAI_API_KEY=...
python test.py
```

... where `test.py` contains:

```python
from llama_index import VectorStoreIndex, SimpleDirectoryReader

docs = SimpleDirectoryReader('.', filename_as_id=True).load_data()
index = VectorStoreIndex.from_documents(docs)
```

... and the same folder has a `sample.md` that contains this **EXACT TEXT**:

```md
## March 2020

L&D Metric (Org) - 2.92%

| Training Name                                                                                                          | Catergory       | Duration (hrs) | Invitees | Attendance | Target Training Hours | Actual Training Hours | Adoption % |
| ---------------------------------------------------------------------------------------------------------------------- | --------------- | -------------- | -------- | ---------- | --------------------- | --------------------- | ---------- |
| [Overview of Data Analytics](https://gramener.tekstac.com/course/view.php?id=178)                                      | Technical       | 1              | 23       | 10         | 23                    | 10                    | 43.5       |
| [Sales & Learning Best Practices - Introduction to OTT Platforms](https://gramener.tekstac.com/course/view.php?id=180) | Technical       | 0.5            | 16       | 12         | 8                     | 6                     | 75         |
| Leading Through OKRs                                                                                                   | Lifeskill       | 1              | 1        | 1          | 1                     | 1                     | 100        |
| COVID: Lockdown Awareness Session                                                                                      | Lifeskill       | 2              | 1        | 1          | 2                     | 2                     | 100        |
| Navgati Interview                                                                                                      | Lifeskill       | 2              | 6        | 6          | 12                    | 12                    | 100        |
| [leadership Summit](https://gramener.tekstac.com/course/view.php?id=177)                                               | Leadership      | 18             | 42       | 42         | 756                   | 756                   | 100        |
| AWS - AI/ML - Online Conference                                                                                        | Project Related | 15             | 2        | 2          | 30                    | 30                    | 100        |
```

This hangs in an infinite loop.

### Relevant Logs/Tracbacks

```shell
$ python test.py 
Traceback (most recent call last):
  File "C:\code\cto\learn.gramener.com\killme\test.py", line 4, in <module>
    index = VectorStoreIndex.from_documents(docs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\llama_index\indices\base.py", line 98, in from_documents
    nodes = service_context.node_parser.get_nodes_from_documents(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\llama_index\node_parser\simple.py", line 89, in get_nodes_from_documents
    nodes = get_nodes_from_document(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\llama_index\node_parser\node_utils.py", line 90, in get_nodes_from_document
    text_splits = text_splitter.split_text_metadata_aware(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\llama_index\text_splitter\sentence_splitter.py", line 70, in split_text_metadata_aware
    return self._split_text(text, chunk_size=effective_chunk_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\llama_index\text_splitter\sentence_splitter.py", line 88, in _split_text
    chunks = self._merge(splits, chunk_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\llama_index\text_splitter\sentence_splitter.py", line 138, in _merge
    cur_len = len(self.tokenizer(cur_token.text))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\.conda\envs\gramex\Lib\site-packages\tiktoken\core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by Disiok** [comment]
Should have a PR up for the fix soon!
