### ISSUE TITLE
[Bug]: Must provide an 'engine' or 'deployment_id' parameter to create a class

### ISSUE THREAD

**Issue by rafaeldpaula** [jerryjliu/llama_index#7312]
### Bug Description

Traceback (most recent call last):
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\embeddings\openai.py", line 166, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Desenv\llamaindex\main.py", line 70, in <module>
    main()
  File "C:\Desenv\llamaindex\main.py", line 51, in main
    index = GPTVectorStoreIndex(documents, llm_predictor=llm_predictor, embed_model=embedding_llm, prompt_helper=prompt_helper)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\indices\vector_store\base.py", line 46, in __init__
    super().__init__(
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\indices\base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\indices\vector_store\base.py", line 241, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\indices\vector_store\base.py", line 229, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\indices\vector_store\base.py", line 201, in _add_nodes_to_index
    embedding_results = self._get_node_embedding_results(nodes, show_progress)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\indices\vector_store\base.py", line 111, in _get_node_embedding_results
    ) = self._service_context.embed_model.get_queued_text_embeddings(show_progress)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\embeddings\base.py", line 214, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\llama_index\embeddings\openai.py", line 302, in _get_text_embeddings
    return get_embeddings(
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Desenv\llamaindex\rafa\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1d350bb5ed0 state=finished raised InvalidRequestError>]

### Version

0.8.4

### Steps to Reproduce

I'm trying to create a embedding with llama index using Azure.

```
    llm_predictor = LLMPredictor(llm=AzureOpenAI(engine='gpt-35-turbo-16k'))
    embedding_llm = LangchainEmbedding(OpenAIEmbeddings(deployment="text-embedding-ada-002", model_kwargs={
        "api_key": '<foobar>',
        "api_base": '<foobar>',
        "api_type": "azure",
        "api_version": '<foobar>'
    }))

    prompt_helper = PromptHelper(context_window=3000, num_output=500, chunk_overlap_ratio=0.1, chunk_size_limit=1000)

    reader_pdf = ReaderPDF()
    documents = reader_pdf.read()

    index = GPTVectorStoreIndex(documents, llm_predictor=llm_predictor, embed_model=embedding_llm, prompt_helper=prompt_helper)
```

**Comment by logan-markewich** [comment]
@rafaeldpaula Your code is a little outdated -- you aren't using the service context

Check out our azure guide here
https://gpt-index.readthedocs.io/en/stable/examples/customization/llms/AzureOpenAI.html

**Comment by rafaeldpaula** [comment]
Ok, now that's worked for me. Thank you!

**Comment by rafaeldpaula** [comment]
Ok, now that's worked for me. Thank you!
