### ISSUE TITLE
[Bug]: json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 48690 (char 48689)

### ISSUE THREAD

**Issue by AntonOfTheWoods** [jerryjliu/llama_index#7338]
### Bug Description

I tried to continue after successfully installing and testing yesterday. Now there is an unmanaged exception.

### Version

v0.8.5.post2

### Steps to Reproduce

Follow the installation steps: https://gpt-index.readthedocs.io/en/latest/getting_started/installation.html and https://gpt-index.readthedocs.io/en/latest/examples/llm/llama_2_llama_cpp.html (with CUDA).

This works, then I rebooted, and now it doesn't. A new venv changes nothing, and it is still broken.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/anton/dev/tmp/litest/test.py", line 1, in <module>
    from llama_index.llms import LlamaCPP
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/__init__.py", line 20, in <module>
    from llama_index.indices.keyword_table import (
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/indices/keyword_table/base.py", line 18, in <module>
    from llama_index.indices.base import BaseIndex
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/chat_engine/__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/chat_engine/condense_question.py", line 5, in <module>
    from llama_index.chat_engine.types import (
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/chat_engine/types.py", line 11, in <module>
    from llama_index.memory import BaseMemory
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/memory/__init__.py", line 1, in <module>
    from llama_index.memory.chat_memory_buffer import ChatMemoryBuffer
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 13, in <module>
    class ChatMemoryBuffer(BaseMemory):
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 19, in ChatMemoryBuffer
    default_factory=cast(Callable[[], Any], GlobalsHelper().tokenizer),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/llama_index/utils.py", line 50, in tokenizer
    enc = tiktoken.get_encoding("gpt2")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/dev/tmp/litest/.venv/lib/python3.11/site-packages/tiktoken/load.py", line 92, in data_gym_to_mergeable_bpe_ranks
    encoder_json = json.loads(read_file_cached(encoder_json_file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/.asdf/installs/python/3.11.4/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/.asdf/installs/python/3.11.4/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anton/.asdf/installs/python/3.11.4/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 48690 (char 48689)
```

**Comment by AntonOfTheWoods** [comment]
Hmm... Another reboot seems to have solved the issue...
