### ISSUE TITLE
[Bug]: Wrong parameter supplied with AzureOpenAIEmbeddings (naming inconsistency)

### ISSUE THREAD

**Issue by stickM4N** [jerryjliu/llama_index#7345]
### Bug Description

```python
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>
```

When creating an OpenAIEmbedding instance I pass the registered parameter 'deployment' as I should because I use AzureOpenAI. The problem is the when the EngineAPIResource wants to create the request it looks for the 'deployment_id' parameter instead.

If I use 'deplyment_id' it works but shows the warning:
```python
UserWarning: WARNING! engine is not default parameter.
                    engine was transferred to model_kwargs.
                    Please confirm that engine is what you intended.
```

I Think this inconsistency should be fixed. Istarted to notice it when I updated from version 0.7.5 to 0.8.5.post2

### Version

0.8.5.post2

### Steps to Reproduce

When using AzureOpenAI:
```python
index = GPTVectorStoreIndex.from_documents(
    documents=documents,
    storage_context=...,
    service_context=...
)
```

**Comment by stickM4N** [comment]
```python
folder...\venv\Scripts\python.exe folder...\main.py 
folder...\venv\lib\site-packages\langchain\embeddings\openai.py:214: UserWarning: WARNING! deployment_name is not default parameter.
                    deployment_name was transferred to model_kwargs.
                    Please confirm that deployment_name is what you intended.
  warnings.warn(
Traceback (most recent call last):
  File "folder...\main.py", line 17, in <module>
    print(a.query('3', 'context model'))
  File "folder...\custom_index\index.py", line 81, in query
    return self.__indexes[name].as_query_engine().query(prompt).response \
  File "folder...\venv\lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "folder...\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 169, in _query
    nodes = self.retrieve(query_bundle)
  File "folder...\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 117, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "folder...\venv\lib\site-packages\llama_index\indices\base_retriever.py", line 22, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "folder...\venv\lib\site-packages\llama_index\indices\vector_store\retrievers\retriever.py", line 71, in _retrieve
    self._service_context.embed_model.get_agg_embedding_from_queries(
  File "folder...\venv\lib\site-packages\llama_index\embeddings\base.py", line 118, in get_agg_embedding_from_queries
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "folder...\venv\lib\site-packages\llama_index\embeddings\base.py", line 118, in <listcomp>
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "folder...\venv\lib\site-packages\llama_index\embeddings\base.py", line 89, in get_query_embedding
    query_embedding = self._get_query_embedding(query)
  File "folder...\venv\lib\site-packages\llama_index\embeddings\langchain.py", line 47, in _get_query_embedding
    return self._langchain_embedding.embed_query(query)
  File "folder...\venv\lib\site-packages\langchain\embeddings\openai.py", line 506, in embed_query
    return self.embed_documents([text])[0]
  File "folder...\venv\lib\site-packages\langchain\embeddings\openai.py", line 478, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=self.deployment)
  File "folder...\venv\lib\site-packages\langchain\embeddings\openai.py", line 364, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "folder...\venv\lib\site-packages\langchain\embeddings\openai.py", line 107, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "folder...\venv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "folder...\venv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "folder...\venv\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\jcgal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\jcgal\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "folder...\venv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "folder...\venv\lib\site-packages\langchain\embeddings\openai.py", line 104, in _embed_with_retry
    response = embeddings.client.create(**kwargs)
  File "folder...\venv\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "folder...\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "folder...\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

Process finished with exit code 1

```

It does not solve the issue. I already read the docs and used it as I read it, but it does not work! It only does by providing 'engine' or 'deployment_id' parameter

**Comment by JSv4** [comment]
@dosu-bot, your suggestion doesn't work for me either. See the stack trace that @stickM4N posted above. Other thoughts?

**Comment by stickM4N** [comment]
That was an automated response using a bot that searches the docs, not a developers answered. We need to wait for it.

**Comment by JSv4** [comment]
Yes, thanks @stickM4N. I was seeing if it's possible to prompt the bot for a response as suggested by this in its initial answer:

 `If you want to continue the conversation, start your reply with @dosu-bot.` 

Anyway, in my case, this issue is caused by forgetting to define a specific service_context when reloading my index from disk. 

E.g This causes your error:

```
    index = load_index_from_storage(
        storage_context=storage_context,
    )
```

This does not:

```
    index = load_index_from_storage(
        storage_context=storage_context,
        service_context=service_context
    )
```

In my case this is due to the default service context not being what I want when loading my index.
