### ISSUE TITLE
[Bug]: llama index throws FileExistsError when trying to create a VectorStoreIndex in multithreaded environment

### ISSUE THREAD

**Issue by amarkules1** [jerryjliu/llama_index#7362]
### Bug Description

I'm working on a REST service using gunicorn, and noticed the service sometimes fails during startup when I set the number of workers > 1. In the application I'm creating a llama_index.VectorStoreIndex on startup, which is where the failure is happening. Based on the logs, I've traced the issue to this `os.makedirs()` call: https://github.com/jerryjliu/llama_index/blob/main/llama_index/utils.py#L275

It seems that there's a concurrency issue, where multiple workers check if the directory exists at the same time, see that it does not, and try to create the directory. Fix should be as simple as adding an `exist_ok=True` param to the `os.makedirs()` call

### Version

0.8.5.post2

### Steps to Reproduce

1. create a simple flask app that calls `VectorStoreIndex.from_vector_store()` during startup
2. run the app using gunicorn with multiple workers (seems to happen pretty frequently with 4+)
3. observe output

I've been running into this issue with [this project](https://github.com/amarkules1/bill-the-ai), I can try to put something simpler together to reproduce if needed.

### Relevant Logs/Tracbacks

```shell
[2023-08-22 02:37:51 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2023-08-22 02:37:51 +0000] [1] [INFO] Listening at: https://0.0.0.0:443 (1)
[2023-08-22 02:37:51 +0000] [1] [INFO] Using worker: sync
[2023-08-22 02:37:51 +0000] [6] [INFO] Booting worker with pid: 6
[2023-08-22 02:37:51 +0000] [7] [INFO] Booting worker with pid: 7
[2023-08-22 02:37:51 +0000] [8] [INFO] Booting worker with pid: 8
[2023-08-22 02:37:51 +0000] [9] [INFO] Booting worker with pid: 9
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Downloading (…)okenizer_config.json: 100%|██████████| 28.0/28.0 [00:00<00:00, 164kB/s]
Downloading (…)solve/main/vocab.txt: 100%|██████████| 232k/232k [00:00<00:00, 7.46MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 466k/466k [00:00<00:00, 5.80MB/s]
Downloading (…)lve/main/config.json: 100%|██████████| 570/570 [00:00<00:00, 3.17MB/s]
[2023-08-22 02:38:11 +0000] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/main.py", line 43, in <module>
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 68, in from_vector_store
    return cls(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 46, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 158, in from_defaults
    node_parser = node_parser or _get_default_node_parser(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 28, in _get_default_node_parser
    return SimpleNodeParser.from_defaults(
  File "/usr/local/lib/python3.10/site-packages/llama_index/node_parser/simple.py", line 56, in from_defaults
    text_splitter = text_splitter or get_default_text_splitter(
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/__init__.py", line 22, in get_default_text_splitter
    return SentenceSplitter(
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/sentence_splitter.py", line 91, in __init__
    chunking_tokenizer_fn = chunking_tokenizer_fn or split_by_sentence_tokenizer()
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/utils.py", line 38, in split_by_sentence_tokenizer
    cache_dir = get_cache_dir()
  File "/usr/local/lib/python3.10/site-packages/llama_index/utils.py", line 275, in get_cache_dir
    os.makedirs(path)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/llama_index'
[2023-08-22 02:38:11 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/main.py", line 43, in <module>
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 68, in from_vector_store
    return cls(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 46, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 158, in from_defaults
    node_parser = node_parser or _get_default_node_parser(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 28, in _get_default_node_parser
    return SimpleNodeParser.from_defaults(
  File "/usr/local/lib/python3.10/site-packages/llama_index/node_parser/simple.py", line 56, in from_defaults
    text_splitter = text_splitter or get_default_text_splitter(
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/__init__.py", line 22, in get_default_text_splitter
    return SentenceSplitter(
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/sentence_splitter.py", line 91, in __init__
    chunking_tokenizer_fn = chunking_tokenizer_fn or split_by_sentence_tokenizer()
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/utils.py", line 38, in split_by_sentence_tokenizer
    cache_dir = get_cache_dir()
  File "/usr/local/lib/python3.10/site-packages/llama_index/utils.py", line 275, in get_cache_dir
    os.makedirs(path)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/llama_index'
[2023-08-22 02:38:11 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/main.py", line 43, in <module>
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 68, in from_vector_store
    return cls(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 46, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 158, in from_defaults
    node_parser = node_parser or _get_default_node_parser(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 28, in _get_default_node_parser
    return SimpleNodeParser.from_defaults(
  File "/usr/local/lib/python3.10/site-packages/llama_index/node_parser/simple.py", line 56, in from_defaults
    text_splitter = text_splitter or get_default_text_splitter(
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/__init__.py", line 22, in get_default_text_splitter
    return SentenceSplitter(
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/sentence_splitter.py", line 91, in __init__
    chunking_tokenizer_fn = chunking_tokenizer_fn or split_by_sentence_tokenizer()
  File "/usr/local/lib/python3.10/site-packages/llama_index/text_splitter/utils.py", line 38, in split_by_sentence_tokenizer
    cache_dir = get_cache_dir()
  File "/usr/local/lib/python3.10/site-packages/llama_index/utils.py", line 275, in get_cache_dir
    os.makedirs(path)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/llama_index'
[2023-08-22 02:38:11 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-08-22 02:38:11 +0000] [8] [INFO] Worker exiting (pid: 8)
[2023-08-22 02:38:11 +0000] [9] [INFO] Worker exiting (pid: 9)
[nltk_data] Downloading package punkt to /tmp/llama_index...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[2023-08-22 02:38:14 +0000] [1] [ERROR] Worker (pid:8) exited with code 3
[2023-08-22 02:38:14 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-08-22 02:38:14 +0000] [1] [ERROR] Shutting down: Master
[2023-08-22 02:38:14 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

**Comment by logan-markewich** [comment]
Thanks for flagging this @amarkules1 I'll try to have a fix for this later today (but also feel free to submit a PR as well!)

**Comment by amarkules1** [comment]
@logan-markewich created a PR editing that one line https://github.com/jerryjliu/llama_index/pull/7365. Let me know if there's anything more I should do.
