### ISSUE TITLE
[Bug]:   File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__ ValueError: "EntityExtractor" object has no field "_model"

### ISSUE THREAD

**Issue by kylemassimilian** [jerryjliu/llama_index#7405]
### Bug Description

I'm testing out some metadata extraction methods and ran into trouble w/ the EntityExtractor. I believe I'm following the example in the docs pretty closely:

[https://gpt-index.readthedocs.io/en/stable/examples/metadata_extraction/EntityExtractionClimate.html](url)

I noticed there might be a syntax issue in metadata_extractors.py and thought  `_model: Any = PrivateAttr`  should be   `_model: Any = PrivateAttr()` but not totally sure:

```
class EntityExtractor(MetadataFeatureExtractor):
    """
    Entity extractor. Extracts `entities` into a metadata field using a default model
    `tomaarsen/span-marker-mbert-base-multinerd` and the SpanMarker library.

    Install SpanMarker with `pip install span-marker`.
    """

    model_name: str = Field(
        default=DEFAULT_ENTITY_MODEL,
        description="The model name of the SpanMarker model to use.",
    )
    prediction_threshold: float = Field(
        default=0.5, description="The confidence threshold for accepting predictions."
    )
    span_joiner: str = Field(description="The seperator beween entity names.")
    label_entities: bool = Field(
        default=False, description="Include entity class labels or not."
    )
    device: Optional[str] = Field(
        default=None, description="Device to run model on, i.e. 'cuda', 'cpu'"
    )
    entity_map: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of entity class names to usable names.",
    )

    _tokenizer: Callable = PrivateAttr()
    _model: Any = PrivateAttr
```

When I add the parenthesis, however, I get a different error, so I can't say I'm confident in the alteration.

```
(venv) PS C:\Users\Kyle\DEV\Satori\IX MVP\scripts> python extract_meta_test1.py
C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\accelerate\utils\dataclasses.py:29: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 119549. This might 
induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
Traceback (most recent call last):
  File "C:\Users\Kyle\DEV\Satori\IX MVP\scripts\extract_meta_test1.py", line 134, in <module>
    extract_metadata()
  File "C:\Users\Kyle\DEV\Satori\IX MVP\scripts\extract_meta_test1.py", line 118, in extract_metadata
    EntityExtractor(prediction_threshold=0.5, label_entities=False, device="cpu"),
  File "C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\llama_index\node_parser\extractors\metadata_extractors.py", line 532, in __init__
    super().__init__(
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for EntityExtractor
entity_map
  none is not an allowed value (type=type_error.none.not_allowed)
```

### Version

0.8.9

### Steps to Reproduce

```
def extract_metadata():
    llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
    documents = SimpleDirectoryReader("Data").load_data()

    text_splitter = TokenTextSplitter(separator=" ", chunk_size=1024, chunk_overlap=128)
    
    
    metadata_extractor = MetadataExtractor(
      extractors=[
            #TitleExtractor(nodes=5, llm=llm),
            #QuestionsAnsweredExtractor(questions=3, llm=llm),
            EntityExtractor(prediction_threshold=0.5, label_entities=False, device="cpu"),
            #SummaryExtractor(summaries=["prev", "self"], llm=llm),
            #KeywordExtractor(keywords=2, llm=llm),
            #DateExtractor()
            #CustomExtractor()
      ])
      
    node_parser = SimpleNodeParser(
      text_splitter=text_splitter, metadata_extractor=metadata_extractor)
    
    nodes = node_parser.get_nodes_from_documents(documents)
    
    #for node in nodes:
    print(nodes[0].metadata)
    return nodes
```

Tried with both `EntityExtractor(prediction_threshold=0.5, label_entities=False, device="cpu"` and `EntityExtractor(prediction_threshold=0.5)`

### Relevant Logs/Tracbacks

```shell
(venv) PS C:\Users\Kyle\DEV\Satori\IX MVP\scripts> python extract_meta_test1.py
C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\accelerate\utils\dataclasses.py:29: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 119549. This might 
induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
Traceback (most recent call last):
  File "C:\Users\Kyle\DEV\Satori\IX MVP\scripts\extract_meta_test1.py", line 134, in <module>
    extract_metadata()
  File "C:\Users\Kyle\DEV\Satori\IX MVP\scripts\extract_meta_test1.py", line 118, in extract_metadata
    EntityExtractor(prediction_threshold=0.5, label_entities=False, device="cpu"),
  File "C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\llama_index\node_parser\extractors\metadata_extractors.py", line 522, in __init__
    self._model = SpanMarkerModel.from_pretrained(model_name)
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EntityExtractor" object has no field "_model"
```
```

**Comment by logan-markewich** [comment]
@kylemassimilian oof, that is 100% my bad. Will patch shortly. Need to cut a new version for pypi anyways, so good timing :)

**Comment by logan-markewich** [comment]
Just cut v0.8.10 with this fix 💯
