### ISSUE TITLE
[Bug]: PGVECTOR sqlalchemy.exc.StatementError: (builtins.ValueError) expected 1536 dimensions, not 4096

### ISSUE THREAD

**Issue by GenAIHub** [jerryjliu/llama_index#7490]
### Bug Description

Using other embeddings model with different then 1536 dimensions that OpenAI embedding model have, will get an error when I create the index.

ValueError: expected 1536 dimensions, not 4096

### Version

0.8.13

### Steps to Reproduce

embed_model_config = LangchainEmbedding(
        BedrockEmbeddings(
            credentials_profile_name=credentials_profile_name,
            region_name=region_name,
            model_id=embedding_model
        )
    )
	

service_context = ServiceContext.from_defaults(
        embed_model=embed_model_config,
        chunk_size=chunk_size,
    )

storage_context = StorageContext.from_defaults(
	vector_store=vector_store
)

index = VectorStoreIndex.from_documents(pages,
										storage_context=storage_context,
										service_context=service_context,
										)

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1486, in _init_compiled
    d_param = {
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1487, in <dictcomp>
    key: flattened_processors[key](compiled_params[key])
  File "/home/user/.local/lib/python3.10/site-packages/pgvector/sqlalchemy/__init__.py", line 21, in process
    return to_db(value, self.dim)
  File "/home/user/.local/lib/python3.10/site-packages/pgvector/utils/__init__.py", line 35, in to_db
    raise ValueError('expected %d dimensions, not %d' % (dim, len(value)))
ValueError: expected 1536 dimensions, not 4096

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/test/insert.py", line 131, in <module>
    main()
  File "/mnt/d/test/insert.py", line 124, in main
    index = VectorStoreIndex.from_documents(pages,
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/indices/base.py", line 102, in from_documents
    return cls(
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 46, in __init__
    super().__init__(
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 241, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 229, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 202, in _add_nodes_to_index
    new_ids = self._vector_store.add(embedding_results)
  File "/home/user/.local/lib/python3.10/site-packages/llama_index/vector_stores/postgres.py", line 147, in add
    session.commit()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4314, in _flush
    with util.safe_reraise():
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = connection.execute(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
    self._handle_dbapi_exception(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1486, in _init_compiled
    d_param = {
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1487, in <dictcomp>
    key: flattened_processors[key](compiled_params[key])
  File "/home/user/.local/lib/python3.10/site-packages/pgvector/sqlalchemy/__init__.py", line 21, in process
    return to_db(value, self.dim)
  File "/home/user/.local/lib/python3.10/site-packages/pgvector/utils/__init__.py", line 35, in to_db
    raise ValueError('expected %d dimensions, not %d' % (dim, len(value)))
sqlalchemy.exc.StatementError: (builtins.ValueError) expected 1536 dimensions, not 4096
[SQL: INSERT INTO data_bd_embeddings (text, metadata_, node_id, embedding) SELECT p0::VARCHAR, p1::JSON, p2::VARCHAR, p3::VECTOR(1536) FROM (VALUES (%(text)s, %(metadata_)s, %(node_id)s, %(embedding)s)) AS imp_sen(p0, p1, p2, p3, sen_counter) ORDER BY sen_counter RETURNING data_bd_embeddings.id, data_bd_embeddings.id AS id__1]
[parameters: [{'metadata_': {'page_label': '1', 'file_name': '100KB.pdf', '_node_content': '{"id_": "2d5b3a86-a3d0-4aa9-b930-b75d6ce7c4a5", "embedding": null, "meta ... (53070 characters truncated) ... .Praesent pell entesque lacus eros, nec auctor neque semper eget.Sed vehicula \nornare efficitur.', 'node_id': '2d5b3a86-a3d0-4aa9-b930-b75d6ce7c4a5'}, {'metadata_': {'page_label': '1', 'file_name': '100KB.pdf', '_node_content': '{"id_": "957b4421-8e49-4047-9a0a-0b0f3e6a45ef", "embedding": null, "meta ... (53160 characters truncated) ... corper et euismod eget, facilisis sed nibh.Vestibulum fermentum augue a lacus mattis condimentum.', 'node_id': '957b4421-8e49-4047-9a0a-0b0f3e6a45ef'}, {'metadata_': {'page_label': '1', 'file_name': '100KB.pdf', '_node_content': '{"id_": "e7011450-42e1-4ee7-925e-492b50e342ac", "embedding": null, "meta ... (51954 characters truncated) ... n \nsuscipit sed, volutpat id nisl.Orci varius natoque penatibus et magnis dis parturient montes,', 'node_id': 'e7011450-42e1-4ee7-925e-492b50e342ac'}, {'metadata_': {'page_label': '2', 'file_name': '100KB.pdf', '_node_content': '{"id_": "46a3799f-99ca-439b-a754-f4e5bee32829", "embedding": null, "meta ... (52590 characters truncated) ... \neu lacus eu, eleifend malesuada lorem. Praesent quis justo ligula. Cras quam risus, ultricies .', 'node_id': '46a3799f-99ca-439b-a754-f4e5bee32829'}]]
```

**Comment by GenAIHub** [comment]
@dosu-bot, so issue is that llamaindex is not compatible with LangchainEmbedding ?

embedding_model = "amazon.titan-e1t-medium"
    embed_model_config = LangchainEmbedding(
        BedrockEmbeddings(
            credentials_profile_name=credentials_profile_name,
            region_name=region_name,
            model_id=embedding_model
        )
    )

**Comment by logan-markewich** [comment]
@GenAIHub hmm, I see the issue, the `embedding` column is hardcoded to 1536. I think it will work for embedding models that are smaller, but not larger

Let me see if I can fix that

For reference
https://github.com/jerryjliu/llama_index/blob/8a4da2aa7bff29e809722992e78498dc9f70cbe4/llama_index/vector_stores/postgres.py#L33

**Comment by logan-markewich** [comment]
Should be in the next pypi release, or you can install from source to get the fix now :) 

Just have to specify `embed_dim` in the constructor

```
vector_store = PGVectorStore.from_params(..., embed_dim=1536)
...
vector_store = PGVectorStore(..., embed_dim=1536)
```

**Comment by GenAIHub** [comment]
@logan-markewich Thank you, after adding `embed_dim`, import is working now.
