### ISSUE TITLE
[Bug]: Creating a knowledge graphs triggers Azure OpenAI's content policy

### ISSUE THREAD

**Issue by Jegama** [jerryjliu/llama_index#7500]
### Bug Description

I want to create a vector index and a knowledge graph. The vector index works fine. However, when I want to create the knowledge graph, it triggers Azure OpenAI's content policy. Why is that?

I'm using `from llama_index.llms import AzureOpenAI` as the LLM. Why does it trigger it with the knowledge graph and not the vector index?

### Version

0.8.7

### Steps to Reproduce

```
documents_ = []

for file in tqdm(all_page_ids):
    cleaned, table_dict, urls, last_mod, report_url, title, valid = confluence_helper.process_page(file)

    if not valid:
        continue
    
    titles.append(title)
    documents = TextLoader('temp/temp.txt', encoding='utf-8').load()
    for doc in documents:
        nodes = confluence_helper.process_metadata(doc, last_mod, report_url, title, table_dict, node_parser)
        librarian_vector_index.insert_nodes(nodes)
        documents_.extend(nodes)

librarian_vector_index.storage_context.persist(persist_dir='librarian_vector_index')

librarian_graph_index = KnowledgeGraphIndex(documents_, max_triplets_per_chunk=5, include_embeddings=True, storage_context=storage_context)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\jmancilla\OneDrive - Roku Inc\Dev\uxr-librarian\generate_index.py", line 101, in <module>
    print(f'\nGraph index populated in {(time.time() - start)/60:.3f} minutes')
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\indices\knowledge_graph\base.py", line 85, in __init__
    super().__init__(
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\indices\base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\indices\base.py", line 171, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\indices\knowledge_graph\base.py", line 171, in _build_index_from_nodes
    triplets = self._extract_triplets(
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\indices\knowledge_graph\base.py", line 122, in _extract_triplets
    return self._llm_extract_triplets(text)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\indices\knowledge_graph\base.py", line 126, in _llm_extract_triplets
    response = self._service_context.llm_predictor.predict(
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\llm_predictor\base.py", line 105, in predict
    chat_response = self._llm.chat(messages)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\llms\base.py", line 140, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\llms\openai.py", line 106, in chat
    return chat_fn(messages, **kwargs)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\llms\openai.py", line 163, in _chat
    response = completion_with_retry(
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\llms\openai_utils.py", line 138, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\llama_index\llms\openai_utils.py", line 136, in _completion_with_retry
    return client.create(**kwargs)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\jmancilla\Anaconda3\envs\librarian\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766
```

**Comment by Jegama** [comment]
Yeah, the workaround is to delete the offending text. But the articles are research reports, it doesn't make sense. I just updated to 0.8.15 and I'm re-indexing. I'll come back once it's done.

**Comment by logan-markewich** [comment]
Yea sadly, azure is super strict about this

**Comment by Jegama** [comment]
But why is it complaining with the kg, and not with the vector index? I'm using the same llm.

**Comment by logan-markewich** [comment]
The kg uses the LLM to extract triplets. Maybe something about what I generated violated their content policy somehow?

**Comment by Jegama** [comment]
I see. I'll try to debug a little bit more. 0.8.15 gives the same error.

I'll also try to connect with the MS support team that is managing our company's instance to see what we can do.

**Comment by rajendra-t** [comment]
I am facing the same error while building KG using  llama Index 0.8.30 as well. Is there any solution identified for this?

**Comment by logan-markewich** [comment]
I'm not sure what a solution would be for this. We can't control azures content policy 😅

Maybe something about the data you are indexing is triggering this?
