### ISSUE TITLE
[Bug]: `RecursionError: maximum recursion depth exceeded while calling a Python object` for `HierarchicalNodeParser`

### ISSUE THREAD

**Issue by Whisht** [jerryjliu/llama_index#7505]
### Bug Description

After installing llama-index following [install from the source](https://gpt-index.readthedocs.io/en/stable/getting_started/installation.html) with `pip install -r requirements.txt`. I tried to parse some Chinese documents with metadata to nodes using HierarchicalNodeParser, and it hints at the RecursionError.

### Version

0.8.13

### Steps to Reproduce

Here are the minimal codes required for reproduction.

```python
from llama_index.node_parser import HierarchicalNodeParser
from llama_index import Document

docs = [
    {
        "title": "伊拉克通讯",
        "text": "伊拉克通讯\n\n本条目是有关伊拉克的通讯状况。\n\n2001年前的伊拉克通讯，可以说是一穷二白，主要的交换机是使用国内的两家大通讯商。\n\n2003年的伊拉克战争严重破坏了包括国际通讯在内的电讯业。美国国际开发署为此修理了交换容量，并且建立了一个移动和卫星通讯工具。目前有线通讯已经超过了战前的水平。\n\n\n在2003年期间遭受破坏的交换机和干线已经修复，但是仍然存在被破坏的问题。交换容量正在提高准入。移动通讯已经被广泛使用，并且一个大城市为中心建立了三个GSM网络，全国范围的连通性得到了完善。目前有870万的移动通讯用户。\n\n国际长途代码：964\n\n卫星基站：2（1个在大西洋，1个在印度洋）\n\n1个全球卫星通讯系统在大西洋地区。1个阿拉伯通讯卫星（不起作用）\n\n同轴电缆和微波无线电中继与约旦、科威特、叙利亚、 土耳其连接。尽管新建了卫星网关，但是巴格达以外的国际电话还经常出问题。\n\n不受管制的媒体经过17个月的增长，在伊拉克境内已经有了大约80个电台（2004年）。\n\n电视台: 21(2004年)\n\n因特网国家代码:.iq\n\n互联网服务商:5(2006年)\n\n网民:36,000(2005年)\n",
        "summarization": "伊拉克通讯在2003年战争后得到重建，有线通讯超过战前水平，移动通讯广泛使用，拥有870万用户。国际长途代码为964，与周边国家连接。境内媒体增长，拥有多个电台和电视台。",
    },
    {
        "title": "夏小正",
        "text": "夏小正\n\n《夏小正》为中国现存最早的科学文献之一，也是中国现存最早的一部农事历书，原为《大戴礼记》中的第47篇。\n\n夏小正原文收入《大戴礼记》中，在唐宋时期散佚（而大戴礼记亦有一半同时散佚）。现存的《夏小正》为宋朝傅崧卿著《夏小正传》把当时所藏之两个版本《夏小正》文稿汇集而成。但因经文与传文（以自己的文字解释）在篇章中混集而没有说明之关系，《夏小正传》中不尽是原来之全部篇章。\n\n因原稿散佚与成形之问题，成稿年代争论很大，但一般认为最迟成书在春秋时期；据西汉时期的《史记‧夏本纪》载：「太史公曰：孔子正夏时，学者多传《夏小正》-{云}-」。故人们认为是孔丘及其门生考察后所记载下的农事历书，所收录之有关夏朝的也多是物候等文化讯息。\n\n书中除二月、十一与十二月外，每月载有确定季节的星象（主要是拱极星象与黄道星象）以指导务农生产，另外亦有记载当月植物之生长形态、动物之活动习性与祭祀(亦为物候学之重要典籍)。\n\n由于内容涉及星象与农业赖以使用之历法的关系，对古代天象与先秦历法研究也有相当重要之参考价值。\n\n",
        "summarization": "《夏小正》是中国现存最早的科学文献之一，原为《大戴礼记》的第47篇，现存版本由宋朝傅崧卿编撰。书中记录了各月份的星象、植物生长形态、动物活动习性和祭祀，对古代天象和先秦历法研究具有重要参考价值。",
    },
]
docs = [
    Document(
        text=doc["text"],
        metadata={"title": doc["title"], "summarization": doc["summarization"]},
    )
    for doc in docs
]
parser = HierarchicalNodeParser.from_defaults()
nodes = parser.get_nodes_from_documents(docs)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-95-74f27d5bd0bf>", line 23, in <module>
    parser.get_nodes_from_documents(docs)
  File "~/github/llama_index/llama_index/node_parser/hierarchical.py", line 210, in get_nodes_from_documents
    nodes_from_doc = self._recursively_get_nodes_from_nodes([doc], 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/node_parser/hierarchical.py", line 178, in _recursively_get_nodes_from_nodes
    sub_sub_nodes = self._recursively_get_nodes_from_nodes(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/node_parser/hierarchical.py", line 178, in _recursively_get_nodes_from_nodes
    sub_sub_nodes = self._recursively_get_nodes_from_nodes(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/node_parser/hierarchical.py", line 160, in _recursively_get_nodes_from_nodes
    cur_sub_nodes = get_nodes_from_document(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/node_parser/node_utils.py", line 107, in get_nodes_from_document
    return get_nodes_from_node(
           ^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/node_parser/node_utils.py", line 126, in get_nodes_from_node
    text_splits = text_splitter.split_text_metadata_aware(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/text_splitter/sentence_splitter.py", line 128, in split_text_metadata_aware
    return self._split_text(text, chunk_size=effective_chunk_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/text_splitter/sentence_splitter.py", line 145, in _split_text
    splits = self._split(text, chunk_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/text_splitter/sentence_splitter.py", line 185, in _split
    ns = self._split(split, chunk_size=chunk_size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/text_splitter/sentence_splitter.py", line 185, in _split
    ns = self._split(split, chunk_size=chunk_size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/github/llama_index/llama_index/text_splitter/sentence_splitter.py", line 185, in _split
    ns = self._split(split, chunk_size=chunk_size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2965 more times]
  File "~/github/llama_index/llama_index/text_splitter/sentence_splitter.py", line 166, in _split
    splits = split_fn(text)
             ^^^^^^^^^^^^^^
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 107, in sent_tokenize
    return tokenizer.tokenize(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1281, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1341, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1341, in <listcomp>
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1329, in span_tokenize
    for sentence in slices:
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1459, in _realign_boundaries
    for sentence1, sentence2 in _pair_iter(slices):
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 321, in _pair_iter
    prev = next(iterator)
           ^^^^^^^^^^^^^^
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1431, in _slices_from_text
    for match, context in self._match_potential_end_contexts(text):
  File "~/mambaforge/envs/llama-index/lib/python3.11/site-packages/nltk/tokenize/punkt.py", line 1393, in _match_potential_end_contexts
    previous_slice = slice(0, 0)
                     ^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```
```

**Comment by logan-markewich** [comment]
@Whisht I can add a more helpful error to the log, but the solution here is to either select larger chunk sizes, or decrease the size of your metadata

For example, this will work
```python
HierarchicalNodeParser.from_defaults(chunk_sizes=[2048, 1024, 512])
```

**Comment by Whisht** [comment]
Thanks. 

Is there an effective way to automatically determine the appropriate chunk size? For this reason, the metadata contains a summarization of the text content, which is diverse, ranging from 10s to 400s. 

A compromised way is to set the largest size as the chunk_size, but the large summarizations are only minorities.
