### ISSUE TITLE
[Bug]: validation error for SelectorPromptTemplate kwargs -> existing_answer

### ISSUE THREAD

**Issue by gajavelli** [jerryjliu/llama_index#7551]
### Bug Description

![image](https://github.com/jerryjliu/llama_index/assets/5496552/6fe3b17a-7e70-422f-8681-da61779501f0)

### Version

0.8.13

### Steps to Reproduce

   #Predictor
    llm_streaming_predictor = LLMPredictor(
        llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True)
    )
    Model_Used="gpt-3.5-turbo"
   #service context
    service_streaming_context = ServiceContext.from_defaults(
        llm_predictor=llm_streaming_predictor
    )

    # Configure query engine to use streaming
    query_engine = final_index.as_query_engine(service_context=service_streaming_context,
        streaming=True
    )
    def response_streamExt(query_engine, query ):
        streaming_response = query_engine.query(query)
        for text in streaming_response.response_gen:
            yield text
    # flask response
    return Response(response_streamExt(query_engine, query), mimetype="text/event-stream")

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\werkzeug\wsgi.py", line 462, in __next__
    return self._next()
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\werkzeug\wrappers\response.py", line 50, in _iter_encoded
    for item in iterable:
  File "D:\working\srvless\generic_api\generative_service.py", line 311, in response_streamExt
    streaming_response = query_engine.query(query)
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 171, in _query
    response = self._response_synthesizer.synthesize(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\response_synthesizers\base.py", line 125, in synthesize
    response_str = self.get_response(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\response_synthesizers\compact_and_refine.py", line 34, in get_response
    response = super().get_response(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\response_synthesizers\refine.py", line 125, in get_response
    response = self._refine_response_single(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\response_synthesizers\refine.py", line 243, in _refine_response_single
    refine_template = self._refine_template.partial_format(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\prompts\base.py", line 206, in partial_format
    return SelectorPromptTemplate(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\llama_index\prompts\base.py", line 178, in __init__
    super().__init__(
  File "D:\working\srvless\generic_api\generic_runtime\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for SelectorPromptTemplate
kwargs -> existing_answer
  str type expected (type=type_error.str)
```

**Comment by gajavelli** [comment]
Can somebody please help. Not sure what is going on? The same code works but sometimes keeps failing. Not sure if internally some sort of refining is taking place and erroring out.

Definately it does not indicate failure in the intended code.

Please help or direct to the right documentation or proven example.

**Comment by logan-markewich** [comment]
@gajavelli I see the error here, it is specific to streaming I think. Let me see if I can fix that 😅

**Comment by gajavelli** [comment]
I applied the chnages o my local environment and based on my initial round of testing, the issue appears to be fixed.

Thank you very much.
