### ISSUE TITLE
KeyError: <QueryMode.SUMMARIZE: 'summarize'>

### ISSUE THREAD

**Issue by Tobi-De** [jerryjliu/llama_index#757]
Trying to run the code below result in a KeyError

```python
llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="gpt-3.5-turbo"))
index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor)
index.query("summarize the content", mode="summarize")
```

traceback

```shell
Traceback (most recent call last):
  File "/home/tobi/Builds/documate/ai.py", line 62, in <module>
    main()
  File "/home/tobi/Builds/documate/ai.py", line 47, in main
    summary = index.query("summarize the content", mode="summarize", use_async=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/base.py", line 419, in query
    return query_runner.query(query_str, self._index_struct)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/query/query_runner.py", line 147, in query
    query_obj = self._get_query_obj(index_struct)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/query/query_runner.py", line 117, in _get_query_obj
    query_cls = self._index_registry.type_to_query[index_struct_type][mode]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: <QueryMode.SUMMARIZE: 'summarize'>

```

llama-index = "^0.4.28"
python 3.11

**Comment by jerryjliu** [comment]
Use response_mode="tree_summarize" instead https://gpt-index.readthedocs.io/en/latest/guides/usage_pattern.html#setting-response-mode

**Comment by Tobi-De** [comment]
> Use response_mode="tree_summarize" instead [gpt-index.readthedocs.io/en/latest/guides/usage_pattern.html#setting-response-mode](https://gpt-index.readthedocs.io/en/latest/guides/usage_pattern.html#setting-response-mode)

Ok got it, thanks.
