### ISSUE TITLE
[Question]: Persisting (and loading) index from Neo4J 

### ISSUE THREAD

**Issue by kylemassimilian** [jerryjliu/llama_index#7575]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I assume you do not have to persist an index after building it using Neo4J... but how do you load the index in? 

```
`def build_neo4j():
    llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
    service_context = ServiceContext.from_defaults(llm=llm)
    documents = SimpleDirectoryReader("Data - demo").load_data()
    

    graph_store = Neo4jGraphStore(
        username=username,
        password=password,
        url=url,
        database=database,
    )
    storage_context = StorageContext.from_defaults(graph_store=graph_store)
    index = KnowledgeGraphIndex.from_documents(documents, storage_context, max_tiplets_per_chunk=2, show_progress=True)
`
```

TY

**Comment by kylemassimilian** [comment]
I'm getting the message "No index in storage context, check if you specified the right persist_dir." from my code:

```
`def query_index(query):
       graph_store = Neo4jGraphStore(
        username=neo_username,
        password=neo_password,
        url=neo_url,
        database=neo_database,
    )
       neo_storage_context = StorageContext.from_defaults(graph_store=graph_store)

       neo_index = load_index_from_storage(neo_storage_context)

       graph_storage_context = StorageContext.from_defaults(persist_dir=kg_demo_persist_dir, fs=s3)
       kg_index = load_index_from_storage(graph_storage_context, "demo_kg_index")
       
       vector_storage_context = StorageContext.from_defaults(persist_dir=vector_demo_persist_dir, fs=s3)
       vector_index = load_index_from_storage(vector_storage_context, "demo_vector_index")
       vector_retriever = VectorIndexRetriever(index=vector_index)
       kg_retriever = KGTableRetriever(index=kg_index, 
                                        retriever_mode="keyword", include_text=False)
       custom_retriever = CustomRetriever(vector_retriever, kg_retriever)

       service_context = ServiceContext.from_defaults(llm=llm, chunk_size=512)
       
       reponse_synthesizer = get_response_synthesizer(
        service_context=service_context,
        response_mode="tree_summarize")
       
       custom_query_engine = RetrieverQueryEngine(
        retriever=custom_retriever, response_synthesizer=reponse_synthesizer
    )
    
       # For more detailed answers, send the text from where the triplets were extracted `include_text=True` to LLM
       kg_query_engine = neo_index.as_query_engine(respone_mode="tree_summarize", include_text=True)

       vector_query_engine = vector_index.as_query_engine()

       print("Querying query engine...")
       start_time = time.time()
       
       response = kg_query_engine.query(query)
       #sources = [source_node.node.metadata["file_name"] for source_node in response.source_nodes]
       #source_text = [source_nodes.node.get_text() for source_nodes in response.source_nodes]
       
       end_time = time.time()
       execution_time = end_time - start_time
       print("Query Time:", execution_time)
       return response`
```

after persisting the index:


```
`def build_neo4j():
    llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
    service_context = ServiceContext.from_defaults(llm=llm)
    documents = SimpleDirectoryReader("Data - small").load_data()

    graph_store = Neo4jGraphStore(
        username=neo_username,
        password=neo_password,
        url=neo_url,
        database=neo_database,
    )
    storage_context = StorageContext.from_defaults(graph_store=graph_store)
    neo_index = KnowledgeGraphIndex.from_documents(documents, storage_context, max_tiplets_per_chunk=2, 
                                               service_context=service_context, show_progress=True)
    neo_index.storage_context.persist()
    `
```

and I'm pretty sure my credentials are right (username = neo4j, password = the password when I created my account, url is copy and pasted from the neo4j console with the port, database = neo4j).

Do I need to use bolt here?

 but it's probably an issue with my neo4j creds. Can I have some help with these? 

```
`INFO:llama_index.indices.loading:Loading all indices.
Loading all indices.
Traceback (most recent call last):
  File "C:\Users\Kyle\DEV\Satori\IX MVP\scripts\prep_docs6.py", line 324, in <module>
    reponse = query_index(query)
  File "C:\Users\Kyle\DEV\Satori\IX MVP\scripts\prep_docs6.py", line 261, in query_index
    neo_index = load_index_from_storage(neo_storage_context)
  File "C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\llama_index\indices\loading.py", line 36, in load_index_from_storage
    raise ValueError(                                                                                                                       bject at 0x0000012FDBB305B0>.    
ValueError: No index in storage context, check if you specified the right persist_dir.
C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\neo4j\_sync\driver.py:485: ResourceWarning: Unclosed <neo4j._sync.driver.BoltDriver object at 0x0000012FDBB305B0>.
Object allocated at (most recent call last):
  File "C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\neo4j\_sync\driver.py", line 1220
    return cls(pool, default_workspace_config)
  unclosed_resource_warn(self)
Object allocated at (most recent call last):                                                                                                e the session is deprecated. Plea
  File "C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\neo4j\_sync\driver.py", lineno 1220                                           driver will not close drivers au
    return cls(pool, default_workspace_config)
C:\Users\Kyle\DEV\Satori\IX MVP\venv\lib\site-packages\neo4j\_sync\driver.py:489: DeprecationWarning: Relying on Driver's destructor to close the session is deprecated. Please make sure to close the session. Use it as a context (`with` statement) or make sure to call `.close()` explicitly. Future versions of the driver will not close drivers automatically.
  deprecation_warn(`
```

**Comment by kylemassimilian** [comment]
Would love some guidance here! Still haven't been able to connect to neo4j
