### ISSUE TITLE
[Bug]: "CustomWebPageReader" object has no field "url_metadata"

### ISSUE THREAD

**Issue by Ma-Fukudama** [jerryjliu/llama_index#7656]
### Bug Description

The following error occurs when creating an index with a file name in metadata.
but 0.8.13 creates indexes without problems.

```
Traceback (most recent call last):
  File "~/insertIndex.py", line 62, in <module>
    documents = CustomWebPageReader(html_to_text=True, url_metadata=url_metadata_fn).load_data(
  File "~/insertIndex.py", line 27, in __init__
    self.url_metadata = url_metadata  
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "CustomWebPageReader" object has no field "url_metadata"
```

### Version

0.8.25

### Steps to Reproduce

When I run the source below, an error always occurs

```
user_input = sys.argv[1]

class CustomWebPageReader(SimpleWebPageReader):
    def __init__(self, html_to_text=False, url_metadata=None):
        self.url_metadata = url_metadata 
        super().__init__(html_to_text)

    def load_data(self, urls):
        documents = super().load_data(urls)
        if self.url_metadata is not None:
            for doc, url in zip(documents, urls):
                metadata = self.url_metadata(url)
                doc.metadata.update(metadata)
        return documents

file_extension = os.path.splitext(user_input)[1].lower()

url_pattern = r'^https?://[^\s/$.?#].[^\s]*$'

if file_extension in ('.pdf', '.docx', '.txt'):
    filename_fn = lambda filename: {'file_name': filename}
    documents = SimpleDirectoryReader(input_files=text_list,  file_metadata=filename_fn).load_data()

# URL
elif re.match(url_pattern, user_input):

    url_metadata_fn = lambda url: {'file_name': url}

    documents = CustomWebPageReader(html_to_text=True, url_metadata=url_metadata_fn).load_data(
        [
            user_input
        ]
    )
```

**Comment by logan-markewich** [comment]
Yea the base class switched to be a pedantic object. You can't use `self.variable = var` in the init with pydantic. 

The bots suggestion is nearly right, here's the correct version

```
from typing import Callable, Optional

class CustomWebPageReader(SimpleWebPageReader):
    url_metadata: Optional[Callable] = None  # Add this line

    def __init__(self, html_to_text=False, url_metadata=None):
        super.__init__(html_to_text=html_to_text, url_metadata=url_metadata)
```

But tbh, the base `SimpleWebPageReader` has the same functionality with the `metadata_fn` kwarg. You could just use that

```
loader = SimpleWebPageReader(metadata_fn=url_metadata)
```

**Comment by Ma-Fukudama** [comment]
@logan-markewich 
Now it works, thank you
```
    def __init__(self, html_to_text=False, url_metadata=None, **kwargs):
        super().__init__(html_to_text=html_to_text, **kwargs)  
        self.url_metadata = url_metadata
```
