### ISSUE TITLE
[Bug]: AzureOpenAI.stream_chat causes AttributeError

### ISSUE THREAD

**Issue by apptaro** [jerryjliu/llama_index#7657]
### Bug Description

PR #7646 has introduced another issue instead of fixing the bug #7640
Now, AzureOpenAI.stream_chat causes AttributeError.

Look here:
https://github.com/jerryjliu/llama_index/blob/276d976c1cadbee316e6a777b2b37cccfd1d59f0/llama_index/llms/openai.py#L232
and here:
https://github.com/jerryjliu/llama_index/blob/276d976c1cadbee316e6a777b2b37cccfd1d59f0/llama_index/llms/openai.py#L451

"delta" is supposed to be something like { "role": "", content: "" } instead of ""

### Version

0.8.25

### Steps to Reproduce

Run the following code to reproduce the issue:

```
import os
from llama_index.llms import OpenAI, AzureOpenAI
from llama_index.llms.base import ChatMessage

use_azure = True

if use_azure:
    os.environ["OPENAI_API_TYPE"] = "azure"
    os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"
    os.environ["OPENAI_API_BASE"] = "https://xxxx.openai.azure.com/"
    os.environ["OPENAI_API_KEY"] = "xxxxxxxxxxxxxxxxxxxxxxx"
    llm = AzureOpenAI(engine = "gpt-35-turbo")
else:
    os.environ["OPENAI_API_TYPE"] = "open_ai"
    os.environ["OPENAI_API_KEY"] = "sk-xxxxxxxxxxxxxxxxxxxxxxx"
    os.environ["OPENAI_API_BASE"] = "https://api.openai.com/v1"
    llm = OpenAI()

for delta in llm.stream_chat([ChatMessage(content = "Hello!")]):
    print(delta)
```

### Relevant Logs/Tracbacks

```shell
$ python3 test.py
Traceback (most recent call last):
  File "/home/ubuntuuser/LlamaIndex_env/project/test.py", line 19, in <module>
    for delta in llm.stream_chat([ChatMessage(content = "Hello!")]):
  File "/home/ubuntuuser/LlamaIndex_env/lib/python3.10/site-packages/llama_index/llms/base.py", line 157, in wrapped_gen
    for x in f_return_val:
  File "/home/ubuntuuser/LlamaIndex_env/lib/python3.10/site-packages/llama_index/llms/openai.py", line 233, in gen
    role = delta.get("role", "assistant")
AttributeError: 'str' object has no attribute 'get'
```

**Comment by apptaro** [comment]
1. Happening consistently
2. Not only for specific condition
3. I'm using Python 3.10.11, but this issue is not python version specific
4. No

**Comment by logan-markewich** [comment]
@apptaro ha whoops. I don't have access to azure, so hard to actually test it. Will fix again
