### ISSUE TITLE
[Bug]: 'StorageContext' object has no attribute 'callback_manager' for DynamoDB stores

### ISSUE THREAD

**Issue by acastro2** [jerryjliu/llama_index#7666]
### Bug Description

I'm getting 'StorageContext' object has no attribute 'callback_manager' when setting DynamoDB as the store context.

### Version

0.8.26

### Steps to Reproduce

Running it inside Docker:

```dockerfile
FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y gcc-c++ make cmake

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

ENV OPENAI_API_KEY=xxx
ENV AWS_ACCESS_KEY_ID=yyy
ENV AWS_SECRET_ACCESS_KEY=zzz
ENV AWS_DEFAULT_REGION=us-east-1

# Install the specified packages
RUN pip install -r requirements.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.handler" ]

```

```python
from llama_index import VectorStoreIndex, StorageContext, ServiceContext, set_global_service_context, set_global_service_context, SummaryIndex, SimpleKeywordTableIndex, SimpleWebPageReader
from llama_index.vector_stores.dynamodb import DynamoDBVectorStore
from llama_index.storage.index_store.dynamodb_index_store import DynamoDBIndexStore
from llama_index.storage.docstore.dynamodb_docstore import DynamoDBDocumentStore
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0, max_tokens=200)

service_context = ServiceContext.from_defaults(llm=llm, chunk_size=600)

set_global_service_context(service_context)

documents = SimpleWebPageReader(html_to_text=True).load_data(
    ["https://www.cashnetusa.com/faq.html", "http://www.zappos.com/general-questions"]
)

table_name = "LlamaIndexVectors"

storage_context = StorageContext.from_defaults(
    docstore=DynamoDBDocumentStore.from_table_name(table_name=table_name),
    index_store=DynamoDBIndexStore.from_table_name(table_name=table_name),
    vector_store=DynamoDBVectorStore.from_table_name(table_name=table_name),
)

storage_context.docstore.add_documents(documents)

set_global_service_context(storage_context)

vector_index = VectorStoreIndex.from_documents(documents)
keyword_table_index = SimpleKeywordTableIndex.from_documents(documents)
summary_index = SummaryIndex.from_documents(documents)

storage_context.persist()
```

### Relevant Logs/Tracbacks

```shell
[ERROR] AttributeError: 'StorageContext' object has no attribute 'callback_manager'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 84, in handler
    summary_index = SummaryIndex(documents, storage_context=storage_context)
  File "/var/lang/lib/python3.11/site-packages/llama_index/indices/list/base.py", line 56, in __init__
    super().__init__(
  File "/var/lang/lib/python3.11/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/var/lang/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 138, in from_defaults
    return cls.from_service_context(
  File "/var/lang/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 220, in from_service_context
    callback_manager = callback_manager or service_context.callback_manager
[ERROR] AttributeError: 'StorageContext' object has no attribute 'callback_manager' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 84, in handler     summary_index = SummaryIndex(documents, storage_context=storage_context)   File "/var/lang/lib/python3.11/site-packages/llama_index/indices/list/base.py", line 56, in __init__     super().__init__(   File "/var/lang/lib/python3.11/site-packages/llama_index/indices/base.py", line 61, in __init__     self._service_context = service_context or ServiceContext.from_defaults()   File "/var/lang/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 138, in from_defaults     return cls.from_service_context(   File "/var/lang/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 220, in from_service_context     callback_manager = callback_manager or service_context.callback_manager
```

**Comment by acastro2** [comment]
Good bot
