### ISSUE TITLE
GoogleDocsReader - Request contains an invalid argument

### ISSUE THREAD

**Issue by am17torres** [jerryjliu/llama_index#775]
I'm trying to implement the GoogleDocsReader [following the instructions here](https://gpt-index.readthedocs.io/en/latest/how_to/data_connectors.html#data-connectors-llamahub).

```python
from llama_index import GPTSimpleVectorIndex, download_loader

GoogleDocsReader = download_loader('GoogleDocsReader')

gdoc_ids = ['1wf-y2pd9C878Oh-FmLH7Q_BQkljdm6TQal-c1pUfrec'] # I've substituted my google doc id in my code
loader = GoogleDocsReader()
documents = loader.load_data(document_ids=gdoc_ids)
index = GPTSimpleVectorIndex(documents)
index.query('Where did the author go to school?')
```

I managed to get auth working using the oauth2 flow and have a token.json file 

Quick aside - [had to set the port to any fixed value from 0](https://github.com/jerryjliu/llama_index/blob/main/gpt_index/readers/google_readers/gdocs.py#L107) so I could setup the `redirect_url`, otherwise it would randomly pick the port and I'd get a mismatch url.

The bigger issue is now that I'm authenticated, enabled the GoogleDocs Api in GCP, and go to run the script. 

```
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
Traceback (most recent call last):
  File "~/gpt_docs/index.py", line 11, in <module>
    documents = loader.load_data(document_ids=gdoc_ids)
  File "~/Library/Application Support/pdm/venv/lib/python3.9/site-packages/llama_index/readers/llamahub_modules/google_docs/base.py", line 45, in load_data
    doc = self._load_doc(document_id)
  File "~/Library/Application Support/pdm/venv/lib/python3.9/site-packages/llama_index/readers/llamahub_modules/google_docs/base.py", line 62, in _load_doc
    doc = docs_service.documents().get(documentId=document_id).execute()
  File "~/Library/Application Support/pdm/venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "~/Library/Application Support/pdm/venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://docs.googleapis.com/v1/documents/<REDACTED>?alt=json returned "Request contains an invalid argument.". Details: "Request contains an invalid argument.">
```

excerpt from pyproject.toml

```toml
dependencies = [
    "llama-index>=0.4.29",
    "openai>=0.27.2",
    "google-api-python-client>=2.81.0",
    "google-auth-httplib2>=0.1.0",
    "google-auth-oauthlib>=1.0.0",
]
```

Is this a package issue or am I missing something obvious. Thanks!

**Comment by am17torres** [comment]
Ugh...I figured it out. I was using a the Google Docs folder id, assuming it would pull in all documents. When I changed the id to a document id the errors have resolved.
