### ISSUE TITLE
[Bug]: `BaseSQLTableQueryEngine._parse_response_to_sql` not reliably extracting SQL

### ISSUE THREAD

**Issue by jamesbraza** [jerryjliu/llama_index#7865]
### Bug Description

When using the default LlamaIndex embeddings model, my `NLSQLTableQueryEngine` query works.

Next, when trying to use `OllamaEmbeddings(model="llama2:13b")`, it's not currently working with LlamaIndex's `NLSQLTableQueryEngine`.  I get a `psycopg2.errors.SyntaxError: syntax error at or near "Sure"`.

I believe the issue is the embeddings model outputting something that is not pure SQL, but basically a full-blown response.

I am wondering if https://github.com/jerryjliu/llama_index/blob/v0.8.34/llama_index/prompts/default_prompts.py#L188 is not currently adapted to work with `llama2:13b`?  Perhaps we need to expand this prompt?

### Version

0.8.34

### Steps to Reproduce

Also with `SQLAlchemy==2.0.21` and `psycopg2==2.9.7`:

```python
from langchain.embeddings import OllamaEmbeddings
from llama_index.llms.ollama import Ollama

nl_query_engine = NLSQLTableQueryEngine(
    ...,
    service_context=ServiceContext.from_defaults(
        llm=Ollama(model="llama2:13b"), embed_model=OllamaEmbeddings(model="llama2:13b")
    )
)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "Sure"
LINE 1: Sure! I'd be happy to help you with that. Here's the SQL que...
        ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/user/code/llama_index/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/llama_index/llama_index/indices/struct_store/sql_query.py", line 282, in _query
    raw_response_str, metadata = self._sql_database.run_sql(sql_query_str)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/llama_index/llama_index/langchain_helpers/sql_wrapper.py", line 91, in run_sql
    cursor = connection.execute(text(command))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "Sure"
LINE 1: Sure! I'd be happy to help you with that. Here's the SQL que...
        ^
[SQL: Sure! I'd be happy to help you with that. Here's the SQL query to retrieve the aliases for <redacted>:

SELECT ai.aliases
FROM table1 ci
JOIN table2 cch ON ci.id = cch.<redacted>_id
JOIN table3 clp ON cch.diff LIKE '%%<redacted>%%'
JOIN table4 clb ON clp.column1 = clb.name
JOIN table5 cm ON clb.column2 = cm.name
WHERE cm.id = 1; -- specify the id of the <redacted> you want to retrieve aliases for

The query joins several tables to retrieve all relevant information about <redacted>, including its aliases. The `JOIN` statements are used to link the tables based on common columns. The `WHERE` clause is used to filter the results to only include records with a specific <redacted> ID (in this case, 1).
The query will return a list of all known aliases for <redacted>, which can be useful in various applications such as <redacted>.
Note that the query is written using PostgreSQL syntax and may need to be modified to work with other SQL databases. Additionally, the table names and column names may need to be adjusted based on the specific schema of your database.]
(Background on this error at: https://sqlalche.me/e/20/f405)
python-BaseException
```

**Comment by jamesbraza** [comment]
Update: stepping through the code, the issue is `BaseSQLTableQueryEngine._parse_response_to_sql` is not properly extracting the SQL. Seems @dosu-bot is agreeing with me.  I will further debug and see why it's not working

**Comment by jamesbraza** [comment]
One thought is it could be useful to have SQL validation before actually `execute`ing the SQL query
