### ISSUE TITLE
ChatGptLLMPredictor object has no attribute __llm

### ISSUE THREAD

**Issue by t-h-e-r-o-x** [jerryjliu/llama_index#789]
When I try to query an index defined as following:
`index = GPTListIndex(docs, llm_predictor=llm_predictor)
llm_predictor = ChatGPTLLMPredictor(temperature = 0)`
The following is the stack trace:
`Traceback (most recent call last):
  File "C:\Users\shara\AppData\Local\Temp\ipykernel_20760\2919870425.py", line 5, in <module>
    response = index.query(prompt, )
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\base.py", line 395, in query
    return query_runner.query(query_str, self._index_struct)
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\query\query_runner.py", line 127, in query
    return query_obj.query(query_bundle)
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\token_counter\token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\query\base.py", line 342, in query
    response = self._query(query_bundle)
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\query\base.py", line 318, in _query
    response_str = self._give_response_for_nodes(query_bundle.query_str)
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\query\base.py", line 216, in _give_response_for_nodes
    response = self.response_builder.get_response(
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\response\builder.py", line 318, in get_response
    return self._get_response_default(query_str, prev_response)
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\response\builder.py", line 201, in _get_response_default
    return self.get_response_over_chunks(
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\response\builder.py", line 183, in get_response_over_chunks
    response = self.give_response_single(
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\gpt_index\indices\response\builder.py", line 144, in give_response_single
    response, _ = self.llm_predictor.predict(
  File "c:\Users\shara\anaconda3\envs\YTSummariseGPT\lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 132, in predict
    formatted_prompt = prompt.format(llm=self._llm, **prompt_args)
AttributeError: 'ChatGPTLLMPredictor' object has no attribute '_llm'
`
Note: If I use GPTTreeIndex that leverages the LLM, it will fail at the index building phase citing the same error

**Comment by ankitb82** [comment]
Use the following - 

from langchain.chat_models import ChatOpenAI
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo"))
