### ISSUE TITLE
[Bug] Github Data Loader Error Handling

### ISSUE THREAD

**Issue by stobias123** [jerryjliu/llama_index#907]
If there are any failures in with web calls, the github data loader fails and you have to start data loading all over. 

Example: After about 5 minutes of ingestion, I get this stacktrace.
```
Traceback (most recent call last):
  File "work/main.py", line 18, in <module>
    indexer.index_steampipe_docs(repository_name=collection)
  File "/work/steampipe.py", line 38, in index_steampipe_docs
    docs = reader.load_data(branch=branch)
  File "/Users//.python-envs/lib/python3.9/site-packages/llama_index/readers/github_readers/github_repository_reader.py", line 185, in load_data
    return self._load_data_from_branch(branch)
  File "/Users//.python-envs/lib/python3.9/site-packages/llama_index/readers/github_readers/github_repository_reader.py", line 156, in _load_data_from_branch
    return self._loop.run_until_complete(
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users//.python-envs/lib/python3.9/site-packages/llama_index/readers/github_readers/github_repository_reader.py", line 271, in _generate_documents
    async for blob_data, full_path in buffered_iterator:
  File "/Users//.python-envs/lib/python3.9/site-packages/llama_index/readers/github_readers/utils.py", line 74, in __anext__
    await self._fill_buffer()
  File "/Users//.python-envs/lib/python3.9/site-packages/llama_index/readers/github_readers/utils.py", line 148, in _fill_buffer
    results: List[GitBlobResponseModel] = await asyncio.gather(
  File "/Users//.python-envs/lib/python3.9/site-packages/llama_index/readers/github_readers/github_api_client.py", line 333, in get_blob
    return GitBlobResponseModel.from_json(
  File "/Users//.python-envs/lib/python3.9/site-packages/dataclasses_json/api.py", line 65, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "/Users//.python-envs/lib/python3.9/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/Users//.python-envs/lib/python3.9/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'content
```

I'd suspect this is due to the github rate limit, or perhaps some auth issue, it's hard do say. Would love it if there was error handling in this loader.

**Comment by stobias123** [comment]
Small update: I reduced the number of concurrent requests after waiting a couple hours, and things looked ok. I'm pretty sure it was a rate limiting issue.

GH says [1k requests per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) - then I think they return 429. Idk how much effort it is to add some kind of request backoff, but at least surfacing the error code might be nice.
