### ISSUE TITLE
ValueError: df must be provided.

### ISSUE THREAD

**Issue by antonioaa1979** [jerryjliu/llama_index#999]
Hi,

reg llama-index version: 0.5.1. Querying GPTPandasIndex directly works, but querying it via ComposableGraph returns an error. Steps to reproduce:

```
df = pd.read_csv('toy_dataset.csv')
index = GPTPandasIndex(df=df)
index.query('how many records are in the toy dataset?')

Out[]: Response(response='1000', source_nodes=[], extra_info={'pandas_instruction_str': '\nlen(df)'})

graph = ComposableGraph.from_indices(GPTSimpleKeywordTableIndex, [index], index_summaries=['toy dataset'], max_keywords_per_chunk=50)
graph.query('how many records are in the toy dataset?')

Out[]: 
INFO:llama_index.indices.query.keyword_table.query:> Starting query: how many records are in the toy dataset?
INFO:llama_index.indices.query.keyword_table.query:query keywords: ['records', 'toy', 'dataset']
INFO:llama_index.indices.query.keyword_table.query:> Extracted keywords: ['toy', 'dataset']
Traceback (most recent call last):
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-2a3e815437e2>", line 1, in <module>
    graph.query('how many records are in the toy dataset?')
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/composability/graph.py", line 145, in query
    return query_runner.query(query_str)
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 342, in query
    return query_combiner.run(query_bundle, level)
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_combiner/base.py", line 66, in run
    return self._query_runner.query_transformed(
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 193, in query_transformed
    node_with_score, source_nodes = self._fetch_recursive_nodes(
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 219, in _fetch_recursive_nodes
    response = self.query(query_bundle, index_node.index_id, level + 1)
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 342, in query
    return query_combiner.run(query_bundle, level)
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_combiner/base.py", line 66, in run
    return self._query_runner.query_transformed(
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 183, in query_transformed
    query_obj = self._get_query_obj(index_struct)
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 168, in _get_query_obj
    query_obj = query_cls(
  File "/Users/.pyenv/versions/3.10.6/lib/python3.10/site-packages/llama_index/indices/query/struct_store/pandas.py", line 101, in __init__
    raise ValueError("df must be provided.")
ValueError: df must be provided.
```

**Comment by jerryjliu** [comment]
Hey @antonioaa1979, apologies for the current UX. are you passing in query_configs? try passing the df in as part of the "query_kwargs" section of the query_configs

**Comment by antonioaa1979** [comment]
Thanks Jerry, I have tried it, and I am not sure I am doing it correctly:
